.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00100000, 0x4

glabel func_00100000
    /* 0 00100000 00000000 */  nop
endlabel func_00100000
    /* 4 00100004 00000000 */  nop

.align 3
/* Handwritten function */
nonmatching _start, 0xAC

glabel _start
    /* 8 00100008 6300023C */  lui        $v0, %hi(D_00633C00)
    /* C 0010000C 7200033C */  lui        $v1, %hi(D_71EB98)
    /* 10 00100010 003C4224 */  addiu      $v0, $v0, %lo(D_00633C00)
    /* 14 00100014 98EB6324 */  addiu      $v1, $v1, %lo(D_71EB98)
.align 2
  .L00100018:
    /* 18 00100018 0000407C */  sq         $zero, 0x0($v0)
    /* 1C 0010001C 2B084300 */  sltu       $at, $v0, $v1
    /* 20 00100020 00000000 */  nop
    /* 24 00100024 00000000 */  nop
    /* 28 00100028 00000000 */  nop
    /* 2C 0010002C FAFF2014 */  bnez       $at, .L00100018
    /* 30 00100030 10004224 */   addiu     $v0, $v0, 0x10
    /* 34 00100034 6400043C */  lui        $a0, %hi(D_006388F0)
    /* 38 00100038 FF01053C */  lui        $a1, %hi(D_1FF0000)
    /* 3C 0010003C 0100063C */  lui        $a2, %hi(D_10000)
    /* 40 00100040 6300073C */  lui        $a3, %hi(D_00634000)
    /* 44 00100044 1000083C */  lui        $t0, %hi(func_001000C0)
    /* 48 00100048 F0888424 */  addiu      $a0, $a0, %lo(D_006388F0)
    /* 4C 0010004C 0000A524 */  addiu      $a1, $a1, %lo(D_1FF0000)
    /* 50 00100050 0000C624 */  addiu      $a2, $a2, %lo(D_10000)
    /* 54 00100054 0040E724 */  addiu      $a3, $a3, %lo(D_00634000)
    /* 58 00100058 C0000825 */  addiu      $t0, $t0, %lo(func_001000C0)
    /* 5C 0010005C 2DE08000 */  daddu      $gp, $a0, $zero
    /* 60 00100060 3C000324 */  addiu      $v1, $zero, 0x3C
    /* 64 00100064 0C000000 */  syscall    0 /* handwritten instruction */
    /* 68 00100068 2DE84000 */  daddu      $sp, $v0, $zero
    /* 6C 0010006C 7200043C */  lui        $a0, %hi(D_71EB98)
    /* 70 00100070 0100053C */  lui        $a1, %hi(D_10000)
    /* 74 00100074 98EB8424 */  addiu      $a0, $a0, %lo(D_71EB98)
    /* 78 00100078 0000A524 */  addiu      $a1, $a1, %lo(D_10000)
    /* 7C 0010007C 3D000324 */  addiu      $v1, $zero, 0x3D
    /* 80 00100080 0C000000 */  syscall    0 /* handwritten instruction */
    /* 84 00100084 7802040C */  jal        func_001009E0
    /* 88 00100088 00000000 */   nop
    /* 8C 0010008C E801040C */  jal        func_001007A0
    /* 90 00100090 2D200000 */   daddu     $a0, $zero, $zero
    /* 94 00100094 38000042 */  ei /* handwritten instruction */
    /* 98 00100098 6300023C */  lui        $v0, %hi(D_00634000)
    /* 9C 0010009C 00404224 */  addiu      $v0, $v0, %lo(D_00634000)
    /* A0 001000A0 0000448C */  lw         $a0, 0x0($v0)
    /* A4 001000A4 3E09040C */  jal        func_001024F8
    /* A8 001000A8 04004524 */   addiu     $a1, $v0, 0x4
    /* AC 001000AC 50000408 */  j          func_00100140
    /* B0 001000B0 2D204000 */   daddu     $a0, $v0, $zero
endlabel _start
    /* B4 001000B4 00000000 */  nop
