.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001001B0, 0x10

glabel func_001001B0
    /* 1B0 001001B0 0B000324 */  addiu      $v1, $zero, 0xB
    /* 1B4 001001B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 1B8 001001B8 0800E003 */  jr         $ra
    /* 1BC 001001BC 00000000 */   nop
endlabel func_001001B0
