.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100170, 0x10

glabel func_00100170
    /* 170 00100170 07000324 */  addiu      $v1, $zero, 0x7
    /* 174 00100174 0C000000 */  syscall    0 /* handwritten instruction */
    /* 178 00100178 0800E003 */  jr         $ra
    /* 17C 0010017C 00000000 */   nop
endlabel func_00100170
