.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100180, 0x10

glabel func_00100180
    /* 180 00100180 08000324 */  addiu      $v1, $zero, 0x8
    /* 184 00100184 0C000000 */  syscall    0 /* handwritten instruction */
    /* 188 00100188 0800E003 */  jr         $ra
    /* 18C 0010018C 00000000 */   nop
endlabel func_00100180
