.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100150, 0x10

glabel func_00100150
    /* 150 00100150 05000324 */  addiu      $v1, $zero, 0x5
    /* 154 00100154 0C000000 */  syscall    0 /* handwritten instruction */
    /* 158 00100158 0800E003 */  jr         $ra
    /* 15C 0010015C 00000000 */   nop
endlabel func_00100150
