.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001001E0, 0x10

glabel func_001001E0
    /* 1E0 001001E0 0E000324 */  addiu      $v1, $zero, 0xE
    /* 1E4 001001E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 1E8 001001E8 0800E003 */  jr         $ra
    /* 1EC 001001EC 00000000 */   nop
endlabel func_001001E0
