.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001001A0, 0x10

glabel func_001001A0
    /* 1A0 001001A0 0A000324 */  addiu      $v1, $zero, 0xA
    /* 1A4 001001A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 1A8 001001A8 0800E003 */  jr         $ra
    /* 1AC 001001AC 00000000 */   nop
endlabel func_001001A0
