.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100130, 0x10

glabel func_00100130
    /* 130 00100130 03000324 */  addiu      $v1, $zero, 0x3
    /* 134 00100134 0C000000 */  syscall    0 /* handwritten instruction */
    /* 138 00100138 0800E003 */  jr         $ra
    /* 13C 0010013C 00000000 */   nop
endlabel func_00100130
