.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001001F0, 0x10

glabel func_001001F0
    /* 1F0 001001F0 0F000324 */  addiu      $v1, $zero, 0xF
    /* 1F4 001001F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 1F8 001001F8 0800E003 */  jr         $ra
    /* 1FC 001001FC 00000000 */   nop
endlabel func_001001F0
