.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100190, 0x10

glabel func_00100190
    /* 190 00100190 09000324 */  addiu      $v1, $zero, 0x9
    /* 194 00100194 0C000000 */  syscall    0 /* handwritten instruction */
    /* 198 00100198 0800E003 */  jr         $ra
    /* 19C 0010019C 00000000 */   nop
endlabel func_00100190
