.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100110, 0x10

glabel func_00100110
    /* 110 00100110 01000324 */  addiu      $v1, $zero, 0x1
    /* 114 00100114 0C000000 */  syscall    0 /* handwritten instruction */
    /* 118 00100118 0800E003 */  jr         $ra
    /* 11C 0010011C 00000000 */   nop
endlabel func_00100110
