.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001001D0, 0x10

glabel func_001001D0
    /* 1D0 001001D0 0D000324 */  addiu      $v1, $zero, 0xD
    /* 1D4 001001D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 1D8 001001D8 0800E003 */  jr         $ra
    /* 1DC 001001DC 00000000 */   nop
endlabel func_001001D0
