.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100160, 0x10

glabel func_00100160
    /* 160 00100160 06000324 */  addiu      $v1, $zero, 0x6
    /* 164 00100164 0C000000 */  syscall    0 /* handwritten instruction */
    /* 168 00100168 0800E003 */  jr         $ra
    /* 16C 0010016C 00000000 */   nop
endlabel func_00100160
