.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001001C0, 0x10

glabel func_001001C0
    /* 1C0 001001C0 0C000324 */  addiu      $v1, $zero, 0xC
    /* 1C4 001001C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 1C8 001001C8 0800E003 */  jr         $ra
    /* 1CC 001001CC 00000000 */   nop
endlabel func_001001C0
