.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100120, 0x10

glabel func_00100120
    /* 120 00100120 02000324 */  addiu      $v1, $zero, 0x2
    /* 124 00100124 0C000000 */  syscall    0 /* handwritten instruction */
    /* 128 00100128 0800E003 */  jr         $ra
    /* 12C 0010012C 00000000 */   nop
endlabel func_00100120
