.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001002B0, 0x10

glabel func_001002B0
    /* 2B0 001002B0 FD000324 */  addiu      $v1, $zero, 0xFD
    /* 2B4 001002B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2B8 001002B8 0800E003 */  jr         $ra
    /* 2BC 001002BC 00000000 */   nop
endlabel func_001002B0
