.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001002C0, 0x10

glabel func_001002C0
    /* 2C0 001002C0 E6FF0324 */  addiu      $v1, $zero, -0x1A
    /* 2C4 001002C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C8 001002C8 0800E003 */  jr         $ra
    /* 2CC 001002CC 00000000 */   nop
endlabel func_001002C0
