.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100210, 0x10

glabel func_00100210
    /* 210 00100210 10000324 */  addiu      $v1, $zero, 0x10
    /* 214 00100214 0C000000 */  syscall    0 /* handwritten instruction */
    /* 218 00100218 0800E003 */  jr         $ra
    /* 21C 0010021C 00000000 */   nop
endlabel func_00100210
