.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001002A0, 0x10

glabel func_001002A0
    /* 2A0 001002A0 FC000324 */  addiu      $v1, $zero, 0xFC
    /* 2A4 001002A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2A8 001002A8 0800E003 */  jr         $ra
    /* 2AC 001002AC 00000000 */   nop
endlabel func_001002A0
