.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100280, 0x10

glabel func_00100280
    /* 280 00100280 16000324 */  addiu      $v1, $zero, 0x16
    /* 284 00100284 0C000000 */  syscall    0 /* handwritten instruction */
    /* 288 00100288 0800E003 */  jr         $ra
    /* 28C 0010028C 00000000 */   nop
endlabel func_00100280
