.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100290, 0x10

glabel func_00100290
    /* 290 00100290 17000324 */  addiu      $v1, $zero, 0x17
    /* 294 00100294 0C000000 */  syscall    0 /* handwritten instruction */
    /* 298 00100298 0800E003 */  jr         $ra
    /* 29C 0010029C 00000000 */   nop
endlabel func_00100290
