.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001002F0, 0x10

glabel func_001002F0
    /* 2F0 001002F0 E3FF0324 */  addiu      $v1, $zero, -0x1D
    /* 2F4 001002F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F8 001002F8 0800E003 */  jr         $ra
    /* 2FC 001002FC 00000000 */   nop
endlabel func_001002F0
