.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100220, 0x10

glabel func_00100220
    /* 220 00100220 11000324 */  addiu      $v1, $zero, 0x11
    /* 224 00100224 0C000000 */  syscall    0 /* handwritten instruction */
    /* 228 00100228 0800E003 */  jr         $ra
    /* 22C 0010022C 00000000 */   nop
endlabel func_00100220
