.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100260, 0x10

glabel func_00100260
    /* 260 00100260 14000324 */  addiu      $v1, $zero, 0x14
    /* 264 00100264 0C000000 */  syscall    0 /* handwritten instruction */
    /* 268 00100268 0800E003 */  jr         $ra
    /* 26C 0010026C 00000000 */   nop
endlabel func_00100260
