.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100250, 0x10

glabel func_00100250
    /* 250 00100250 13000324 */  addiu      $v1, $zero, 0x13
    /* 254 00100254 0C000000 */  syscall    0 /* handwritten instruction */
    /* 258 00100258 0800E003 */  jr         $ra
    /* 25C 0010025C 00000000 */   nop
endlabel func_00100250
