.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001002E0, 0x10

glabel func_001002E0
    /* 2E0 001002E0 E4FF0324 */  addiu      $v1, $zero, -0x1C
    /* 2E4 001002E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E8 001002E8 0800E003 */  jr         $ra
    /* 2EC 001002EC 00000000 */   nop
endlabel func_001002E0
