.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100240, 0x10

glabel func_00100240
    /* 240 00100240 12000324 */  addiu      $v1, $zero, 0x12
    /* 244 00100244 0C000000 */  syscall    0 /* handwritten instruction */
    /* 248 00100248 0800E003 */  jr         $ra
    /* 24C 0010024C 00000000 */   nop
endlabel func_00100240
