.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100230, 0x10

glabel func_00100230
    /* 230 00100230 12000324 */  addiu      $v1, $zero, 0x12
    /* 234 00100234 0C000000 */  syscall    0 /* handwritten instruction */
    /* 238 00100238 0800E003 */  jr         $ra
    /* 23C 0010023C 00000000 */   nop
endlabel func_00100230
