.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100200, 0x10

glabel func_00100200
    /* 200 00100200 10000324 */  addiu      $v1, $zero, 0x10
    /* 204 00100204 0C000000 */  syscall    0 /* handwritten instruction */
    /* 208 00100208 0800E003 */  jr         $ra
    /* 20C 0010020C 00000000 */   nop
endlabel func_00100200
