.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001002D0, 0x10

glabel func_001002D0
    /* 2D0 001002D0 E5FF0324 */  addiu      $v1, $zero, -0x1B
    /* 2D4 001002D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D8 001002D8 0800E003 */  jr         $ra
    /* 2DC 001002DC 00000000 */   nop
endlabel func_001002D0
