.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100270, 0x10

glabel func_00100270
    /* 270 00100270 15000324 */  addiu      $v1, $zero, 0x15
    /* 274 00100274 0C000000 */  syscall    0 /* handwritten instruction */
    /* 278 00100278 0800E003 */  jr         $ra
    /* 27C 0010027C 00000000 */   nop
endlabel func_00100270
