.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100370, 0x10

glabel func_00100370
    /* 370 00100370 25000324 */  addiu      $v1, $zero, 0x25
    /* 374 00100374 0C000000 */  syscall    0 /* handwritten instruction */
    /* 378 00100378 0800E003 */  jr         $ra
    /* 37C 0010037C 00000000 */   nop
endlabel func_00100370
