.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001003B0, 0x10

glabel func_001003B0
    /* 3B0 001003B0 29000324 */  addiu      $v1, $zero, 0x29
    /* 3B4 001003B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3B8 001003B8 0800E003 */  jr         $ra
    /* 3BC 001003BC 00000000 */   nop
endlabel func_001003B0
