.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100380, 0x10

glabel func_00100380
    /* 380 00100380 DAFF0324 */  addiu      $v1, $zero, -0x26
    /* 384 00100384 0C000000 */  syscall    0 /* handwritten instruction */
    /* 388 00100388 0800E003 */  jr         $ra
    /* 38C 0010038C 00000000 */   nop
endlabel func_00100380
