.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100300, 0x10

glabel func_00100300
    /* 300 00100300 02FF0324 */  addiu      $v1, $zero, -0xFE
    /* 304 00100304 0C000000 */  syscall    0 /* handwritten instruction */
    /* 308 00100308 0800E003 */  jr         $ra
    /* 30C 0010030C 00000000 */   nop
endlabel func_00100300
