.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001003A0, 0x10

glabel func_001003A0
    /* 3A0 001003A0 28000324 */  addiu      $v1, $zero, 0x28
    /* 3A4 001003A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3A8 001003A8 0800E003 */  jr         $ra
    /* 3AC 001003AC 00000000 */   nop
endlabel func_001003A0
