.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001003E0, 0x10

glabel func_001003E0
    /* 3E0 001003E0 D4FF0324 */  addiu      $v1, $zero, -0x2C
    /* 3E4 001003E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3E8 001003E8 0800E003 */  jr         $ra
    /* 3EC 001003EC 00000000 */   nop
endlabel func_001003E0
