.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100340, 0x10

glabel func_00100340
    /* 340 00100340 22000324 */  addiu      $v1, $zero, 0x22
    /* 344 00100344 0C000000 */  syscall    0 /* handwritten instruction */
    /* 348 00100348 0800E003 */  jr         $ra
    /* 34C 0010034C 00000000 */   nop
endlabel func_00100340
