.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001003D0, 0x10

glabel func_001003D0
    /* 3D0 001003D0 2B000324 */  addiu      $v1, $zero, 0x2B
    /* 3D4 001003D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3D8 001003D8 0800E003 */  jr         $ra
    /* 3DC 001003DC 00000000 */   nop
endlabel func_001003D0
