.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100330, 0x10

glabel func_00100330
    /* 330 00100330 21000324 */  addiu      $v1, $zero, 0x21
    /* 334 00100334 0C000000 */  syscall    0 /* handwritten instruction */
    /* 338 00100338 0800E003 */  jr         $ra
    /* 33C 0010033C 00000000 */   nop
endlabel func_00100330
