.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100360, 0x10

glabel func_00100360
    /* 360 00100360 24000324 */  addiu      $v1, $zero, 0x24
    /* 364 00100364 0C000000 */  syscall    0 /* handwritten instruction */
    /* 368 00100368 0800E003 */  jr         $ra
    /* 36C 0010036C 00000000 */   nop
endlabel func_00100360
