.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001003F0, 0x10

glabel func_001003F0
    /* 3F0 001003F0 2D000324 */  addiu      $v1, $zero, 0x2D
    /* 3F4 001003F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3F8 001003F8 0800E003 */  jr         $ra
    /* 3FC 001003FC 00000000 */   nop
endlabel func_001003F0
