.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001003C0, 0x10

glabel func_001003C0
    /* 3C0 001003C0 D6FF0324 */  addiu      $v1, $zero, -0x2A
    /* 3C4 001003C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3C8 001003C8 0800E003 */  jr         $ra
    /* 3CC 001003CC 00000000 */   nop
endlabel func_001003C0
