.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100320, 0x10

glabel func_00100320
    /* 320 00100320 20000324 */  addiu      $v1, $zero, 0x20
    /* 324 00100324 0C000000 */  syscall    0 /* handwritten instruction */
    /* 328 00100328 0800E003 */  jr         $ra
    /* 32C 0010032C 00000000 */   nop
endlabel func_00100320
