.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100310, 0x10

glabel func_00100310
    /* 310 00100310 01FF0324 */  addiu      $v1, $zero, -0xFF
    /* 314 00100314 0C000000 */  syscall    0 /* handwritten instruction */
    /* 318 00100318 0800E003 */  jr         $ra
    /* 31C 0010031C 00000000 */   nop
endlabel func_00100310
