.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100350, 0x10

glabel func_00100350
    /* 350 00100350 23000324 */  addiu      $v1, $zero, 0x23
    /* 354 00100354 0C000000 */  syscall    0 /* handwritten instruction */
    /* 358 00100358 0800E003 */  jr         $ra
    /* 35C 0010035C 00000000 */   nop
endlabel func_00100350
