.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100390, 0x10

glabel func_00100390
    /* 390 00100390 27000324 */  addiu      $v1, $zero, 0x27
    /* 394 00100394 0C000000 */  syscall    0 /* handwritten instruction */
    /* 398 00100398 0800E003 */  jr         $ra
    /* 39C 0010039C 00000000 */   nop
endlabel func_00100390
