.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100410, 0x10

glabel func_00100410
    /* 410 00100410 2F000324 */  addiu      $v1, $zero, 0x2F
    /* 414 00100414 0C000000 */  syscall    0 /* handwritten instruction */
    /* 418 00100418 0800E003 */  jr         $ra
    /* 41C 0010041C 00000000 */   nop
endlabel func_00100410
