.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001004E0, 0x10

glabel func_001004E0
    /* 4E0 001004E0 3C000324 */  addiu      $v1, $zero, 0x3C
    /* 4E4 001004E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 4E8 001004E8 0800E003 */  jr         $ra
    /* 4EC 001004EC 00000000 */   nop
endlabel func_001004E0
