.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100400, 0x10

glabel func_00100400
    /* 400 00100400 D2FF0324 */  addiu      $v1, $zero, -0x2E
    /* 404 00100404 0C000000 */  syscall    0 /* handwritten instruction */
    /* 408 00100408 0800E003 */  jr         $ra
    /* 40C 0010040C 00000000 */   nop
endlabel func_00100400
