.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100420, 0x10

glabel func_00100420
    /* 420 00100420 30000324 */  addiu      $v1, $zero, 0x30
    /* 424 00100424 0C000000 */  syscall    0 /* handwritten instruction */
    /* 428 00100428 0800E003 */  jr         $ra
    /* 42C 0010042C 00000000 */   nop
endlabel func_00100420
