.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001004A0, 0x10

glabel func_001004A0
    /* 4A0 001004A0 C8FF0324 */  addiu      $v1, $zero, -0x38
    /* 4A4 001004A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 4A8 001004A8 0800E003 */  jr         $ra
    /* 4AC 001004AC 00000000 */   nop
endlabel func_001004A0
