.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001004B0, 0x10

glabel func_001004B0
    /* 4B0 001004B0 39000324 */  addiu      $v1, $zero, 0x39
    /* 4B4 001004B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 4B8 001004B8 0800E003 */  jr         $ra
    /* 4BC 001004BC 00000000 */   nop
endlabel func_001004B0
