.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100490, 0x10

glabel func_00100490
    /* 490 00100490 37000324 */  addiu      $v1, $zero, 0x37
    /* 494 00100494 0C000000 */  syscall    0 /* handwritten instruction */
    /* 498 00100498 0800E003 */  jr         $ra
    /* 49C 0010049C 00000000 */   nop
endlabel func_00100490
