.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001004D0, 0x10

glabel func_001004D0
    /* 4D0 001004D0 3B000324 */  addiu      $v1, $zero, 0x3B
    /* 4D4 001004D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 4D8 001004D8 0800E003 */  jr         $ra
    /* 4DC 001004DC 00000000 */   nop
endlabel func_001004D0
