.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100440, 0x10

glabel func_00100440
    /* 440 00100440 32000324 */  addiu      $v1, $zero, 0x32
    /* 444 00100444 0C000000 */  syscall    0 /* handwritten instruction */
    /* 448 00100448 0800E003 */  jr         $ra
    /* 44C 0010044C 00000000 */   nop
endlabel func_00100440
