.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100480, 0x10

glabel func_00100480
    /* 480 00100480 CAFF0324 */  addiu      $v1, $zero, -0x36
    /* 484 00100484 0C000000 */  syscall    0 /* handwritten instruction */
    /* 488 00100488 0800E003 */  jr         $ra
    /* 48C 0010048C 00000000 */   nop
endlabel func_00100480
