.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100470, 0x10

glabel func_00100470
    /* 470 00100470 35000324 */  addiu      $v1, $zero, 0x35
    /* 474 00100474 0C000000 */  syscall    0 /* handwritten instruction */
    /* 478 00100478 0800E003 */  jr         $ra
    /* 47C 0010047C 00000000 */   nop
endlabel func_00100470
