.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100450, 0x10

glabel func_00100450
    /* 450 00100450 33000324 */  addiu      $v1, $zero, 0x33
    /* 454 00100454 0C000000 */  syscall    0 /* handwritten instruction */
    /* 458 00100458 0800E003 */  jr         $ra
    /* 45C 0010045C 00000000 */   nop
endlabel func_00100450
