.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001004F0, 0x10

glabel func_001004F0
    /* 4F0 001004F0 3D000324 */  addiu      $v1, $zero, 0x3D
    /* 4F4 001004F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 4F8 001004F8 0800E003 */  jr         $ra
    /* 4FC 001004FC 00000000 */   nop
endlabel func_001004F0
