.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100460, 0x10

glabel func_00100460
    /* 460 00100460 CCFF0324 */  addiu      $v1, $zero, -0x34
    /* 464 00100464 0C000000 */  syscall    0 /* handwritten instruction */
    /* 468 00100468 0800E003 */  jr         $ra
    /* 46C 0010046C 00000000 */   nop
endlabel func_00100460
