.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100430, 0x10

glabel func_00100430
    /* 430 00100430 CFFF0324 */  addiu      $v1, $zero, -0x31
    /* 434 00100434 0C000000 */  syscall    0 /* handwritten instruction */
    /* 438 00100438 0800E003 */  jr         $ra
    /* 43C 0010043C 00000000 */   nop
endlabel func_00100430
