.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001004C0, 0x10

glabel func_001004C0
    /* 4C0 001004C0 C6FF0324 */  addiu      $v1, $zero, -0x3A
    /* 4C4 001004C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 4C8 001004C8 0800E003 */  jr         $ra
    /* 4CC 001004CC 00000000 */   nop
endlabel func_001004C0
