.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100540, 0x10

glabel func_00100540
    /* 540 00100540 42000324 */  addiu      $v1, $zero, 0x42
    /* 544 00100544 0C000000 */  syscall    0 /* handwritten instruction */
    /* 548 00100548 0800E003 */  jr         $ra
    /* 54C 0010054C 00000000 */   nop
endlabel func_00100540
