.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100580, 0x10

glabel func_00100580
    /* 580 00100580 BAFF0324 */  addiu      $v1, $zero, -0x46
    /* 584 00100584 0C000000 */  syscall    0 /* handwritten instruction */
    /* 588 00100588 0800E003 */  jr         $ra
    /* 58C 0010058C 00000000 */   nop
endlabel func_00100580
