.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100510, 0x10

glabel func_00100510
    /* 510 00100510 3F000324 */  addiu      $v1, $zero, 0x3F
    /* 514 00100514 0C000000 */  syscall    0 /* handwritten instruction */
    /* 518 00100518 0800E003 */  jr         $ra
    /* 51C 0010051C 00000000 */   nop
endlabel func_00100510
