.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100570, 0x10

glabel func_00100570
    /* 570 00100570 45000324 */  addiu      $v1, $zero, 0x45
    /* 574 00100574 0C000000 */  syscall    0 /* handwritten instruction */
    /* 578 00100578 0800E003 */  jr         $ra
    /* 57C 0010057C 00000000 */   nop
endlabel func_00100570
