.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100500, 0x10

glabel func_00100500
    /* 500 00100500 3E000324 */  addiu      $v1, $zero, 0x3E
    /* 504 00100504 0C000000 */  syscall    0 /* handwritten instruction */
    /* 508 00100508 0800E003 */  jr         $ra
    /* 50C 0010050C 00000000 */   nop
endlabel func_00100500
