.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001005A0, 0x10

glabel func_001005A0
    /* 5A0 001005A0 B8FF0324 */  addiu      $v1, $zero, -0x48
    /* 5A4 001005A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 5A8 001005A8 0800E003 */  jr         $ra
    /* 5AC 001005AC 00000000 */   nop
endlabel func_001005A0
