.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001005D0, 0x10

glabel func_001005D0
    /* 5D0 001005D0 4B000324 */  addiu      $v1, $zero, 0x4B
    /* 5D4 001005D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 5D8 001005D8 0800E003 */  jr         $ra
    /* 5DC 001005DC 00000000 */   nop
endlabel func_001005D0
