.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001005C0, 0x10

glabel func_001005C0
    /* 5C0 001005C0 4A000324 */  addiu      $v1, $zero, 0x4A
    /* 5C4 001005C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 5C8 001005C8 0800E003 */  jr         $ra
    /* 5CC 001005CC 00000000 */   nop
endlabel func_001005C0
