.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001005E0, 0x10

glabel func_001005E0
    /* 5E0 001005E0 4C000324 */  addiu      $v1, $zero, 0x4C
    /* 5E4 001005E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 5E8 001005E8 0800E003 */  jr         $ra
    /* 5EC 001005EC 00000000 */   nop
endlabel func_001005E0
