.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100530, 0x10

glabel func_00100530
    /* 530 00100530 41000324 */  addiu      $v1, $zero, 0x41
    /* 534 00100534 0C000000 */  syscall    0 /* handwritten instruction */
    /* 538 00100538 0800E003 */  jr         $ra
    /* 53C 0010053C 00000000 */   nop
endlabel func_00100530
