.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100520, 0x10

glabel func_00100520
    /* 520 00100520 40000324 */  addiu      $v1, $zero, 0x40
    /* 524 00100524 0C000000 */  syscall    0 /* handwritten instruction */
    /* 528 00100528 0800E003 */  jr         $ra
    /* 52C 0010052C 00000000 */   nop
endlabel func_00100520
