.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100550, 0x10

glabel func_00100550
    /* 550 00100550 BDFF0324 */  addiu      $v1, $zero, -0x43
    /* 554 00100554 0C000000 */  syscall    0 /* handwritten instruction */
    /* 558 00100558 0800E003 */  jr         $ra
    /* 55C 0010055C 00000000 */   nop
endlabel func_00100550
