.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100590, 0x10

glabel func_00100590
    /* 590 00100590 47000324 */  addiu      $v1, $zero, 0x47
    /* 594 00100594 0C000000 */  syscall    0 /* handwritten instruction */
    /* 598 00100598 0800E003 */  jr         $ra
    /* 59C 0010059C 00000000 */   nop
endlabel func_00100590
