.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001005F0, 0x10

glabel func_001005F0
    /* 5F0 001005F0 4D000324 */  addiu      $v1, $zero, 0x4D
    /* 5F4 001005F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 5F8 001005F8 0800E003 */  jr         $ra
    /* 5FC 001005FC 00000000 */   nop
endlabel func_001005F0
