.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001005B0, 0x10

glabel func_001005B0
    /* 5B0 001005B0 49000324 */  addiu      $v1, $zero, 0x49
    /* 5B4 001005B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 5B8 001005B8 0800E003 */  jr         $ra
    /* 5BC 001005BC 00000000 */   nop
endlabel func_001005B0
