.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100560, 0x10

glabel func_00100560
    /* 560 00100560 44000324 */  addiu      $v1, $zero, 0x44
    /* 564 00100564 0C000000 */  syscall    0 /* handwritten instruction */
    /* 568 00100568 0800E003 */  jr         $ra
    /* 56C 0010056C 00000000 */   nop
endlabel func_00100560
