.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001006D0, 0x10

glabel func_001006D0
    /* 6D0 001006D0 5B000324 */  addiu      $v1, $zero, 0x5B
    /* 6D4 001006D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 6D8 001006D8 0800E003 */  jr         $ra
    /* 6DC 001006DC 00000000 */   nop
endlabel func_001006D0
