.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100690, 0x10

glabel func_00100690
    /* 690 00100690 57000324 */  addiu      $v1, $zero, 0x57
    /* 694 00100694 0C000000 */  syscall    0 /* handwritten instruction */
    /* 698 00100698 0800E003 */  jr         $ra
    /* 69C 0010069C 00000000 */   nop
endlabel func_00100690
