.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001006A0, 0x10

glabel func_001006A0
    /* 6A0 001006A0 A8FF0324 */  addiu      $v1, $zero, -0x58
    /* 6A4 001006A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 6A8 001006A8 0800E003 */  jr         $ra
    /* 6AC 001006AC 00000000 */   nop
endlabel func_001006A0
