.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001006F0, 0x10

glabel func_001006F0
    /* 6F0 001006F0 A4FF0324 */  addiu      $v1, $zero, -0x5C
    /* 6F4 001006F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 6F8 001006F8 0800E003 */  jr         $ra
    /* 6FC 001006FC 00000000 */   nop
endlabel func_001006F0
