.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100680, 0x10

glabel func_00100680
    /* 680 00100680 56000324 */  addiu      $v1, $zero, 0x56
    /* 684 00100684 0C000000 */  syscall    0 /* handwritten instruction */
    /* 688 00100688 0800E003 */  jr         $ra
    /* 68C 0010068C 00000000 */   nop
endlabel func_00100680
