.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100620, 0x10

glabel func_00100620
    /* 620 00100620 50000324 */  addiu      $v1, $zero, 0x50
    /* 624 00100624 0C000000 */  syscall    0 /* handwritten instruction */
    /* 628 00100628 0800E003 */  jr         $ra
    /* 62C 0010062C 00000000 */   nop
endlabel func_00100620
