.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100640, 0x10

glabel func_00100640
    /* 640 00100640 52000324 */  addiu      $v1, $zero, 0x52
    /* 644 00100644 0C000000 */  syscall    0 /* handwritten instruction */
    /* 648 00100648 0800E003 */  jr         $ra
    /* 64C 0010064C 00000000 */   nop
endlabel func_00100640
