.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100660, 0x10

glabel func_00100660
    /* 660 00100660 54000324 */  addiu      $v1, $zero, 0x54
    /* 664 00100664 0C000000 */  syscall    0 /* handwritten instruction */
    /* 668 00100668 0800E003 */  jr         $ra
    /* 66C 0010066C 00000000 */   nop
endlabel func_00100660
