.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100600, 0x10

glabel func_00100600
    /* 600 00100600 4E000324 */  addiu      $v1, $zero, 0x4E
    /* 604 00100604 0C000000 */  syscall    0 /* handwritten instruction */
    /* 608 00100608 0800E003 */  jr         $ra
    /* 60C 0010060C 00000000 */   nop
endlabel func_00100600
