.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100630, 0x10

glabel func_00100630
    /* 630 00100630 51000324 */  addiu      $v1, $zero, 0x51
    /* 634 00100634 0C000000 */  syscall    0 /* handwritten instruction */
    /* 638 00100638 0800E003 */  jr         $ra
    /* 63C 0010063C 00000000 */   nop
endlabel func_00100630
