.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100670, 0x10

glabel func_00100670
    /* 670 00100670 ABFF0324 */  addiu      $v1, $zero, -0x55
    /* 674 00100674 0C000000 */  syscall    0 /* handwritten instruction */
    /* 678 00100678 0800E003 */  jr         $ra
    /* 67C 0010067C 00000000 */   nop
endlabel func_00100670
