.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100610, 0x10

glabel func_00100610
    /* 610 00100610 4F000324 */  addiu      $v1, $zero, 0x4F
    /* 614 00100614 0C000000 */  syscall    0 /* handwritten instruction */
    /* 618 00100618 0800E003 */  jr         $ra
    /* 61C 0010061C 00000000 */   nop
endlabel func_00100610
