.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001006C0, 0x10

glabel func_001006C0
    /* 6C0 001006C0 A6FF0324 */  addiu      $v1, $zero, -0x5A
    /* 6C4 001006C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 6C8 001006C8 0800E003 */  jr         $ra
    /* 6CC 001006CC 00000000 */   nop
endlabel func_001006C0
