.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001006E0, 0x10

glabel func_001006E0
    /* 6E0 001006E0 5C000324 */  addiu      $v1, $zero, 0x5C
    /* 6E4 001006E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 6E8 001006E8 0800E003 */  jr         $ra
    /* 6EC 001006EC 00000000 */   nop
endlabel func_001006E0
