.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001006B0, 0x10

glabel func_001006B0
    /* 6B0 001006B0 59000324 */  addiu      $v1, $zero, 0x59
    /* 6B4 001006B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 6B8 001006B8 0800E003 */  jr         $ra
    /* 6BC 001006BC 00000000 */   nop
endlabel func_001006B0
