.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100730, 0x10

glabel func_00100730
    /* 730 00100730 A2FF0324 */  addiu      $v1, $zero, -0x5E
    /* 734 00100734 0C000000 */  syscall    0 /* handwritten instruction */
    /* 738 00100738 0800E003 */  jr         $ra
    /* 73C 0010073C 00000000 */   nop
endlabel func_00100730
