.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100710, 0x10

glabel func_00100710
    /* 710 00100710 A3FF0324 */  addiu      $v1, $zero, -0x5D
    /* 714 00100714 0C000000 */  syscall    0 /* handwritten instruction */
    /* 718 00100718 0800E003 */  jr         $ra
    /* 71C 0010071C 00000000 */   nop
endlabel func_00100710
