.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001007F0, 0x10

glabel func_001007F0
    /* 7F0 001007F0 6B000324 */  addiu      $v1, $zero, 0x6B
    /* 7F4 001007F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 7F8 001007F8 0800E003 */  jr         $ra
    /* 7FC 001007FC 00000000 */   nop
endlabel func_001007F0
