.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100740, 0x10

glabel func_00100740
    /* 740 00100740 5F000324 */  addiu      $v1, $zero, 0x5F
    /* 744 00100744 0C000000 */  syscall    0 /* handwritten instruction */
    /* 748 00100748 0800E003 */  jr         $ra
    /* 74C 0010074C 00000000 */   nop
endlabel func_00100740
