.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100750, 0x10

glabel func_00100750
    /* 750 00100750 A1FF0324 */  addiu      $v1, $zero, -0x5F
    /* 754 00100754 0C000000 */  syscall    0 /* handwritten instruction */
    /* 758 00100758 0800E003 */  jr         $ra
    /* 75C 0010075C 00000000 */   nop
endlabel func_00100750
