.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100720, 0x10

glabel func_00100720
    /* 720 00100720 5E000324 */  addiu      $v1, $zero, 0x5E
    /* 724 00100724 0C000000 */  syscall    0 /* handwritten instruction */
    /* 728 00100728 0800E003 */  jr         $ra
    /* 72C 0010072C 00000000 */   nop
endlabel func_00100720
