.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001007C0, 0x10

glabel func_001007C0
    /* 7C0 001007C0 99FF0324 */  addiu      $v1, $zero, -0x67
    /* 7C4 001007C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 7C8 001007C8 0800E003 */  jr         $ra
    /* 7CC 001007CC 00000000 */   nop
endlabel func_001007C0
