.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001007D0, 0x10

glabel func_001007D0
    /* 7D0 001007D0 98FF0324 */  addiu      $v1, $zero, -0x68
    /* 7D4 001007D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 7D8 001007D8 0800E003 */  jr         $ra
    /* 7DC 001007DC 00000000 */   nop
endlabel func_001007D0
