.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100790, 0x10

glabel func_00100790
    /* 790 00100790 63000324 */  addiu      $v1, $zero, 0x63
    /* 794 00100794 0C000000 */  syscall    0 /* handwritten instruction */
    /* 798 00100798 0800E003 */  jr         $ra
    /* 79C 0010079C 00000000 */   nop
endlabel func_00100790
