.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001007B0, 0x10

glabel func_001007B0
    /* 7B0 001007B0 66000324 */  addiu      $v1, $zero, 0x66
    /* 7B4 001007B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 7B8 001007B8 0800E003 */  jr         $ra
    /* 7BC 001007BC 00000000 */   nop
endlabel func_001007B0
