.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100770, 0x10

glabel func_00100770
    /* 770 00100770 61000324 */  addiu      $v1, $zero, 0x61
    /* 774 00100774 0C000000 */  syscall    0 /* handwritten instruction */
    /* 778 00100778 0800E003 */  jr         $ra
    /* 77C 0010077C 00000000 */   nop
endlabel func_00100770
