.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100700, 0x10

glabel func_00100700
    /* 700 00100700 5D000324 */  addiu      $v1, $zero, 0x5D
    /* 704 00100704 0C000000 */  syscall    0 /* handwritten instruction */
    /* 708 00100708 0800E003 */  jr         $ra
    /* 70C 0010070C 00000000 */   nop
endlabel func_00100700
