.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100760, 0x10

glabel func_00100760
    /* 760 00100760 60000324 */  addiu      $v1, $zero, 0x60
    /* 764 00100764 0C000000 */  syscall    0 /* handwritten instruction */
    /* 768 00100768 0800E003 */  jr         $ra
    /* 76C 0010076C 00000000 */   nop
endlabel func_00100760
