.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001007E0, 0x10

glabel func_001007E0
    /* 7E0 001007E0 96FF0324 */  addiu      $v1, $zero, -0x6A
    /* 7E4 001007E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 7E8 001007E8 0800E003 */  jr         $ra
    /* 7EC 001007EC 00000000 */   nop
endlabel func_001007E0
