.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100780, 0x10

glabel func_00100780
    /* 780 00100780 62000324 */  addiu      $v1, $zero, 0x62
    /* 784 00100784 0C000000 */  syscall    0 /* handwritten instruction */
    /* 788 00100788 0800E003 */  jr         $ra
    /* 78C 0010078C 00000000 */   nop
endlabel func_00100780
