.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001007A0, 0x10

glabel func_001007A0
    /* 7A0 001007A0 64000324 */  addiu      $v1, $zero, 0x64
    /* 7A4 001007A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 7A8 001007A8 0800E003 */  jr         $ra
    /* 7AC 001007AC 00000000 */   nop
endlabel func_001007A0
