.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100840, 0x10

glabel func_00100840
    /* 840 00100840 70000324 */  addiu      $v1, $zero, 0x70
    /* 844 00100844 0C000000 */  syscall    0 /* handwritten instruction */
    /* 848 00100848 0800E003 */  jr         $ra
    /* 84C 0010084C 00000000 */   nop
endlabel func_00100840
