.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100880, 0x10

glabel func_00100880
    /* 880 00100880 72000324 */  addiu      $v1, $zero, 0x72
    /* 884 00100884 0C000000 */  syscall    0 /* handwritten instruction */
    /* 888 00100888 0800E003 */  jr         $ra
    /* 88C 0010088C 00000000 */   nop
endlabel func_00100880
