.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100860, 0x10

glabel func_00100860
    /* 860 00100860 71000324 */  addiu      $v1, $zero, 0x71
    /* 864 00100864 0C000000 */  syscall    0 /* handwritten instruction */
    /* 868 00100868 0800E003 */  jr         $ra
    /* 86C 0010086C 00000000 */   nop
endlabel func_00100860
