.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100850, 0x10

glabel func_00100850
    /* 850 00100850 90FF0324 */  addiu      $v1, $zero, -0x70
    /* 854 00100854 0C000000 */  syscall    0 /* handwritten instruction */
    /* 858 00100858 0800E003 */  jr         $ra
    /* 85C 0010085C 00000000 */   nop
endlabel func_00100850
