.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001008D0, 0x10

glabel func_001008D0
    /* 8D0 001008D0 8AFF0324 */  addiu      $v1, $zero, -0x76
    /* 8D4 001008D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 8D8 001008D8 0800E003 */  jr         $ra
    /* 8DC 001008DC 00000000 */   nop
endlabel func_001008D0
