.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100870, 0x10

glabel func_00100870
    /* 870 00100870 8FFF0324 */  addiu      $v1, $zero, -0x71
    /* 874 00100874 0C000000 */  syscall    0 /* handwritten instruction */
    /* 878 00100878 0800E003 */  jr         $ra
    /* 87C 0010087C 00000000 */   nop
endlabel func_00100870
