.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001008C0, 0x10

glabel func_001008C0
    /* 8C0 001008C0 76000324 */  addiu      $v1, $zero, 0x76
    /* 8C4 001008C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 8C8 001008C8 0800E003 */  jr         $ra
    /* 8CC 001008CC 00000000 */   nop
endlabel func_001008C0
