.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001008B0, 0x10

glabel func_001008B0
    /* 8B0 001008B0 75000324 */  addiu      $v1, $zero, 0x75
    /* 8B4 001008B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 8B8 001008B8 0800E003 */  jr         $ra
    /* 8BC 001008BC 00000000 */   nop
endlabel func_001008B0
