.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001008A0, 0x10

glabel func_001008A0
    /* 8A0 001008A0 74000324 */  addiu      $v1, $zero, 0x74
    /* 8A4 001008A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 8A8 001008A8 0800E003 */  jr         $ra
    /* 8AC 001008AC 00000000 */   nop
endlabel func_001008A0
