.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100810, 0x10

glabel func_00100810
    /* 810 00100810 6D000324 */  addiu      $v1, $zero, 0x6D
    /* 814 00100814 0C000000 */  syscall    0 /* handwritten instruction */
    /* 818 00100818 0800E003 */  jr         $ra
    /* 81C 0010081C 00000000 */   nop
endlabel func_00100810
