.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001008F0, 0x10

glabel func_001008F0
    /* 8F0 001008F0 89FF0324 */  addiu      $v1, $zero, -0x77
    /* 8F4 001008F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 8F8 001008F8 0800E003 */  jr         $ra
    /* 8FC 001008FC 00000000 */   nop
endlabel func_001008F0
