.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100890, 0x10

glabel func_00100890
    /* 890 00100890 73000324 */  addiu      $v1, $zero, 0x73
    /* 894 00100894 0C000000 */  syscall    0 /* handwritten instruction */
    /* 898 00100898 0800E003 */  jr         $ra
    /* 89C 0010089C 00000000 */   nop
endlabel func_00100890
