.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100800, 0x10

glabel func_00100800
    /* 800 00100800 6C000324 */  addiu      $v1, $zero, 0x6C
    /* 804 00100804 0C000000 */  syscall    0 /* handwritten instruction */
    /* 808 00100808 0800E003 */  jr         $ra
    /* 80C 0010080C 00000000 */   nop
endlabel func_00100800
