.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100820, 0x10

glabel func_00100820
    /* 820 00100820 6E000324 */  addiu      $v1, $zero, 0x6E
    /* 824 00100824 0C000000 */  syscall    0 /* handwritten instruction */
    /* 828 00100828 0800E003 */  jr         $ra
    /* 82C 0010082C 00000000 */   nop
endlabel func_00100820
