.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100830, 0x10

glabel func_00100830
    /* 830 00100830 6F000324 */  addiu      $v1, $zero, 0x6F
    /* 834 00100834 0C000000 */  syscall    0 /* handwritten instruction */
    /* 838 00100838 0800E003 */  jr         $ra
    /* 83C 0010083C 00000000 */   nop
endlabel func_00100830
