.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_001008E0, 0x10

glabel func_001008E0
    /* 8E0 001008E0 77000324 */  addiu      $v1, $zero, 0x77
    /* 8E4 001008E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 8E8 001008E8 0800E003 */  jr         $ra
    /* 8EC 001008EC 00000000 */   nop
endlabel func_001008E0
