.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100950, 0x10

glabel func_00100950
    /* 950 00100950 7C000324 */  addiu      $v1, $zero, 0x7C
    /* 954 00100954 0C000000 */  syscall    0 /* handwritten instruction */
    /* 958 00100958 0800E003 */  jr         $ra
    /* 95C 0010095C 00000000 */   nop
endlabel func_00100950
