.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100980, 0x10

glabel func_00100980
    /* 980 00100980 7F000324 */  addiu      $v1, $zero, 0x7F
    /* 984 00100984 0C000000 */  syscall    0 /* handwritten instruction */
    /* 988 00100988 0800E003 */  jr         $ra
    /* 98C 0010098C 00000000 */   nop
endlabel func_00100980
