.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100910, 0x10

glabel func_00100910
    /* 910 00100910 88FF0324 */  addiu      $v1, $zero, -0x78
    /* 914 00100914 0C000000 */  syscall    0 /* handwritten instruction */
    /* 918 00100918 0800E003 */  jr         $ra
    /* 91C 0010091C 00000000 */   nop
endlabel func_00100910
