.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100930, 0x10

glabel func_00100930
    /* 930 00100930 7A000324 */  addiu      $v1, $zero, 0x7A
    /* 934 00100934 0C000000 */  syscall    0 /* handwritten instruction */
    /* 938 00100938 0800E003 */  jr         $ra
    /* 93C 0010093C 00000000 */   nop
endlabel func_00100930
