.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100960, 0x10

glabel func_00100960
    /* 960 00100960 7D000324 */  addiu      $v1, $zero, 0x7D
    /* 964 00100964 0C000000 */  syscall    0 /* handwritten instruction */
    /* 968 00100968 0800E003 */  jr         $ra
    /* 96C 0010096C 00000000 */   nop
endlabel func_00100960
