.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100970, 0x10

glabel func_00100970
    /* 970 00100970 7E000324 */  addiu      $v1, $zero, 0x7E
    /* 974 00100974 0C000000 */  syscall    0 /* handwritten instruction */
    /* 978 00100978 0800E003 */  jr         $ra
    /* 97C 0010097C 00000000 */   nop
endlabel func_00100970
