.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100900, 0x10

glabel func_00100900
    /* 900 00100900 78000324 */  addiu      $v1, $zero, 0x78
    /* 904 00100904 0C000000 */  syscall    0 /* handwritten instruction */
    /* 908 00100908 0800E003 */  jr         $ra
    /* 90C 0010090C 00000000 */   nop
endlabel func_00100900
