.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100990, 0x10

glabel func_00100990
    /* 990 00100990 74000324 */  addiu      $v1, $zero, 0x74
    /* 994 00100994 0C000000 */  syscall    0 /* handwritten instruction */
    /* 998 00100998 0800E003 */  jr         $ra
    /* 99C 0010099C 00000000 */   nop
endlabel func_00100990
