.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100920, 0x10

glabel func_00100920
    /* 920 00100920 79000324 */  addiu      $v1, $zero, 0x79
    /* 924 00100924 0C000000 */  syscall    0 /* handwritten instruction */
    /* 928 00100928 0800E003 */  jr         $ra
    /* 92C 0010092C 00000000 */   nop
endlabel func_00100920
