.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100C28, 0x10

glabel func_00100C28
    /* C28 00100C28 74000324 */  addiu      $v1, $zero, 0x74
    /* C2C 00100C2C 0C000000 */  syscall    0 /* handwritten instruction */
    /* C30 00100C30 0800E003 */  jr         $ra
    /* C34 00100C34 00000000 */   nop
endlabel func_00100C28
