.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100C38, 0x10

glabel func_00100C38
    /* C38 00100C38 5A000324 */  addiu      $v1, $zero, 0x5A
    /* C3C 00100C3C 0C000000 */  syscall    0 /* handwritten instruction */
    /* C40 00100C40 0800E003 */  jr         $ra
    /* C44 00100C44 00000000 */   nop
endlabel func_00100C38
