.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00100C80, 0x10

glabel func_00100C80
    /* C80 00100C80 5B000324 */  addiu      $v1, $zero, 0x5B
    /* C84 00100C84 0C000000 */  syscall    0 /* handwritten instruction */
    /* C88 00100C88 0800E003 */  jr         $ra
    /* C8C 00100C8C 00000000 */   nop
endlabel func_00100C80
