.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function — COP0 status read + DI loop + return prev EIE state. */
nonmatching func_00101A40, 0x48

glabel func_00101A40
    /* 1A40 00101A40 00600340 */  mfc0       $v1, $12 /* handwritten instruction */
    /* 1A44 00101A44 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 1A48 00101A48 24186200 */  and        $v1, $v1, $v0
    /* 1A4C 00101A4C 0B006010 */  beqz       $v1, .L00101A7C
    /* 1A50 00101A50 2B200300 */   sltu      $a0, $zero, $v1
    /* 1A54 00101A54 00000000 */  nop
.align 2
  .L00101A58:
    /* 1A58 00101A58 39000042 */  di /* handwritten instruction */
    /* 1A5C 00101A5C 0F040000 */  sync.p
    /* 1A60 00101A60 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 1A64 00101A64 0100033C */  lui        $v1, (0x10000 >> 16)
    /* 1A68 00101A68 24104300 */  and        $v0, $v0, $v1
    /* 1A6C 00101A6C FAFF4014 */  bnez       $v0, .L00101A58
    /* 1A70 00101A70 00000000 */   nop
    /* 1A74 00101A74 0800E003 */  jr         $ra
    /* 1A78 00101A78 2D108000 */   daddu     $v0, $a0, $zero
.align 2
  .L00101A7C:
    /* 1A7C 00101A7C 2D200000 */  daddu      $a0, $zero, $zero
    /* 1A80 00101A80 0800E003 */  jr         $ra
    /* 1A84 00101A84 2D108000 */   daddu     $v0, $a0, $zero
endlabel func_00101A40
