.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00101B0C, 0x4

glabel func_00101B0C
    /* 1B0C 00101B0C 00000000 */  nop
endlabel func_00101B0C
