.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00105F90, 0x18

glabel func_00105F90
    /* 5F90 00105F90 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 5F94 00105F94 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 5F98 00105F98 2C21C54B */  vsub.xyz   $vf4, $vf4, $vf5
    /* 5F9C 00105F9C 000084F8 */  sqc2       $vf4, 0x0($a0)
    /* 5FA0 00105FA0 0800E003 */  jr         $ra
    /* 5FA4 00105FA4 00000000 */   nop
endlabel func_00105F90
