.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00105FE0, 0x20

glabel func_00105FE0
    /* 5FE0 00105FE0 00600844 */  mfc1       $t0, $f12
    /* 5FE4 00105FE4 0020A848 */  qmtc2.ni   $t0, $vf4
    /* 5FE8 00105FE8 BD03044A */  .word      0x4A0403BD                    # vsqrt      $Q, $vf4x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 5FEC 00105FEC BF03004A */  vwaitq
    /* 5FF0 00105FF0 00B04248 */  cfc2.ni    $v0, $vi22
    /* 5FF4 00105FF4 00008244 */  mtc1       $v0, $f0
    /* 5FF8 00105FF8 0800E003 */  jr         $ra
    /* 5FFC 00105FFC 00000000 */   nop
endlabel func_00105FE0
