.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00105F20, 0x28

glabel func_00105F20
    /* 5F20 00105F20 0000A678 */  lq         $a2, 0x0($a1)
    /* 5F24 00105F24 0000867C */  sq         $a2, 0x0($a0)
    /* 5F28 00105F28 1000A678 */  lq         $a2, 0x10($a1)
    /* 5F2C 00105F2C 1000867C */  sq         $a2, 0x10($a0)
    /* 5F30 00105F30 2000A678 */  lq         $a2, 0x20($a1)
    /* 5F34 00105F34 2000867C */  sq         $a2, 0x20($a0)
    /* 5F38 00105F38 3000A678 */  lq         $a2, 0x30($a1)
    /* 5F3C 00105F3C 3000867C */  sq         $a2, 0x30($a0)
    /* 5F40 00105F40 0800E003 */  jr         $ra
    /* 5F44 00105F44 00000000 */   nop
endlabel func_00105F20
