.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00105F78, 0x18

glabel func_00105F78
    /* 5F78 00105F78 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 5F7C 00105F7C 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 5F80 00105F80 2821C54B */  vadd.xyz   $vf4, $vf4, $vf5
    /* 5F84 00105F84 000084F8 */  sqc2       $vf4, 0x0($a0)
    /* 5F88 00105F88 0800E003 */  jr         $ra
    /* 5F8C 00105F8C 00000000 */   nop
endlabel func_00105F78
