.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00106000, 0x28

glabel func_00106000
    /* 6000 00106000 000084D8 */  lqc2       $vf4, 0x0($a0)
    /* 6004 00106004 2A21C44B */  vmul.xyz   $vf4, $vf4, $vf4
    /* 6008 00106008 0121044B */  vaddy.x    $vf4, $vf4, $vf4y
    /* 600C 0010600C 0221044B */  vaddz.x    $vf4, $vf4, $vf4z
    /* 6010 00106010 BD03044A */  .word      0x4A0403BD                    # vsqrt      $Q, $vf4x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 6014 00106014 BF03004A */  vwaitq
    /* 6018 00106018 00B04248 */  cfc2.ni    $v0, $vi22
    /* 601C 0010601C 00008244 */  mtc1       $v0, $f0
    /* 6020 00106020 0800E003 */  jr         $ra
    /* 6024 00106024 00000000 */   nop
endlabel func_00106000
