.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00106028, 0x20

glabel func_00106028
    /* 6028 00106028 000083D8 */  lqc2       $vf3, 0x0($a0)
    /* 602C 0010602C EA18C34B */  vmul.xyz   $vf3, $vf3, $vf3
    /* 6030 00106030 C118034B */  vaddy.x    $vf3, $vf3, $vf3y
    /* 6034 00106034 C218034B */  vaddz.x    $vf3, $vf3, $vf3z
    /* 6038 00106038 00182248 */  qmfc2.ni   $v0, $vf3
    /* 603C 0010603C 00008244 */  mtc1       $v0, $f0
    /* 6040 00106040 0800E003 */  jr         $ra
    /* 6044 00106044 00000000 */   nop
endlabel func_00106028
