.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00106D64, 0x4

glabel func_00106D64
    /* 6D64 00106D64 00000000 */  nop
endlabel func_00106D64
