.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00106DEC, 0x4

glabel func_00106DEC
    /* 6DEC 00106DEC 00000000 */  nop
endlabel func_00106DEC
