.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00106DA4, 0x4

glabel func_00106DA4
    /* 6DA4 00106DA4 00000000 */  nop
endlabel func_00106DA4
