.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_0010DDB8, 0x3C

glabel func_0010DDB8
    /* DDB8 0010DDB8 0000ABD8 */  lqc2       $vf11, 0x0($a1)
    /* DDBC 0010DDBC 0000CCD8 */  lqc2       $vf12, 0x0($a2)
    /* DDC0 0010DDC0 6A5BEC4B */  vmul.xyzw  $vf13, $vf11, $vf12
    /* DDC4 0010DDC4 416B0D4B */  vaddy.x    $vf13, $vf13, $vf13y
    /* DDC8 0010DDC8 426B0D4B */  vaddz.x    $vf13, $vf13, $vf13z
    /* DDCC 0010DDCC 446B2D4A */  vsubx.w    $vf13, $vf13, $vf13x
    /* DDD0 0010DDD0 9B63CB4B */  vmulw.xyz  $vf14, $vf12, $vf11w
    /* DDD4 0010DDD4 DB5BCC4B */  vmulw.xyz  $vf15, $vf11, $vf12w
    /* DDD8 0010DDD8 FE62CB4B */  vopmula.xyz $ACC, $vf12, $vf11
    /* DDDC 0010DDDC 2E5CCC4B */  vopmsub.xyz $vf16, $vf11, $vf12
    /* DDE0 0010DDE0 6873CF4B */  vadd.xyz   $vf13, $vf14, $vf15
    /* DDE4 0010DDE4 686BD04B */  vadd.xyz   $vf13, $vf13, $vf16
    /* DDE8 0010DDE8 00008DF8 */  sqc2       $vf13, 0x0($a0)
    /* DDEC 0010DDEC 0800E003 */  jr         $ra
    /* DDF0 0010DDF0 00000000 */   nop
endlabel func_0010DDB8
