.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_0010E928, 0x28

glabel func_0010E928
    /* E928 0010E928 00008ED8 */  lqc2       $vf14, 0x0($a0)
    /* E92C 0010E92C 0000AFD8 */  lqc2       $vf15, 0x0($a1)
    /* E930 0010E930 EA73EF4B */  vmul.xyzw  $vf15, $vf14, $vf15
    /* E934 0010E934 C17B0F4B */  vaddy.x    $vf15, $vf15, $vf15y
    /* E938 0010E938 C27B0F4B */  vaddz.x    $vf15, $vf15, $vf15z
    /* E93C 0010E93C C37B0F4B */  vaddw.x    $vf15, $vf15, $vf15w
    /* E940 0010E940 00782248 */  qmfc2.ni   $v0, $vf15
    /* E944 0010E944 00008244 */  mtc1       $v0, $f0
    /* E948 0010E948 0800E003 */  jr         $ra
    /* E94C 0010E94C 00000000 */   nop
endlabel func_0010E928
