.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0010EC4C, 0x4

glabel func_0010EC4C
    /* EC4C 0010EC4C 00000000 */  nop
endlabel func_0010EC4C
