.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001118E4, 0x4

glabel func_001118E4
    /* 118E4 001118E4 00000000 */  nop
endlabel func_001118E4
