.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00114FC4, 0x4

glabel func_00114FC4
    /* 14FC4 00114FC4 00000000 */  nop
endlabel func_00114FC4
