.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117C98, 0x18

glabel func_00117C98
    /* 17C98 00117C98 7E7BE74B */  vlqd.xyzw  $vf7, (--$vi15)
    /* 17C9C 00117C9C 7E7BE64B */  vlqd.xyzw  $vf6, (--$vi15)
    /* 17CA0 00117CA0 7E7BE54B */  vlqd.xyzw  $vf5, (--$vi15)
    /* 17CA4 00117CA4 7E7BE44B */  vlqd.xyzw  $vf4, (--$vi15)
    /* 17CA8 00117CA8 0800E003 */  jr         $ra
    /* 17CAC 00117CAC 00000000 */   nop
endlabel func_00117C98
