.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117C80, 0x18

glabel func_00117C80
    /* 17C80 00117C80 7D23EF4B */  vsqi.xyzw  $vf4, ($vi15++)
    /* 17C84 00117C84 7D2BEF4B */  vsqi.xyzw  $vf5, ($vi15++)
    /* 17C88 00117C88 7D33EF4B */  vsqi.xyzw  $vf6, ($vi15++)
    /* 17C8C 00117C8C 7D3BEF4B */  vsqi.xyzw  $vf7, ($vi15++)
    /* 17C90 00117C90 0800E003 */  jr         $ra
    /* 17C94 00117C94 00000000 */   nop
endlabel func_00117C80
