.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117C60, 0x1C

glabel func_00117C60
    /* 17C60 00117C60 3C03E74B */  vmove.xyzw $vf7, $vf0
    /* 17C64 00117C64 3D3BE64B */  vmr32.xyzw $vf6, $vf7
    /* 17C68 00117C68 3D33E54B */  vmr32.xyzw $vf5, $vf6
    /* 17C6C 00117C6C 3D2BE44B */  vmr32.xyzw $vf4, $vf5
    /* 17C70 00117C70 32000F4A */  viaddi     $vi15, $vi0, 0x0
    /* 17C74 00117C74 0800E003 */  jr         $ra
    /* 17C78 00117C78 00000000 */   nop
endlabel func_00117C60
