.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117C40, 0x1C

glabel func_00117C40
    /* 17C40 00117C40 3C03E74B */  vmove.xyzw $vf7, $vf0
    /* 17C44 00117C44 3D3BE64B */  vmr32.xyzw $vf6, $vf7
    /* 17C48 00117C48 3D33E54B */  vmr32.xyzw $vf5, $vf6
    /* 17C4C 00117C4C 3D2BE44B */  vmr32.xyzw $vf4, $vf5
    /* 17C50 00117C50 32000F4A */  viaddi     $vi15, $vi0, 0x0
    /* 17C54 00117C54 0800E003 */  jr         $ra
    /* 17C58 00117C58 00000000 */   nop
endlabel func_00117C40
