.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117CD0, 0x10

glabel func_00117CD0
    /* 17CD0 00117CD0 000088D8 */  lqc2       $vf8, 0x0($a0)
    /* 17CD4 00117CD4 3C43E74B */  vmove.xyzw $vf7, $vf8
    /* 17CD8 00117CD8 0800E003 */  jr         $ra
    /* 17CDC 00117CDC 00000000 */   nop
endlabel func_00117CD0
