.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117CE0, 0xC

glabel func_00117CE0
    /* 17CE0 00117CE0 3C03E74B */  vmove.xyzw $vf7, $vf0
    /* 17CE4 00117CE4 0800E003 */  jr         $ra
    /* 17CE8 00117CE8 00000000 */   nop
endlabel func_00117CE0
