.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117CB0, 0x1C

glabel func_00117CB0
    /* 17CB0 00117CB0 000088D8 */  lqc2       $vf8, 0x0($a0)
    /* 17CB4 00117CB4 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 17CB8 00117CB8 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 17CBC 00117CBC BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 17CC0 00117CC0 CB39E84B */  vmaddw.xyzw $vf7, $vf7, $vf8w
    /* 17CC4 00117CC4 0800E003 */  jr         $ra
    /* 17CC8 00117CC8 00000000 */   nop
endlabel func_00117CB0
