.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117C20, 0x20

glabel func_00117C20
    /* 17C20 00117C20 00600644 */  mfc1       $a2, $f12
    /* 17C24 00117C24 0008A648 */  qmtc2.ni   $a2, $vf1
    /* 17C28 00117C28 BD03014A */  .word      0x4A0103BD                    # vsqrt      $Q, $vf1x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 17C2C 00117C2C BF03004A */  vwaitq
    /* 17C30 00117C30 00B04748 */  cfc2.ni    $a3, $vi22
    /* 17C34 00117C34 00008744 */  mtc1       $a3, $f0
    /* 17C38 00117C38 0800E003 */  jr         $ra
    /* 17C3C 00117C3C 00000000 */   nop
endlabel func_00117C20
