.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117DB0, 0xC0

glabel func_00117DB0
    /* 17DB0 00117DB0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 17DB4 00117DB4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 17DB8 00117DB8 00840400 */  sll        $s0, $a0, 16
    /* 17DBC 00117DBC 2000B4E7 */  swc1       $f20, 0x20($sp)
    /* 17DC0 00117DC0 03841000 */  sra        $s0, $s0, 16
    /* 17DC4 00117DC4 1000BFFF */  sd         $ra, 0x10($sp)
    /* 17DC8 00117DC8 683A040C */  jal        func_0010E9A0
    /* 17DCC 00117DCC 2D200002 */   daddu     $a0, $s0, $zero
    /* 17DD0 00117DD0 06050046 */  mov.s      $f20, $f0
    /* 17DD4 00117DD4 543A040C */  jal        func_0010E950
    /* 17DD8 00117DD8 2D200002 */   daddu     $a0, $s0, $zero
    /* 17DDC 00117DDC 00A00844 */  mfc1       $t0, $f20
    /* 17DE0 00117DE0 00000944 */  mfc1       $t1, $f0
    /* 17DE4 00117DE4 0008A848 */  qmtc2.ni   $t0, $vf1
    /* 17DE8 00117DE8 0010A948 */  qmtc2.ni   $t1, $vf2
    /* 17DEC 00117DEC 3C03F14B */  vmove.xyzw $vf17, $vf0
    /* 17DF0 00117DF0 3D8BF04B */  vmr32.xyzw $vf16, $vf17
    /* 17DF4 00117DF4 3D83EF4B */  vmr32.xyzw $vf15, $vf16
    /* 17DF8 00117DF8 3D7BEE4B */  vmr32.xyzw $vf14, $vf15
    /* 17DFC 00117DFC 8003014B */  vaddx.x    $vf14, $vf0, $vf1x
    /* 17E00 00117E00 0004024B */  vaddx.x    $vf16, $vf0, $vf2x
    /* 17E04 00117E04 8403424A */  vsubx.z    $vf14, $vf0, $vf2x
    /* 17E08 00117E08 0004414A */  vaddx.z    $vf16, $vf0, $vf1x
    /* 17E0C 00117E0C BC21EE4B */  vmulax.xyzw $ACC, $vf4, $vf14x
    /* 17E10 00117E10 BD28EE4B */  vmadday.xyzw $ACC, $vf5, $vf14y
    /* 17E14 00117E14 BE30EE4B */  vmaddaz.xyzw $ACC, $vf6, $vf14z
    /* 17E18 00117E18 8B3BEE4B */  vmaddw.xyzw $vf14, $vf7, $vf14w
    /* 17E1C 00117E1C BC21EF4B */  vmulax.xyzw $ACC, $vf4, $vf15x
    /* 17E20 00117E20 BD28EF4B */  vmadday.xyzw $ACC, $vf5, $vf15y
    /* 17E24 00117E24 BE30EF4B */  vmaddaz.xyzw $ACC, $vf6, $vf15z
    /* 17E28 00117E28 CB3BEF4B */  vmaddw.xyzw $vf15, $vf7, $vf15w
    /* 17E2C 00117E2C BC21F04B */  vmulax.xyzw $ACC, $vf4, $vf16x
    /* 17E30 00117E30 BD28F04B */  vmadday.xyzw $ACC, $vf5, $vf16y
    /* 17E34 00117E34 BE30F04B */  vmaddaz.xyzw $ACC, $vf6, $vf16z
    /* 17E38 00117E38 0B3CF04B */  vmaddw.xyzw $vf16, $vf7, $vf16w
    /* 17E3C 00117E3C BC21F14B */  vmulax.xyzw $ACC, $vf4, $vf17x
    /* 17E40 00117E40 BD28F14B */  vmadday.xyzw $ACC, $vf5, $vf17y
    /* 17E44 00117E44 BE30F14B */  vmaddaz.xyzw $ACC, $vf6, $vf17z
    /* 17E48 00117E48 4B3CF14B */  vmaddw.xyzw $vf17, $vf7, $vf17w
    /* 17E4C 00117E4C 3C73E44B */  vmove.xyzw $vf4, $vf14
    /* 17E50 00117E50 3C7BE54B */  vmove.xyzw $vf5, $vf15
    /* 17E54 00117E54 3C83E64B */  vmove.xyzw $vf6, $vf16
    /* 17E58 00117E58 3C8BE74B */  vmove.xyzw $vf7, $vf17
    /* 17E5C 00117E5C 1000BFDF */  ld         $ra, 0x10($sp)
    /* 17E60 00117E60 0000B0DF */  ld         $s0, 0x0($sp)
    /* 17E64 00117E64 2000B4C7 */  lwc1       $f20, 0x20($sp)
    /* 17E68 00117E68 0800E003 */  jr         $ra
    /* 17E6C 00117E6C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00117DB0

.align 3
nonmatching func_00117E70, 0xC0

glabel func_00117E70
    /* 17E70 00117E70 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 17E74 00117E74 0000B0FF */  sd         $s0, 0x0($sp)
    /* 17E78 00117E78 00840400 */  sll        $s0, $a0, 16
    /* 17E7C 00117E7C 2000B4E7 */  swc1       $f20, 0x20($sp)
    /* 17E80 00117E80 03841000 */  sra        $s0, $s0, 16
    /* 17E84 00117E84 1000BFFF */  sd         $ra, 0x10($sp)
    /* 17E88 00117E88 683A040C */  jal        func_0010E9A0
    /* 17E8C 00117E8C 2D200002 */   daddu     $a0, $s0, $zero
    /* 17E90 00117E90 06050046 */  mov.s      $f20, $f0
    /* 17E94 00117E94 543A040C */  jal        func_0010E950
    /* 17E98 00117E98 2D200002 */   daddu     $a0, $s0, $zero
    /* 17E9C 00117E9C 00A00844 */  mfc1       $t0, $f20
    /* 17EA0 00117EA0 00000944 */  mfc1       $t1, $f0
    /* 17EA4 00117EA4 0008A848 */  qmtc2.ni   $t0, $vf1
    /* 17EA8 00117EA8 0010A948 */  qmtc2.ni   $t1, $vf2
    /* 17EAC 00117EAC 3C03F14B */  vmove.xyzw $vf17, $vf0
    /* 17EB0 00117EB0 3D8BF04B */  vmr32.xyzw $vf16, $vf17
    /* 17EB4 00117EB4 3D83EF4B */  vmr32.xyzw $vf15, $vf16
    /* 17EB8 00117EB8 3D7BEE4B */  vmr32.xyzw $vf14, $vf15
    /* 17EBC 00117EBC 8003014B */  vaddx.x    $vf14, $vf0, $vf1x
    /* 17EC0 00117EC0 C403024B */  vsubx.x    $vf15, $vf0, $vf2x
    /* 17EC4 00117EC4 8003824A */  vaddx.y    $vf14, $vf0, $vf2x
    /* 17EC8 00117EC8 C003814A */  vaddx.y    $vf15, $vf0, $vf1x
    /* 17ECC 00117ECC BC21EE4B */  vmulax.xyzw $ACC, $vf4, $vf14x
    /* 17ED0 00117ED0 BD28EE4B */  vmadday.xyzw $ACC, $vf5, $vf14y
    /* 17ED4 00117ED4 BE30EE4B */  vmaddaz.xyzw $ACC, $vf6, $vf14z
    /* 17ED8 00117ED8 8B3BEE4B */  vmaddw.xyzw $vf14, $vf7, $vf14w
    /* 17EDC 00117EDC BC21EF4B */  vmulax.xyzw $ACC, $vf4, $vf15x
    /* 17EE0 00117EE0 BD28EF4B */  vmadday.xyzw $ACC, $vf5, $vf15y
    /* 17EE4 00117EE4 BE30EF4B */  vmaddaz.xyzw $ACC, $vf6, $vf15z
    /* 17EE8 00117EE8 CB3BEF4B */  vmaddw.xyzw $vf15, $vf7, $vf15w
    /* 17EEC 00117EEC BC21F04B */  vmulax.xyzw $ACC, $vf4, $vf16x
    /* 17EF0 00117EF0 BD28F04B */  vmadday.xyzw $ACC, $vf5, $vf16y
    /* 17EF4 00117EF4 BE30F04B */  vmaddaz.xyzw $ACC, $vf6, $vf16z
    /* 17EF8 00117EF8 0B3CF04B */  vmaddw.xyzw $vf16, $vf7, $vf16w
    /* 17EFC 00117EFC BC21F14B */  vmulax.xyzw $ACC, $vf4, $vf17x
    /* 17F00 00117F00 BD28F14B */  vmadday.xyzw $ACC, $vf5, $vf17y
    /* 17F04 00117F04 BE30F14B */  vmaddaz.xyzw $ACC, $vf6, $vf17z
    /* 17F08 00117F08 4B3CF14B */  vmaddw.xyzw $vf17, $vf7, $vf17w
    /* 17F0C 00117F0C 3C73E44B */  vmove.xyzw $vf4, $vf14
    /* 17F10 00117F10 3C7BE54B */  vmove.xyzw $vf5, $vf15
    /* 17F14 00117F14 3C83E64B */  vmove.xyzw $vf6, $vf16
    /* 17F18 00117F18 3C8BE74B */  vmove.xyzw $vf7, $vf17
    /* 17F1C 00117F1C 1000BFDF */  ld         $ra, 0x10($sp)
    /* 17F20 00117F20 0000B0DF */  ld         $s0, 0x0($sp)
    /* 17F24 00117F24 2000B4C7 */  lwc1       $f20, 0x20($sp)
    /* 17F28 00117F28 0800E003 */  jr         $ra
    /* 17F2C 00117F2C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00117E70

.align 3
nonmatching func_00117F30, 0x8C

glabel func_00117F30
    /* 17F30 00117F30 00600644 */  mfc1       $a2, $f12
    /* 17F34 00117F34 00680744 */  mfc1       $a3, $f13
    /* 17F38 00117F38 00700844 */  mfc1       $t0, $f14
    /* 17F3C 00117F3C 0008A648 */  qmtc2.ni   $a2, $vf1
    /* 17F40 00117F40 0010A748 */  qmtc2.ni   $a3, $vf2
    /* 17F44 00117F44 0018A848 */  qmtc2.ni   $t0, $vf3
    /* 17F48 00117F48 3C03F14B */  vmove.xyzw $vf17, $vf0
    /* 17F4C 00117F4C 3D8BF04B */  vmr32.xyzw $vf16, $vf17
    /* 17F50 00117F50 3D83EF4B */  vmr32.xyzw $vf15, $vf16
    /* 17F54 00117F54 3D7BEE4B */  vmr32.xyzw $vf14, $vf15
    /* 17F58 00117F58 8003014B */  vaddx.x    $vf14, $vf0, $vf1x
    /* 17F5C 00117F5C C003824A */  vaddx.y    $vf15, $vf0, $vf2x
    /* 17F60 00117F60 0004434A */  vaddx.z    $vf16, $vf0, $vf3x
    /* 17F64 00117F64 BC21EE4B */  vmulax.xyzw $ACC, $vf4, $vf14x
    /* 17F68 00117F68 BD28EE4B */  vmadday.xyzw $ACC, $vf5, $vf14y
    /* 17F6C 00117F6C BE30EE4B */  vmaddaz.xyzw $ACC, $vf6, $vf14z
    /* 17F70 00117F70 8B3BEE4B */  vmaddw.xyzw $vf14, $vf7, $vf14w
    /* 17F74 00117F74 BC21EF4B */  vmulax.xyzw $ACC, $vf4, $vf15x
    /* 17F78 00117F78 BD28EF4B */  vmadday.xyzw $ACC, $vf5, $vf15y
    /* 17F7C 00117F7C BE30EF4B */  vmaddaz.xyzw $ACC, $vf6, $vf15z
    /* 17F80 00117F80 CB3BEF4B */  vmaddw.xyzw $vf15, $vf7, $vf15w
    /* 17F84 00117F84 BC21F04B */  vmulax.xyzw $ACC, $vf4, $vf16x
    /* 17F88 00117F88 BD28F04B */  vmadday.xyzw $ACC, $vf5, $vf16y
    /* 17F8C 00117F8C BE30F04B */  vmaddaz.xyzw $ACC, $vf6, $vf16z
    /* 17F90 00117F90 0B3CF04B */  vmaddw.xyzw $vf16, $vf7, $vf16w
    /* 17F94 00117F94 BC21F14B */  vmulax.xyzw $ACC, $vf4, $vf17x
    /* 17F98 00117F98 BD28F14B */  vmadday.xyzw $ACC, $vf5, $vf17y
    /* 17F9C 00117F9C BE30F14B */  vmaddaz.xyzw $ACC, $vf6, $vf17z
    /* 17FA0 00117FA0 4B3CF14B */  vmaddw.xyzw $vf17, $vf7, $vf17w
    /* 17FA4 00117FA4 3C73E44B */  vmove.xyzw $vf4, $vf14
    /* 17FA8 00117FA8 3C7BE54B */  vmove.xyzw $vf5, $vf15
    /* 17FAC 00117FAC 3C83E64B */  vmove.xyzw $vf6, $vf16
    /* 17FB0 00117FB0 3C8BE74B */  vmove.xyzw $vf7, $vf17
    /* 17FB4 00117FB4 0800E003 */  jr         $ra
    /* 17FB8 00117FB8 00000000 */   nop
endlabel func_00117F30
    /* 17FBC 00117FBC 00000000 */  nop
