.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117FC0, 0x18

glabel func_00117FC0
    /* 17FC0 00117FC0 000084F8 */  sqc2       $vf4, 0x0($a0)
    /* 17FC4 00117FC4 100085F8 */  sqc2       $vf5, 0x10($a0)
    /* 17FC8 00117FC8 200086F8 */  sqc2       $vf6, 0x20($a0)
    /* 17FCC 00117FCC 300087F8 */  sqc2       $vf7, 0x30($a0)
    /* 17FD0 00117FD0 0800E003 */  jr         $ra
    /* 17FD4 00117FD4 00000000 */   nop
endlabel func_00117FC0
