.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117FD8, 0xC

glabel func_00117FD8
    /* 17FD8 00117FD8 000087F8 */  sqc2       $vf7, 0x0($a0)
    /* 17FDC 00117FDC 0800E003 */  jr         $ra
    /* 17FE0 00117FE0 00000000 */   nop
endlabel func_00117FD8
