.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00117FE8, 0x18

glabel func_00117FE8
    /* 17FE8 00117FE8 000084D8 */  lqc2       $vf4, 0x0($a0)
    /* 17FEC 00117FEC 100085D8 */  lqc2       $vf5, 0x10($a0)
    /* 17FF0 00117FF0 200086D8 */  lqc2       $vf6, 0x20($a0)
    /* 17FF4 00117FF4 300087D8 */  lqc2       $vf7, 0x30($a0)
    /* 17FF8 00117FF8 0800E003 */  jr         $ra
    /* 17FFC 00117FFC 00000000 */   nop
endlabel func_00117FE8
