.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001180E0, 0x2C

glabel func_001180E0
    /* 180E0 001180E0 0000A8D8 */  lqc2       $vf8, 0x0($a1)
    /* 180E4 001180E4 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 180E8 001180E8 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 180EC 001180EC BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 180F0 001180F0 8B3AE84B */  vmaddw.xyzw $vf10, $vf7, $vf8w
    /* 180F4 001180F4 BC03EA4B */  vdiv       $Q, $vf0w, $vf10w
    /* 180F8 001180F8 BF03004A */  vwaitq
    /* 180FC 001180FC 9C52C04B */  vmulq.xyz  $vf10, $vf10, $Q
    /* 18100 00118100 00008AF8 */  sqc2       $vf10, 0x0($a0)
    /* 18104 00118104 0800E003 */  jr         $ra
    /* 18108 00118108 00000000 */   nop
endlabel func_001180E0
