.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001180C0, 0x20

glabel func_001180C0
    /* 180C0 001180C0 0000A8D8 */  lqc2       $vf8, 0x0($a1)
    /* 180C4 001180C4 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 180C8 001180C8 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 180CC 001180CC BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 180D0 001180D0 8B3AE84B */  vmaddw.xyzw $vf10, $vf7, $vf8w
    /* 180D4 001180D4 00008AF8 */  sqc2       $vf10, 0x0($a0)
    /* 180D8 001180D8 0800E003 */  jr         $ra
    /* 180DC 001180DC 00000000 */   nop
endlabel func_001180C0
