.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118000, 0x68

glabel func_00118000
    /* 18000 00118000 00008ED8 */  lqc2       $vf14, 0x0($a0)
    /* 18004 00118004 10008FD8 */  lqc2       $vf15, 0x10($a0)
    /* 18008 00118008 200090D8 */  lqc2       $vf16, 0x20($a0)
    /* 1800C 0011800C 300091D8 */  lqc2       $vf17, 0x30($a0)
    /* 18010 00118010 BC21EE4B */  vmulax.xyzw $ACC, $vf4, $vf14x
    /* 18014 00118014 BD28EE4B */  vmadday.xyzw $ACC, $vf5, $vf14y
    /* 18018 00118018 BE30EE4B */  vmaddaz.xyzw $ACC, $vf6, $vf14z
    /* 1801C 0011801C 8B3BEE4B */  vmaddw.xyzw $vf14, $vf7, $vf14w
    /* 18020 00118020 BC21EF4B */  vmulax.xyzw $ACC, $vf4, $vf15x
    /* 18024 00118024 BD28EF4B */  vmadday.xyzw $ACC, $vf5, $vf15y
    /* 18028 00118028 BE30EF4B */  vmaddaz.xyzw $ACC, $vf6, $vf15z
    /* 1802C 0011802C CB3BEF4B */  vmaddw.xyzw $vf15, $vf7, $vf15w
    /* 18030 00118030 BC21F04B */  vmulax.xyzw $ACC, $vf4, $vf16x
    /* 18034 00118034 BD28F04B */  vmadday.xyzw $ACC, $vf5, $vf16y
    /* 18038 00118038 BE30F04B */  vmaddaz.xyzw $ACC, $vf6, $vf16z
    /* 1803C 0011803C 0B3CF04B */  vmaddw.xyzw $vf16, $vf7, $vf16w
    /* 18040 00118040 BC21F14B */  vmulax.xyzw $ACC, $vf4, $vf17x
    /* 18044 00118044 BD28F14B */  vmadday.xyzw $ACC, $vf5, $vf17y
    /* 18048 00118048 BE30F14B */  vmaddaz.xyzw $ACC, $vf6, $vf17z
    /* 1804C 0011804C 4B3CF14B */  vmaddw.xyzw $vf17, $vf7, $vf17w
    /* 18050 00118050 3C73E44B */  vmove.xyzw $vf4, $vf14
    /* 18054 00118054 3C7BE54B */  vmove.xyzw $vf5, $vf15
    /* 18058 00118058 3C83E64B */  vmove.xyzw $vf6, $vf16
    /* 1805C 0011805C 3C8BE74B */  vmove.xyzw $vf7, $vf17
    /* 18060 00118060 0800E003 */  jr         $ra
    /* 18064 00118064 00000000 */   nop
endlabel func_00118000
