.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118190, 0x4C

glabel func_00118190
    /* 18190 00118190 6C00E04B */  vsub.xyzw  $vf1, $vf0, $vf0
    /* 18194 00118194 8700004B */  vsubw.x    $vf2, $vf0, $vf0w
    /* 18198 00118198 800B854A */  vaddx.y    $vf14, $vf1, $vf5x
    /* 1819C 0011819C 800B464A */  vaddx.z    $vf14, $vf1, $vf6x
    /* 181A0 001181A0 C10B044B */  vaddy.x    $vf15, $vf1, $vf4y
    /* 181A4 001181A4 C10B464A */  vaddy.z    $vf15, $vf1, $vf6y
    /* 181A8 001181A8 020C044B */  vaddz.x    $vf16, $vf1, $vf4z
    /* 181AC 001181AC 020C854A */  vaddz.y    $vf16, $vf1, $vf5z
    /* 181B0 001181B0 583CC24B */  vmulx.xyz  $vf17, $vf7, $vf2x
    /* 181B4 001181B4 3C73C44A */  vmove.yz   $vf4, $vf14
    /* 181B8 001181B8 3C7B454B */  vmove.xz   $vf5, $vf15
    /* 181BC 001181BC 3C83864B */  vmove.xy   $vf6, $vf16
    /* 181C0 001181C0 3C03314A */  vmove.w    $vf17, $vf0
    /* 181C4 001181C4 BC21F14B */  vmulax.xyzw $ACC, $vf4, $vf17x
    /* 181C8 001181C8 BD28F14B */  vmadday.xyzw $ACC, $vf5, $vf17y
    /* 181CC 001181CC BE30F14B */  vmaddaz.xyzw $ACC, $vf6, $vf17z
    /* 181D0 001181D0 CB01F14B */  vmaddw.xyzw $vf7, $vf0, $vf17w
    /* 181D4 001181D4 0800E003 */  jr         $ra
    /* 181D8 001181D8 00000000 */   nop
endlabel func_00118190
