.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118160, 0x30

glabel func_00118160
    /* 18160 00118160 6C00E04B */  vsub.xyzw  $vf1, $vf0, $vf0
    /* 18164 00118164 800B854A */  vaddx.y    $vf14, $vf1, $vf5x
    /* 18168 00118168 800B464A */  vaddx.z    $vf14, $vf1, $vf6x
    /* 1816C 0011816C C10B044B */  vaddy.x    $vf15, $vf1, $vf4y
    /* 18170 00118170 C10B464A */  vaddy.z    $vf15, $vf1, $vf6y
    /* 18174 00118174 020C044B */  vaddz.x    $vf16, $vf1, $vf4z
    /* 18178 00118178 020C854A */  vaddz.y    $vf16, $vf1, $vf5z
    /* 1817C 0011817C 3C73C44A */  vmove.yz   $vf4, $vf14
    /* 18180 00118180 3C7B454B */  vmove.xz   $vf5, $vf15
    /* 18184 00118184 3C83864B */  vmove.xy   $vf6, $vf16
    /* 18188 00118188 0800E003 */  jr         $ra
    /* 1818C 0011818C 00000000 */   nop
endlabel func_00118160
