.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0011810C, 0x4

glabel func_0011810C
    /* 1810C 0011810C 00000000 */  nop
endlabel func_0011810C
