.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118110, 0x4C

glabel func_00118110
    /* 18110 00118110 6C00E04B */  vsub.xyzw  $vf1, $vf0, $vf0
    /* 18114 00118114 800B854A */  vaddx.y    $vf14, $vf1, $vf5x
    /* 18118 00118118 800B464A */  vaddx.z    $vf14, $vf1, $vf6x
    /* 1811C 0011811C 800B274A */  vaddx.w    $vf14, $vf1, $vf7x
    /* 18120 00118120 C10B044B */  vaddy.x    $vf15, $vf1, $vf4y
    /* 18124 00118124 C10B464A */  vaddy.z    $vf15, $vf1, $vf6y
    /* 18128 00118128 C10B274A */  vaddy.w    $vf15, $vf1, $vf7y
    /* 1812C 0011812C 020C044B */  vaddz.x    $vf16, $vf1, $vf4z
    /* 18130 00118130 020C854A */  vaddz.y    $vf16, $vf1, $vf5z
    /* 18134 00118134 020C274A */  vaddz.w    $vf16, $vf1, $vf7z
    /* 18138 00118138 430C044B */  vaddw.x    $vf17, $vf1, $vf4w
    /* 1813C 0011813C 430C854A */  vaddw.y    $vf17, $vf1, $vf5w
    /* 18140 00118140 430C464A */  vaddw.z    $vf17, $vf1, $vf6w
    /* 18144 00118144 3C73E44A */  vmove.yzw  $vf4, $vf14
    /* 18148 00118148 3C7B654B */  vmove.xzw  $vf5, $vf15
    /* 1814C 0011814C 3C83A64B */  vmove.xyw  $vf6, $vf16
    /* 18150 00118150 3C8BC74B */  vmove.xyz  $vf7, $vf17
    /* 18154 00118154 0800E003 */  jr         $ra
    /* 18158 00118158 00000000 */   nop
endlabel func_00118110
