.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001182F0, 0x2C

glabel func_001182F0
    /* 182F0 001182F0 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 182F4 001182F4 EA08C14B */  vmul.xyz   $vf3, $vf1, $vf1
    /* 182F8 001182F8 BC01234A */  vmulax.w   $ACC, $vf0, $vf3x
    /* 182FC 001182FC BD00234A */  vmadday.w  $ACC, $vf0, $vf3y
    /* 18300 00118300 CA00234A */  vmaddz.w   $vf3, $vf0, $vf3z
    /* 18304 00118304 BE03E34B */  vrsqrt     $Q, $vf0w, $vf3w
    /* 18308 00118308 BF03004A */  vwaitq
    /* 1830C 0011830C 5C08C04B */  vmulq.xyz  $vf1, $vf1, $Q
    /* 18310 00118310 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 18314 00118314 0800E003 */  jr         $ra
    /* 18318 00118318 00000000 */   nop
endlabel func_001182F0
