.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118370, 0x18

glabel func_00118370
    /* 18370 00118370 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 18374 00118374 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 18378 00118378 E808E24B */  vadd.xyzw  $vf3, $vf1, $vf2
    /* 1837C 0011837C 000083F8 */  sqc2       $vf3, 0x0($a0)
    /* 18380 00118380 0800E003 */  jr         $ra
    /* 18384 00118384 00000000 */   nop
endlabel func_00118370
