.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118388, 0x18

glabel func_00118388
    /* 18388 00118388 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 1838C 0011838C 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 18390 00118390 6808C24B */  vadd.xyz   $vf1, $vf1, $vf2
    /* 18394 00118394 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 18398 00118398 0800E003 */  jr         $ra
    /* 1839C 0011839C 00000000 */   nop
endlabel func_00118388
