.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118320, 0x2C

glabel func_00118320
    /* 18320 00118320 000081D8 */  lqc2       $vf1, 0x0($a0)
    /* 18324 00118324 0000A2D8 */  lqc2       $vf2, 0x0($a1)
    /* 18328 00118328 C300004B */  vaddw.x    $vf3, $vf0, $vf0w
    /* 1832C 0011832C AA08C24B */  vmul.xyz   $vf2, $vf1, $vf2
    /* 18330 00118330 3C00024B */  vaddax.x   $ACC, $vf0, $vf2x
    /* 18334 00118334 BD18024B */  vmadday.x  $ACC, $vf3, $vf2y
    /* 18338 00118338 8A18024B */  vmaddz.x   $vf2, $vf3, $vf2z
    /* 1833C 0011833C 00102248 */  qmfc2.ni   $v0, $vf2
    /* 18340 00118340 00008244 */  mtc1       $v0, $f0
    /* 18344 00118344 0800E003 */  jr         $ra
    /* 18348 00118348 00000000 */   nop
endlabel func_00118320
