.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118350, 0x20

glabel func_00118350
    /* 18350 00118350 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 18354 00118354 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 18358 00118358 FE0AC24B */  vopmula.xyz $ACC, $vf1, $vf2
    /* 1835C 0011835C EE10C14B */  vopmsub.xyz $vf3, $vf2, $vf1
    /* 18360 00118360 EC18234A */  vsub.w     $vf3, $vf3, $vf3
    /* 18364 00118364 000083F8 */  sqc2       $vf3, 0x0($a0)
    /* 18368 00118368 0800E003 */  jr         $ra
    /* 1836C 0011836C 00000000 */   nop
endlabel func_00118350
