.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001183F0, 0x1C

glabel func_001183F0
    /* 183F0 001183F0 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 183F4 001183F4 00600844 */  mfc1       $t0, $f12
    /* 183F8 001183F8 0010A848 */  qmtc2.ni   $t0, $vf2
    /* 183FC 001183FC 5808C24B */  vmulx.xyz  $vf1, $vf1, $vf2x
    /* 18400 00118400 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 18404 00118404 0800E003 */  jr         $ra
    /* 18408 00118408 00000000 */   nop
endlabel func_001183F0
