.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001183D0, 0x1C

glabel func_001183D0
    /* 183D0 001183D0 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 183D4 001183D4 00600844 */  mfc1       $t0, $f12
    /* 183D8 001183D8 0010A848 */  qmtc2.ni   $t0, $vf2
    /* 183DC 001183DC D808E24B */  vmulx.xyzw $vf3, $vf1, $vf2x
    /* 183E0 001183E0 000083F8 */  sqc2       $vf3, 0x0($a0)
    /* 183E4 001183E4 0800E003 */  jr         $ra
    /* 183E8 001183E8 00000000 */   nop
endlabel func_001183D0
