.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0011831C, 0x4

glabel func_0011831C
    /* 1831C 0011831C 00000000 */  nop
endlabel func_0011831C
