.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001183B8, 0x18

glabel func_001183B8
    /* 183B8 001183B8 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 183BC 001183BC 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 183C0 001183C0 6C08C24B */  vsub.xyz   $vf1, $vf1, $vf2
    /* 183C4 001183C4 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 183C8 001183C8 0800E003 */  jr         $ra
    /* 183CC 001183CC 00000000 */   nop
endlabel func_001183B8
