.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001183EC, 0x4

glabel func_001183EC
    /* 183EC 001183EC 00000000 */  nop
endlabel func_001183EC
