.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001183A0, 0x18

glabel func_001183A0
    /* 183A0 001183A0 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 183A4 001183A4 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 183A8 001183A8 EC08E24B */  vsub.xyzw  $vf3, $vf1, $vf2
    /* 183AC 001183AC 000083F8 */  sqc2       $vf3, 0x0($a0)
    /* 183B0 001183B0 0800E003 */  jr         $ra
    /* 183B4 001183B4 00000000 */   nop
endlabel func_001183A0
