.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118490, 0x28

glabel func_00118490
    /* 18490 00118490 00600844 */  mfc1       $t0, $f12
    /* 18494 00118494 0018A848 */  qmtc2.ni   $t0, $vf3
    /* 18498 00118498 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 1849C 0011849C 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 184A0 001184A0 0402234A */  vsubx.w    $vf8, $vf0, $vf3x
    /* 184A4 001184A4 BC09E34B */  vmulax.xyzw $ACC, $vf1, $vf3x
    /* 184A8 001184A8 4B12E84B */  vmaddw.xyzw $vf9, $vf2, $vf8w
    /* 184AC 001184AC 000089F8 */  sqc2       $vf9, 0x0($a0)
    /* 184B0 001184B0 0800E003 */  jr         $ra
    /* 184B4 001184B4 00000000 */   nop
endlabel func_00118490
