.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118430, 0x14

glabel func_00118430
    /* 18430 00118430 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 18434 00118434 7D09E24B */  vftoi4.xyzw $vf2, $vf1
    /* 18438 00118438 000082F8 */  sqc2       $vf2, 0x0($a0)
    /* 1843C 0011843C 0800E003 */  jr         $ra
    /* 18440 00118440 00000000 */   nop
endlabel func_00118430
