.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118410, 0x20

glabel func_00118410
    /* 18410 00118410 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 18414 00118414 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 18418 00118418 5808024B */  vmulx.x    $vf1, $vf1, $vf2x
    /* 1841C 0011841C 5908824A */  vmuly.y    $vf1, $vf1, $vf2y
    /* 18420 00118420 5A08424A */  vmulz.z    $vf1, $vf1, $vf2z
    /* 18424 00118424 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 18428 00118428 0800E003 */  jr         $ra
    /* 1842C 0011842C 00000000 */   nop
endlabel func_00118410
