.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118480, 0xC

glabel func_00118480
    /* 18480 00118480 000080F8 */  sqc2       $vf0, 0x0($a0)
    /* 18484 00118484 0800E003 */  jr         $ra
    /* 18488 00118488 00000000 */   nop
endlabel func_00118480
