.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001184E0, 0x2C

glabel func_001184E0
    /* 184E0 001184E0 000083D8 */  lqc2       $vf3, 0x0($a0)
    /* 184E4 001184E4 EA18C34B */  vmul.xyz   $vf3, $vf3, $vf3
    /* 184E8 001184E8 BC01234A */  vmulax.w   $ACC, $vf0, $vf3x
    /* 184EC 001184EC BD00234A */  vmadday.w  $ACC, $vf0, $vf3y
    /* 184F0 001184F0 CA00234A */  vmaddz.w   $vf3, $vf0, $vf3z
    /* 184F4 001184F4 BD03834B */  .word      0x4B8303BD                    # vsqrt      $Q, $vf3w # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 184F8 001184F8 BF03004A */  vwaitq
    /* 184FC 001184FC 00B04248 */  cfc2.ni    $v0, $vi22
    /* 18500 00118500 00008244 */  mtc1       $v0, $f0
    /* 18504 00118504 0800E003 */  jr         $ra
    /* 18508 00118508 00000000 */   nop
endlabel func_001184E0
