.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118448, 0x14

glabel func_00118448
    /* 18448 00118448 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 1844C 0011844C 7C09E24B */  vftoi0.xyzw $vf2, $vf1
    /* 18450 00118450 000082F8 */  sqc2       $vf2, 0x0($a0)
    /* 18454 00118454 0800E003 */  jr         $ra
    /* 18458 00118458 00000000 */   nop
endlabel func_00118448
