.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001184B8, 0x28

glabel func_001184B8
    /* 184B8 001184B8 00600844 */  mfc1       $t0, $f12
    /* 184BC 001184BC 0018A848 */  qmtc2.ni   $t0, $vf3
    /* 184C0 001184C0 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* 184C4 001184C4 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 184C8 001184C8 0402234A */  vsubx.w    $vf8, $vf0, $vf3x
    /* 184CC 001184CC BC09C34B */  vmulax.xyz $ACC, $vf1, $vf3x
    /* 184D0 001184D0 4B10C84B */  vmaddw.xyz $vf1, $vf2, $vf8w
    /* 184D4 001184D4 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 184D8 001184D8 0800E003 */  jr         $ra
    /* 184DC 001184DC 00000000 */   nop
endlabel func_001184B8
