.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001185A8, 0x28

glabel func_001185A8
    /* 185A8 001185A8 0000A678 */  lq         $a2, 0x0($a1)
    /* 185AC 001185AC 1000A778 */  lq         $a3, 0x10($a1)
    /* 185B0 001185B0 2000A878 */  lq         $t0, 0x20($a1)
    /* 185B4 001185B4 3000A978 */  lq         $t1, 0x30($a1)
    /* 185B8 001185B8 0000867C */  sq         $a2, 0x0($a0)
    /* 185BC 001185BC 1000877C */  sq         $a3, 0x10($a0)
    /* 185C0 001185C0 2000887C */  sq         $t0, 0x20($a0)
    /* 185C4 001185C4 3000897C */  sq         $t1, 0x30($a0)
    /* 185C8 001185C8 0800E003 */  jr         $ra
    /* 185CC 001185CC 00000000 */   nop
endlabel func_001185A8
