.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118578, 0x2C

glabel func_00118578
    /* 18578 00118578 000081D8 */  lqc2       $vf1, 0x0($a0)
    /* 1857C 0011857C 0000A2D8 */  lqc2       $vf2, 0x0($a1)
    /* 18580 00118580 EC08E24B */  vsub.xyzw  $vf3, $vf1, $vf2
    /* 18584 00118584 EA18434B */  vmul.xz    $vf3, $vf3, $vf3
    /* 18588 00118588 C218034B */  vaddz.x    $vf3, $vf3, $vf3z
    /* 1858C 0011858C BD03034A */  .word      0x4A0303BD                    # vsqrt      $Q, $vf3x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 18590 00118590 BF03004A */  vwaitq
    /* 18594 00118594 00B04248 */  cfc2.ni    $v0, $vi22
    /* 18598 00118598 00008244 */  mtc1       $v0, $f0
    /* 1859C 0011859C 0800E003 */  jr         $ra
    /* 185A0 001185A0 00000000 */   nop
endlabel func_00118578
