.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118510, 0x34

glabel func_00118510
    /* 18510 00118510 000081D8 */  lqc2       $vf1, 0x0($a0)
    /* 18514 00118514 0000A2D8 */  lqc2       $vf2, 0x0($a1)
    /* 18518 00118518 EC08E24B */  vsub.xyzw  $vf3, $vf1, $vf2
    /* 1851C 0011851C EA18C34B */  vmul.xyz   $vf3, $vf3, $vf3
    /* 18520 00118520 BC01234A */  vmulax.w   $ACC, $vf0, $vf3x
    /* 18524 00118524 BD00234A */  vmadday.w  $ACC, $vf0, $vf3y
    /* 18528 00118528 CA00234A */  vmaddz.w   $vf3, $vf0, $vf3z
    /* 1852C 0011852C BD03834B */  .word      0x4B8303BD                    # vsqrt      $Q, $vf3w # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 18530 00118530 BF03004A */  vwaitq
    /* 18534 00118534 00B04248 */  cfc2.ni    $v0, $vi22
    /* 18538 00118538 00008244 */  mtc1       $v0, $f0
    /* 1853C 0011853C 0800E003 */  jr         $ra
    /* 18540 00118540 00000000 */   nop
endlabel func_00118510
