.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118548, 0x2C

glabel func_00118548
    /* 18548 00118548 000081D8 */  lqc2       $vf1, 0x0($a0)
    /* 1854C 0011854C 0000A2D8 */  lqc2       $vf2, 0x0($a1)
    /* 18550 00118550 EC08E24B */  vsub.xyzw  $vf3, $vf1, $vf2
    /* 18554 00118554 EA18834B */  vmul.xy    $vf3, $vf3, $vf3
    /* 18558 00118558 C118034B */  vaddy.x    $vf3, $vf3, $vf3y
    /* 1855C 0011855C BD03034A */  .word      0x4A0303BD                    # vsqrt      $Q, $vf3x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 18560 00118560 BF03004A */  vwaitq
    /* 18564 00118564 00B04248 */  cfc2.ni    $v0, $vi22
    /* 18568 00118568 00008244 */  mtc1       $v0, $f0
    /* 1856C 0011856C 0800E003 */  jr         $ra
    /* 18570 00118570 00000000 */   nop
endlabel func_00118548
