.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001186A0, 0x24

glabel func_001186A0
    /* 186A0 001186A0 3C03F14B */  vmove.xyzw $vf17, $vf0
    /* 186A4 001186A4 3D8BF04B */  vmr32.xyzw $vf16, $vf17
    /* 186A8 001186A8 3D83EF4B */  vmr32.xyzw $vf15, $vf16
    /* 186AC 001186AC 3D7BEE4B */  vmr32.xyzw $vf14, $vf15
    /* 186B0 001186B0 00008EF8 */  sqc2       $vf14, 0x0($a0)
    /* 186B4 001186B4 10008FF8 */  sqc2       $vf15, 0x10($a0)
    /* 186B8 001186B8 200090F8 */  sqc2       $vf16, 0x20($a0)
    /* 186BC 001186BC 0800E003 */  jr         $ra
    /* 186C0 001186C0 00000000 */   nop
endlabel func_001186A0
