.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118678, 0x28

glabel func_00118678
    /* 18678 00118678 3C03F14B */  vmove.xyzw $vf17, $vf0
    /* 1867C 0011867C 3D8BF04B */  vmr32.xyzw $vf16, $vf17
    /* 18680 00118680 3D83EF4B */  vmr32.xyzw $vf15, $vf16
    /* 18684 00118684 3D7BEE4B */  vmr32.xyzw $vf14, $vf15
    /* 18688 00118688 00008EF8 */  sqc2       $vf14, 0x0($a0)
    /* 1868C 0011868C 10008FF8 */  sqc2       $vf15, 0x10($a0)
    /* 18690 00118690 200090F8 */  sqc2       $vf16, 0x20($a0)
    /* 18694 00118694 300091F8 */  sqc2       $vf17, 0x30($a0)
    /* 18698 00118698 0800E003 */  jr         $ra
    /* 1869C 0011869C 00000000 */   nop
endlabel func_00118678
