.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118648, 0x30

glabel func_00118648
    /* 18648 00118648 0000C8D8 */  lqc2       $vf8, 0x0($a2)
    /* 1864C 0011864C 0000AED8 */  lqc2       $vf14, 0x0($a1)
    /* 18650 00118650 1000AFD8 */  lqc2       $vf15, 0x10($a1)
    /* 18654 00118654 2000B0D8 */  lqc2       $vf16, 0x20($a1)
    /* 18658 00118658 3000B1D8 */  lqc2       $vf17, 0x30($a1)
    /* 1865C 0011865C BC71E84B */  vmulax.xyzw $ACC, $vf14, $vf8x
    /* 18660 00118660 BD78E84B */  vmadday.xyzw $ACC, $vf15, $vf8y
    /* 18664 00118664 BE80E84B */  vmaddaz.xyzw $ACC, $vf16, $vf8z
    /* 18668 00118668 8B8AE84B */  vmaddw.xyzw $vf10, $vf17, $vf8w
    /* 1866C 0011866C 00008AF8 */  sqc2       $vf10, 0x0($a0)
    /* 18670 00118670 0800E003 */  jr         $ra
    /* 18674 00118674 00000000 */   nop
endlabel func_00118648
