.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001186C4, 0x4

glabel func_001186C4
    /* 186C4 001186C4 00000000 */  nop
endlabel func_001186C4
