.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118710, 0x70

glabel func_00118710
    /* 18710 00118710 0000A878 */  lq         $t0, 0x0($a1)
    /* 18714 00118714 1000A978 */  lq         $t1, 0x10($a1)
    /* 18718 00118718 2000AA78 */  lq         $t2, 0x20($a1)
    /* 1871C 0011871C 3000A4D8 */  lqc2       $vf4, 0x30($a1)
    /* 18720 00118720 3C23E54B */  vmove.xyzw $vf5, $vf4
    /* 18724 00118724 2C21C44B */  vsub.xyz   $vf4, $vf4, $vf4
    /* 18728 00118728 3C23E94B */  vmove.xyzw $vf9, $vf4
    /* 1872C 0011872C 00202B48 */  qmfc2.ni   $t3, $vf4
    /* 18730 00118730 88642871 */  pextlw     $t4, $t1, $t0
    /* 18734 00118734 A86C2871 */  pextuw     $t5, $t1, $t0
    /* 18738 00118738 88746A71 */  pextlw     $t6, $t3, $t2
    /* 1873C 0011873C A87C6A71 */  pextuw     $t7, $t3, $t2
    /* 18740 00118740 8943CC71 */  pcpyld     $t0, $t6, $t4
    /* 18744 00118744 A94B8E71 */  pcpyud     $t1, $t4, $t6
    /* 18748 00118748 8953ED71 */  pcpyld     $t2, $t7, $t5
    /* 1874C 0011874C 0030A848 */  qmtc2.ni   $t0, $vf6
    /* 18750 00118750 0038A948 */  qmtc2.ni   $t1, $vf7
    /* 18754 00118754 0040AA48 */  qmtc2.ni   $t2, $vf8
    /* 18758 00118758 BC31C54B */  vmulax.xyz $ACC, $vf6, $vf5x
    /* 1875C 0011875C BD38C54B */  vmadday.xyz $ACC, $vf7, $vf5y
    /* 18760 00118760 0A41C54B */  vmaddz.xyz $vf4, $vf8, $vf5z
    /* 18764 00118764 2C49C44B */  vsub.xyz   $vf4, $vf9, $vf4
    /* 18768 00118768 0000887C */  sq         $t0, 0x0($a0)
    /* 1876C 0011876C 1000897C */  sq         $t1, 0x10($a0)
    /* 18770 00118770 20008A7C */  sq         $t2, 0x20($a0)
    /* 18774 00118774 300084F8 */  sqc2       $vf4, 0x30($a0)
    /* 18778 00118778 0800E003 */  jr         $ra
    /* 1877C 0011877C 00000000 */   nop
endlabel func_00118710

.align 3
nonmatching func_00118780, 0x98

glabel func_00118780
    /* 18780 00118780 0000C1C4 */  lwc1       $f1, 0x0($a2)
    /* 18784 00118784 2700033C */  lui        $v1, %hi(D_002761D0)
    /* 18788 00118788 D0616224 */  addiu      $v0, $v1, %lo(D_002761D0)
    /* 1878C 0011878C D06161E4 */  swc1       $f1, %lo(D_002761D0)($v1)
    /* 18790 00118790 0400C0C4 */  lwc1       $f0, 0x4($a2)
    /* 18794 00118794 140040E4 */  swc1       $f0, 0x14($v0)
    /* 18798 00118798 0800C1C4 */  lwc1       $f1, 0x8($a2)
    /* 1879C 0011879C 280041E4 */  swc1       $f1, 0x28($v0)
    /* 187A0 001187A0 0000AED8 */  lqc2       $vf14, 0x0($a1)
    /* 187A4 001187A4 1000AFD8 */  lqc2       $vf15, 0x10($a1)
    /* 187A8 001187A8 2000B0D8 */  lqc2       $vf16, 0x20($a1)
    /* 187AC 001187AC 3000B1D8 */  lqc2       $vf17, 0x30($a1)
    /* 187B0 001187B0 000058D8 */  lqc2       $vf24, 0x0($v0)
    /* 187B4 001187B4 100059D8 */  lqc2       $vf25, 0x10($v0)
    /* 187B8 001187B8 20005AD8 */  lqc2       $vf26, 0x20($v0)
    /* 187BC 001187BC 30005BD8 */  lqc2       $vf27, 0x30($v0)
    /* 187C0 001187C0 BC71F84B */  vmulax.xyzw $ACC, $vf14, $vf24x
    /* 187C4 001187C4 BD78F84B */  vmadday.xyzw $ACC, $vf15, $vf24y
    /* 187C8 001187C8 BE80F84B */  vmaddaz.xyzw $ACC, $vf16, $vf24z
    /* 187CC 001187CC 0B8EF84B */  vmaddw.xyzw $vf24, $vf17, $vf24w
    /* 187D0 001187D0 BC71F94B */  vmulax.xyzw $ACC, $vf14, $vf25x
    /* 187D4 001187D4 BD78F94B */  vmadday.xyzw $ACC, $vf15, $vf25y
    /* 187D8 001187D8 BE80F94B */  vmaddaz.xyzw $ACC, $vf16, $vf25z
    /* 187DC 001187DC 4B8EF94B */  vmaddw.xyzw $vf25, $vf17, $vf25w
    /* 187E0 001187E0 BC71FA4B */  vmulax.xyzw $ACC, $vf14, $vf26x
    /* 187E4 001187E4 BD78FA4B */  vmadday.xyzw $ACC, $vf15, $vf26y
    /* 187E8 001187E8 BE80FA4B */  vmaddaz.xyzw $ACC, $vf16, $vf26z
    /* 187EC 001187EC 8B8EFA4B */  vmaddw.xyzw $vf26, $vf17, $vf26w
    /* 187F0 001187F0 BC71FB4B */  vmulax.xyzw $ACC, $vf14, $vf27x
    /* 187F4 001187F4 BD78FB4B */  vmadday.xyzw $ACC, $vf15, $vf27y
    /* 187F8 001187F8 BE80FB4B */  vmaddaz.xyzw $ACC, $vf16, $vf27z
    /* 187FC 001187FC CB8EFB4B */  vmaddw.xyzw $vf27, $vf17, $vf27w
    /* 18800 00118800 000098F8 */  sqc2       $vf24, 0x0($a0)
    /* 18804 00118804 100099F8 */  sqc2       $vf25, 0x10($a0)
    /* 18808 00118808 20009AF8 */  sqc2       $vf26, 0x20($a0)
    /* 1880C 0011880C 30009BF8 */  sqc2       $vf27, 0x30($a0)
    /* 18810 00118810 0800E003 */  jr         $ra
    /* 18814 00118814 00000000 */   nop
endlabel func_00118780

.align 3
nonmatching func_00118818, 0x124

glabel func_00118818
    /* 18818 00118818 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 1881C 0011881C 3C03F14B */  vmove.xyzw $vf17, $vf0
    /* 18820 00118820 3D8BF04B */  vmr32.xyzw $vf16, $vf17
    /* 18824 00118824 3D83EF4B */  vmr32.xyzw $vf15, $vf16
    /* 18828 00118828 3D7BEE4B */  vmr32.xyzw $vf14, $vf15
    /* 1882C 0011882C 0000AEFB */  sqc2       $vf14, 0x0($sp)
    /* 18830 00118830 1000AFFB */  sqc2       $vf15, 0x10($sp)
    /* 18834 00118834 2000B0FB */  sqc2       $vf16, 0x20($sp)
    /* 18838 00118838 3000B1FB */  sqc2       $vf17, 0x30($sp)
    /* 1883C 0011883C 4000A227 */  addiu      $v0, $sp, 0x40
    /* 18840 00118840 0000E1D8 */  lqc2       $vf1, 0x0($a3)
    /* 18844 00118844 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* 18848 00118848 FE0AC24B */  vopmula.xyz $ACC, $vf1, $vf2
    /* 1884C 0011884C EE10C14B */  vopmsub.xyz $vf3, $vf2, $vf1
    /* 18850 00118850 EC18234A */  vsub.w     $vf3, $vf3, $vf3
    /* 18854 00118854 000043F8 */  sqc2       $vf3, 0x0($v0)
    /* 18858 00118858 000041D8 */  lqc2       $vf1, 0x0($v0)
    /* 1885C 0011885C EA08C14B */  vmul.xyz   $vf3, $vf1, $vf1
    /* 18860 00118860 BC01234A */  vmulax.w   $ACC, $vf0, $vf3x
    /* 18864 00118864 BD00234A */  vmadday.w  $ACC, $vf0, $vf3y
    /* 18868 00118868 CA00234A */  vmaddz.w   $vf3, $vf0, $vf3z
    /* 1886C 0011886C BE03E34B */  vrsqrt     $Q, $vf0w, $vf3w
    /* 18870 00118870 BF03004A */  vwaitq
    /* 18874 00118874 5C08C04B */  vmulq.xyz  $vf1, $vf1, $Q
    /* 18878 00118878 0000A1FB */  sqc2       $vf1, 0x0($sp)
    /* 1887C 0011887C 2000A727 */  addiu      $a3, $sp, 0x20
    /* 18880 00118880 0000C1D8 */  lqc2       $vf1, 0x0($a2)
    /* 18884 00118884 EA08C14B */  vmul.xyz   $vf3, $vf1, $vf1
    /* 18888 00118888 BC01234A */  vmulax.w   $ACC, $vf0, $vf3x
    /* 1888C 0011888C BD00234A */  vmadday.w  $ACC, $vf0, $vf3y
    /* 18890 00118890 CA00234A */  vmaddz.w   $vf3, $vf0, $vf3z
    /* 18894 00118894 BE03E34B */  vrsqrt     $Q, $vf0w, $vf3w
    /* 18898 00118898 BF03004A */  vwaitq
    /* 1889C 0011889C 5C08C04B */  vmulq.xyz  $vf1, $vf1, $Q
    /* 188A0 001188A0 0000E1F8 */  sqc2       $vf1, 0x0($a3)
    /* 188A4 001188A4 1000A227 */  addiu      $v0, $sp, 0x10
    /* 188A8 001188A8 0000E1D8 */  lqc2       $vf1, 0x0($a3)
    /* 188AC 001188AC 0000A2DB */  lqc2       $vf2, 0x0($sp)
    /* 188B0 001188B0 FE0AC24B */  vopmula.xyz $ACC, $vf1, $vf2
    /* 188B4 001188B4 EE10C14B */  vopmsub.xyz $vf3, $vf2, $vf1
    /* 188B8 001188B8 EC18234A */  vsub.w     $vf3, $vf3, $vf3
    /* 188BC 001188BC 000043F8 */  sqc2       $vf3, 0x0($v0)
    /* 188C0 001188C0 3000A327 */  addiu      $v1, $sp, 0x30
    /* 188C4 001188C4 0000A878 */  lq         $t0, 0x0($a1)
    /* 188C8 001188C8 0000687C */  sq         $t0, 0x0($v1)
    /* 188CC 001188CC 0000A87B */  lq         $t0, 0x0($sp)
    /* 188D0 001188D0 1000A97B */  lq         $t1, 0x10($sp)
    /* 188D4 001188D4 2000AA7B */  lq         $t2, 0x20($sp)
    /* 188D8 001188D8 3000A4DB */  lqc2       $vf4, 0x30($sp)
    /* 188DC 001188DC 3C23E54B */  vmove.xyzw $vf5, $vf4
    /* 188E0 001188E0 2C21C44B */  vsub.xyz   $vf4, $vf4, $vf4
    /* 188E4 001188E4 3C23E94B */  vmove.xyzw $vf9, $vf4
    /* 188E8 001188E8 00202B48 */  qmfc2.ni   $t3, $vf4
    /* 188EC 001188EC 88642871 */  pextlw     $t4, $t1, $t0
    /* 188F0 001188F0 A86C2871 */  pextuw     $t5, $t1, $t0
    /* 188F4 001188F4 88746A71 */  pextlw     $t6, $t3, $t2
    /* 188F8 001188F8 A87C6A71 */  pextuw     $t7, $t3, $t2
    /* 188FC 001188FC 8943CC71 */  pcpyld     $t0, $t6, $t4
    /* 18900 00118900 A94B8E71 */  pcpyud     $t1, $t4, $t6
    /* 18904 00118904 8953ED71 */  pcpyld     $t2, $t7, $t5
    /* 18908 00118908 0030A848 */  qmtc2.ni   $t0, $vf6
    /* 1890C 0011890C 0038A948 */  qmtc2.ni   $t1, $vf7
    /* 18910 00118910 0040AA48 */  qmtc2.ni   $t2, $vf8
    /* 18914 00118914 BC31C54B */  vmulax.xyz $ACC, $vf6, $vf5x
    /* 18918 00118918 BD38C54B */  vmadday.xyz $ACC, $vf7, $vf5y
    /* 1891C 0011891C 0A41C54B */  vmaddz.xyz $vf4, $vf8, $vf5z
    /* 18920 00118920 2C49C44B */  vsub.xyz   $vf4, $vf9, $vf4
    /* 18924 00118924 0000887C */  sq         $t0, 0x0($a0)
    /* 18928 00118928 1000897C */  sq         $t1, 0x10($a0)
    /* 1892C 0011892C 20008A7C */  sq         $t2, 0x20($a0)
    /* 18930 00118930 300084F8 */  sqc2       $vf4, 0x30($a0)
    /* 18934 00118934 0800E003 */  jr         $ra
    /* 18938 00118938 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_00118818
    /* 1893C 0011893C 00000000 */  nop

.align 3
nonmatching func_00118940, 0xCC

glabel func_00118940
    /* 18940 00118940 2D18C000 */  daddu      $v1, $a2, $zero
    /* 18944 00118944 2D10E000 */  daddu      $v0, $a3, $zero
    /* 18948 00118948 4700004B */  vsubw.x    $vf1, $vf0, $vf0w
    /* 1894C 0011894C 0000B8D8 */  lqc2       $vf24, 0x0($a1)
    /* 18950 00118950 000079D8 */  lqc2       $vf25, 0x0($v1)
    /* 18954 00118954 00005AD8 */  lqc2       $vf26, 0x0($v0)
    /* 18958 00118958 18C6C14B */  vmulx.xyz  $vf24, $vf24, $vf1x
    /* 1895C 0011895C 58CEC14B */  vmulx.xyz  $vf25, $vf25, $vf1x
    /* 18960 00118960 98D6C14B */  vmulx.xyz  $vf26, $vf26, $vf1x
    /* 18964 00118964 AAC3D84B */  vmul.xyz   $vf14, $vf24, $vf24
    /* 18968 00118968 81730E4B */  vaddy.x    $vf14, $vf14, $vf14y
    /* 1896C 0011896C 82730E4B */  vaddz.x    $vf14, $vf14, $vf14z
    /* 18970 00118970 BE036E4A */  vrsqrt     $Q, $vf0w, $vf14x
    /* 18974 00118974 EACBD94B */  vmul.xyz   $vf15, $vf25, $vf25
    /* 18978 00118978 C17B0F4B */  vaddy.x    $vf15, $vf15, $vf15y
    /* 1897C 0011897C C27B0F4B */  vaddz.x    $vf15, $vf15, $vf15z
    /* 18980 00118980 BF03004A */  vwaitq
    /* 18984 00118984 1CC6C04B */  vmulq.xyz  $vf24, $vf24, $Q
    /* 18988 00118988 BE036F4A */  vrsqrt     $Q, $vf0w, $vf15x
    /* 1898C 0011898C 2AD4DA4B */  vmul.xyz   $vf16, $vf26, $vf26
    /* 18990 00118990 0184104B */  vaddy.x    $vf16, $vf16, $vf16y
    /* 18994 00118994 0284104B */  vaddz.x    $vf16, $vf16, $vf16z
    /* 18998 00118998 BF03004A */  vwaitq
    /* 1899C 0011899C 5CCEC04B */  vmulq.xyz  $vf25, $vf25, $Q
    /* 189A0 001189A0 BE03704A */  vrsqrt     $Q, $vf0w, $vf16x
    /* 189A4 001189A4 BF03004A */  vwaitq
    /* 189A8 001189A8 9CD6C04B */  vmulq.xyz  $vf26, $vf26, $Q
    /* 189AC 001189AC 3C03FB4B */  vmove.xyzw $vf27, $vf0
    /* 189B0 001189B0 3CC3EE4B */  vmove.xyzw $vf14, $vf24
    /* 189B4 001189B4 3CCBEF4B */  vmove.xyzw $vf15, $vf25
    /* 189B8 001189B8 3CD3F04B */  vmove.xyzw $vf16, $vf26
    /* 189BC 001189BC 3CDBF14B */  vmove.xyzw $vf17, $vf27
    /* 189C0 001189C0 6C00E04B */  vsub.xyzw  $vf1, $vf0, $vf0
    /* 189C4 001189C4 800B994A */  vaddx.y    $vf14, $vf1, $vf25x
    /* 189C8 001189C8 800B5A4A */  vaddx.z    $vf14, $vf1, $vf26x
    /* 189CC 001189CC 800B3B4A */  vaddx.w    $vf14, $vf1, $vf27x
    /* 189D0 001189D0 C10B184B */  vaddy.x    $vf15, $vf1, $vf24y
    /* 189D4 001189D4 C10B5A4A */  vaddy.z    $vf15, $vf1, $vf26y
    /* 189D8 001189D8 C10B3B4A */  vaddy.w    $vf15, $vf1, $vf27y
    /* 189DC 001189DC 020C184B */  vaddz.x    $vf16, $vf1, $vf24z
    /* 189E0 001189E0 020C994A */  vaddz.y    $vf16, $vf1, $vf25z
    /* 189E4 001189E4 020C3B4A */  vaddz.w    $vf16, $vf1, $vf27z
    /* 189E8 001189E8 430C184B */  vaddw.x    $vf17, $vf1, $vf24w
    /* 189EC 001189EC 430C994A */  vaddw.y    $vf17, $vf1, $vf25w
    /* 189F0 001189F0 430C5A4A */  vaddw.z    $vf17, $vf1, $vf26w
    /* 189F4 001189F4 00008EF8 */  sqc2       $vf14, 0x0($a0)
    /* 189F8 001189F8 10008FF8 */  sqc2       $vf15, 0x10($a0)
    /* 189FC 001189FC 200090F8 */  sqc2       $vf16, 0x20($a0)
    /* 18A00 00118A00 300091F8 */  sqc2       $vf17, 0x30($a0)
    /* 18A04 00118A04 0800E003 */  jr         $ra
    /* 18A08 00118A08 00000000 */   nop
endlabel func_00118940
    /* 18A0C 00118A0C 00000000 */  nop

.align 3
nonmatching func_00118A10, 0x34

glabel func_00118A10
    /* 18A10 00118A10 2D50C000 */  daddu      $t2, $a2, $zero
    /* 18A14 00118A14 2D18E000 */  daddu      $v1, $a3, $zero
    /* 18A18 00118A18 2D100001 */  daddu      $v0, $t0, $zero
    /* 18A1C 00118A1C 0000A678 */  lq         $a2, 0x0($a1)
    /* 18A20 00118A20 00004779 */  lq         $a3, 0x0($t2)
    /* 18A24 00118A24 00006878 */  lq         $t0, 0x0($v1)
    /* 18A28 00118A28 00004978 */  lq         $t1, 0x0($v0)
    /* 18A2C 00118A2C 0000867C */  sq         $a2, 0x0($a0)
    /* 18A30 00118A30 1000877C */  sq         $a3, 0x10($a0)
    /* 18A34 00118A34 2000887C */  sq         $t0, 0x20($a0)
    /* 18A38 00118A38 3000897C */  sq         $t1, 0x30($a0)
    /* 18A3C 00118A3C 0800E003 */  jr         $ra
    /* 18A40 00118A40 00000000 */   nop
endlabel func_00118A10
    /* 18A44 00118A44 00000000 */  nop
