.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118AA0, 0x14

glabel func_00118AA0
    /* 18AA0 00118AA0 3C04C14B */  vrnext.xyz $vf1, $R
    /* 18AA4 00118AA4 4708C04B */  vsubw.xyz  $vf1, $vf1, $vf0w
    /* 18AA8 00118AA8 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 18AAC 00118AAC 0800E003 */  jr         $ra
    /* 18AB0 00118AB0 00000000 */   nop
endlabel func_00118AA0
