.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00118A9C, 0x4

glabel func_00118A9C
    /* 18A9C 00118A9C 00000000 */  nop
endlabel func_00118A9C
