.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118A80, 0x1C

glabel func_00118A80
    /* 18A80 00118A80 3C04014B */  vrnext.x   $vf1, $R
    /* 18A84 00118A84 3C04814A */  vrnext.y   $vf1, $R
    /* 18A88 00118A88 3C04414A */  vrnext.z   $vf1, $R
    /* 18A8C 00118A8C 4708C04B */  vsubw.xyz  $vf1, $vf1, $vf0w
    /* 18A90 00118A90 000081F8 */  sqc2       $vf1, 0x0($a0)
    /* 18A94 00118A94 0800E003 */  jr         $ra
    /* 18A98 00118A98 00000000 */   nop
endlabel func_00118A80
