.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118A68, 0x18

glabel func_00118A68
    /* 18A68 00118A68 3C04014B */  vrnext.x   $vf1, $R
    /* 18A6C 00118A6C 4708004B */  vsubw.x    $vf1, $vf1, $vf0w
    /* 18A70 00118A70 00082748 */  qmfc2.ni   $a3, $vf1
    /* 18A74 00118A74 00008744 */  mtc1       $a3, $f0
    /* 18A78 00118A78 0800E003 */  jr         $ra
    /* 18A7C 00118A7C 00000000 */   nop
endlabel func_00118A68
