.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00118A48, 0x20

glabel func_00118A48
    /* 18A48 00118A48 00600644 */  mfc1       $a2, $f12
    /* 18A4C 00118A4C 0008A648 */  qmtc2.ni   $a2, $vf1
    /* 18A50 00118A50 8308004B */  vaddw.x    $vf2, $vf1, $vf0w
    /* 18A54 00118A54 6808014B */  vadd.x     $vf1, $vf1, $vf1
    /* 18A58 00118A58 3E14004A */  vrinit     $R, $vf2x
    /* 18A5C 00118A5C 3F0C004A */  vrxor      $R, $vf1x
    /* 18A60 00118A60 0800E003 */  jr         $ra
    /* 18A64 00118A64 00000000 */   nop
endlabel func_00118A48
