.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00118F94, 0x4

glabel func_00118F94
    /* 18F94 00118F94 00000000 */  nop
endlabel func_00118F94
