.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0011BF5C, 0x4

glabel func_0011BF5C
    /* 1BF5C 0011BF5C 00000000 */  nop
endlabel func_0011BF5C
