.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0012FD4C, 0x4

glabel func_0012FD4C
    /* 2FD4C 0012FD4C 00000000 */  nop
endlabel func_0012FD4C
