.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001335CC, 0x4

glabel func_001335CC
    /* 335CC 001335CC 00000000 */  nop
endlabel func_001335CC
