.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00137F04, 0x4

glabel func_00137F04
    /* 37F04 00137F04 00000000 */  nop
endlabel func_00137F04
