.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001380A8, 0x4

glabel func_001380A8
    /* 380A8 001380A8 1000BD27 */  addiu      $sp, $sp, 0x10
endlabel func_001380A8
    /* 380AC 001380AC 00000000 */  nop
