.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00138138, 0x4

glabel func_00138138
    /* 38138 00138138 1000BD27 */  addiu      $sp, $sp, 0x10
endlabel func_00138138
    /* 3813C 0013813C 00000000 */  nop
