.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013B744, 0x4

glabel func_0013B744
    /* 3B744 0013B744 00000000 */  nop
endlabel func_0013B744
