.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013CC6C, 0x4

glabel func_0013CC6C
    /* 3CC6C 0013CC6C 00000000 */  nop
endlabel func_0013CC6C
