.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013DD9C, 0x4

glabel func_0013DD9C
    /* 3DD9C 0013DD9C 00000000 */  nop
endlabel func_0013DD9C
