.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013E4CC, 0x4

glabel func_0013E4CC
    /* 3E4CC 0013E4CC 00000000 */  nop
endlabel func_0013E4CC
