.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013ED74, 0x4

glabel func_0013ED74
    /* 3ED74 0013ED74 00000000 */  nop
endlabel func_0013ED74
