.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013F7A4, 0x4

glabel func_0013F7A4
    /* 3F7A4 0013F7A4 00000000 */  nop
endlabel func_0013F7A4
