.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00140B6C, 0x4

glabel func_00140B6C
    /* 40B6C 00140B6C 00000000 */  nop
endlabel func_00140B6C
