.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00140F54, 0x4

glabel func_00140F54
    /* 40F54 00140F54 00000000 */  nop
endlabel func_00140F54
