.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00141034, 0x4

glabel func_00141034
    /* 41034 00141034 00000000 */  nop
endlabel func_00141034
