.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0014B044, 0x4

glabel func_0014B044
    /* 4B044 0014B044 00000000 */  nop
endlabel func_0014B044
