.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0014B244, 0x4

glabel func_0014B244
    /* 4B244 0014B244 00000000 */  nop
endlabel func_0014B244
