.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0014B764, 0x4

glabel func_0014B764
    /* 4B764 0014B764 00000000 */  nop
endlabel func_0014B764
