.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0014B854, 0x4

glabel func_0014B854
    /* 4B854 0014B854 00000000 */  nop
endlabel func_0014B854
