.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0015F2D4, 0x4

glabel func_0015F2D4
    /* 5F2D4 0015F2D4 00000000 */  nop
endlabel func_0015F2D4
