.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0015F6EC, 0x4

glabel func_0015F6EC
    /* 5F6EC 0015F6EC 00000000 */  nop
endlabel func_0015F6EC
