.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00165FB4, 0x4

glabel func_00165FB4
    /* 65FB4 00165FB4 00000000 */  nop
endlabel func_00165FB4
