.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00168534, 0x4

glabel func_00168534
    /* 68534 00168534 00000000 */  nop
endlabel func_00168534
