.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00168A3C, 0x4

glabel func_00168A3C
    /* 68A3C 00168A3C 00000000 */  nop
endlabel func_00168A3C
