.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00168BCC, 0x4

glabel func_00168BCC
    /* 68BCC 00168BCC 00000000 */  nop
endlabel func_00168BCC
