.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0016A154, 0x4

glabel func_0016A154
    /* 6A154 0016A154 00000000 */  nop
endlabel func_0016A154
