.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0016A29C, 0x4

glabel func_0016A29C
    /* 6A29C 0016A29C 00000000 */  nop
endlabel func_0016A29C
