.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0016A2F4, 0x4

glabel func_0016A2F4
    /* 6A2F4 0016A2F4 00000000 */  nop
endlabel func_0016A2F4
