.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00175684, 0x4

glabel func_00175684
    /* 75684 00175684 00000000 */  nop
endlabel func_00175684
