.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00176198, 0x20

glabel func_00176198
    /* 76198 00176198 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 7619C 0017619C 1000BFFF */  sd         $ra, 0x10($sp)
    /* 761A0 001761A0 0000A4AF */  sw         $a0, 0x0($sp)
    /* 761A4 001761A4 EA28050C */  jal        func_0014A3A8
    /* 761A8 001761A8 00000000 */   nop
    /* 761AC 001761AC 1000BFDF */  ld         $ra, 0x10($sp)
    /* 761B0 001761B0 0800E003 */  jr         $ra
    /* 761B4 001761B4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00176198
