.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001763F4, 0x4

glabel func_001763F4
    /* 763F4 001763F4 00000000 */  nop
endlabel func_001763F4
