.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017B394, 0x4

glabel func_0017B394
    /* 7B394 0017B394 00000000 */  nop
endlabel func_0017B394
