.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017CA54, 0x4

glabel func_0017CA54
    /* 7CA54 0017CA54 00000000 */  nop
endlabel func_0017CA54
