.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017E9FC, 0x4

glabel func_0017E9FC
    /* 7E9FC 0017E9FC 00000000 */  nop
endlabel func_0017E9FC
