.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00181FAC, 0x4

glabel func_00181FAC
    /* 81FAC 00181FAC 00000000 */  nop
endlabel func_00181FAC
