.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001872B4, 0x4

glabel func_001872B4
    /* 872B4 001872B4 00000000 */  nop
endlabel func_001872B4
