.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0018794C, 0x4

glabel func_0018794C
    /* 8794C 0018794C 00000000 */  nop
endlabel func_0018794C
