.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001903DC, 0x4

glabel func_001903DC
    /* 903DC 001903DC 00000000 */  nop
endlabel func_001903DC
