.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00193844, 0x4

glabel func_00193844
    /* 93844 00193844 00000000 */  nop
endlabel func_00193844
