.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00194394, 0x4

glabel func_00194394
    /* 94394 00194394 00000000 */  nop
endlabel func_00194394
