.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001986A8, 0x30

glabel func_001986A8
    /* 986A8 001986A8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 986AC 001986AC 1000A5D8 */  lqc2       $vf5, 0x10($a1)
    /* 986B0 001986B0 2000A6D8 */  lqc2       $vf6, 0x20($a1)
    /* 986B4 001986B4 3000A7D8 */  lqc2       $vf7, 0x30($a1)
    /* 986B8 001986B8 0000C8D8 */  lqc2       $vf8, 0x0($a2)
    /* 986BC 001986BC BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 986C0 001986C0 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 986C4 001986C4 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 986C8 001986C8 4B3AE04B */  vmaddw.xyzw $vf9, $vf7, $vf0w
    /* 986CC 001986CC 000089F8 */  sqc2       $vf9, 0x0($a0)
    /* 986D0 001986D0 0800E003 */  jr         $ra
    /* 986D4 001986D4 00000000 */   nop
endlabel func_001986A8
