.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00199790, 0x28

glabel func_00199790
    /* 99790 00199790 0000C8D8 */  lqc2       $vf8, 0x0($a2)
    /* 99794 00199794 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 99798 00199798 1000A5D8 */  lqc2       $vf5, 0x10($a1)
    /* 9979C 0019979C 2000A6D8 */  lqc2       $vf6, 0x20($a1)
    /* 997A0 001997A0 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 997A4 001997A4 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 997A8 001997A8 0A33E84B */  vmaddz.xyzw $vf12, $vf6, $vf8z
    /* 997AC 001997AC 00008CF8 */  sqc2       $vf12, 0x0($a0)
    /* 997B0 001997B0 0800E003 */  jr         $ra
    /* 997B4 001997B4 00000000 */   nop
endlabel func_00199790
