.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0019E224, 0x4

glabel func_0019E224
    /* 9E224 0019E224 00000000 */  nop
endlabel func_0019E224
