.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0019F52C, 0x4

glabel func_0019F52C
    /* 9F52C 0019F52C 00000000 */  nop
endlabel func_0019F52C
