.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001A008C, 0x4

glabel func_001A008C
    /* A008C 001A008C 00000000 */  nop
endlabel func_001A008C
