.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001A0024, 0x4

glabel func_001A0024
    /* A0024 001A0024 00000000 */  nop
endlabel func_001A0024
