.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001A0034, 0x4

glabel func_001A0034
    /* A0034 001A0034 00000000 */  nop
endlabel func_001A0034
