.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001A2D74, 0x4

glabel func_001A2D74
    /* A2D74 001A2D74 00000000 */  nop
endlabel func_001A2D74
