.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001A6DFC, 0x4

glabel func_001A6DFC
    /* A6DFC 001A6DFC 00000000 */  nop
endlabel func_001A6DFC
