.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001A6DE0, 0x1C

glabel func_001A6DE0
    /* A6DE0 001A6DE0 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* A6DE4 001A6DE4 4000A8FF */  sd         $t0, 0x40($sp)
    /* A6DE8 001A6DE8 4800A9FF */  sd         $t1, 0x48($sp)
    /* A6DEC 001A6DEC 5000AAFF */  sd         $t2, 0x50($sp)
    /* A6DF0 001A6DF0 5800ABFF */  sd         $t3, 0x58($sp)
    /* A6DF4 001A6DF4 0800E003 */  jr         $ra
    /* A6DF8 001A6DF8 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_001A6DE0
