.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001A7834, 0x4

glabel func_001A7834
    /* A7834 001A7834 00000000 */  nop
endlabel func_001A7834
