.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001A9F1C, 0x4

glabel func_001A9F1C
    /* A9F1C 001A9F1C 00000000 */  nop
endlabel func_001A9F1C
