.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AA254, 0x4

glabel func_001AA254
    /* AA254 001AA254 00000000 */  nop
endlabel func_001AA254
