.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001ADB84, 0x4

glabel func_001ADB84
    /* ADB84 001ADB84 00000000 */  nop
endlabel func_001ADB84
