.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AE20C, 0x4

glabel func_001AE20C
    /* AE20C 001AE20C 00000000 */  nop
endlabel func_001AE20C
