.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AE3AC, 0x4

glabel func_001AE3AC
    /* AE3AC 001AE3AC 00000000 */  nop
endlabel func_001AE3AC
