.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001B0A54, 0x4

glabel func_001B0A54
    /* B0A54 001B0A54 00000000 */  nop
endlabel func_001B0A54
