.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001B718C, 0x4

glabel func_001B718C
    /* B718C 001B718C 00000000 */  nop
endlabel func_001B718C
