.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001BA7BC, 0x4

glabel func_001BA7BC
    /* BA7BC 001BA7BC 00000000 */  nop
endlabel func_001BA7BC
