.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001BB7FC, 0x4

glabel func_001BB7FC
    /* BB7FC 001BB7FC 00000000 */  nop
endlabel func_001BB7FC
