.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001C068C, 0x4

glabel func_001C068C
    /* C068C 001C068C 00000000 */  nop
endlabel func_001C068C
