.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001C34B4, 0x4

glabel func_001C34B4
    /* C34B4 001C34B4 00000000 */  nop
endlabel func_001C34B4
