.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001C8DE8, 0x20

glabel func_001C8DE8
    /* C8DE8 001C8DE8 00600844 */  mfc1       $t0, $f12
    /* C8DEC 001C8DEC 0020A848 */  qmtc2.ni   $t0, $vf4
    /* C8DF0 001C8DF0 BE03644A */  vrsqrt     $Q, $vf0w, $vf4x
    /* C8DF4 001C8DF4 BF03004A */  vwaitq
    /* C8DF8 001C8DF8 00B04248 */  cfc2.ni    $v0, $vi22
    /* C8DFC 001C8DFC 00008244 */  mtc1       $v0, $f0
    /* C8E00 001C8E00 0800E003 */  jr         $ra
    /* C8E04 001C8E04 00000000 */   nop
endlabel func_001C8DE8
