.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001C8E2C, 0x4

glabel func_001C8E2C
    /* C8E2C 001C8E2C 00000000 */  nop
endlabel func_001C8E2C
