.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001C8E30, 0x24

glabel func_001C8E30
    /* C8E30 001C8E30 000084D8 */  lqc2       $vf4, 0x0($a0)
    /* C8E34 001C8E34 2A21444B */  vmul.xz    $vf4, $vf4, $vf4
    /* C8E38 001C8E38 0221044B */  vaddz.x    $vf4, $vf4, $vf4z
    /* C8E3C 001C8E3C BE03644A */  vrsqrt     $Q, $vf0w, $vf4x
    /* C8E40 001C8E40 BF03004A */  vwaitq
    /* C8E44 001C8E44 00B04248 */  cfc2.ni    $v0, $vi22
    /* C8E48 001C8E48 00008244 */  mtc1       $v0, $f0
    /* C8E4C 001C8E4C 0800E003 */  jr         $ra
    /* C8E50 001C8E50 00000000 */   nop
endlabel func_001C8E30
