.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001C8E58, 0x1C

glabel func_001C8E58
    /* C8E58 001C8E58 000084D8 */  lqc2       $vf4, 0x0($a0)
    /* C8E5C 001C8E5C 2A21444B */  vmul.xz    $vf4, $vf4, $vf4
    /* C8E60 001C8E60 0221044B */  vaddz.x    $vf4, $vf4, $vf4z
    /* C8E64 001C8E64 00202248 */  qmfc2.ni   $v0, $vf4
    /* C8E68 001C8E68 00008244 */  mtc1       $v0, $f0
    /* C8E6C 001C8E6C 0800E003 */  jr         $ra
    /* C8E70 001C8E70 00000000 */   nop
endlabel func_001C8E58
