.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001C8E78, 0x34

glabel func_001C8E78
    /* C8E78 001C8E78 0000A1D8 */  lqc2       $vf1, 0x0($a1)
    /* C8E7C 001C8E7C 0000C2D8 */  lqc2       $vf2, 0x0($a2)
    /* C8E80 001C8E80 2C09E24B */  vsub.xyzw  $vf4, $vf1, $vf2
    /* C8E84 001C8E84 EA20C44B */  vmul.xyz   $vf3, $vf4, $vf4
    /* C8E88 001C8E88 C118034B */  vaddy.x    $vf3, $vf3, $vf3y
    /* C8E8C 001C8E8C C218034B */  vaddz.x    $vf3, $vf3, $vf3z
    /* C8E90 001C8E90 BE03634A */  vrsqrt     $Q, $vf0w, $vf3x
    /* C8E94 001C8E94 000084F8 */  sqc2       $vf4, 0x0($a0)
    /* C8E98 001C8E98 BF03004A */  vwaitq
    /* C8E9C 001C8E9C 00B04248 */  cfc2.ni    $v0, $vi22
    /* C8EA0 001C8EA0 00008244 */  mtc1       $v0, $f0
    /* C8EA4 001C8EA4 0800E003 */  jr         $ra
    /* C8EA8 001C8EA8 00000000 */   nop
endlabel func_001C8E78
