.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001C8E08, 0x24

glabel func_001C8E08
    /* C8E08 001C8E08 000084D8 */  lqc2       $vf4, 0x0($a0)
    /* C8E0C 001C8E0C 2A21444B */  vmul.xz    $vf4, $vf4, $vf4
    /* C8E10 001C8E10 0221044B */  vaddz.x    $vf4, $vf4, $vf4z
    /* C8E14 001C8E14 BD03044A */  .word      0x4A0403BD                    # vsqrt      $Q, $vf4x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* C8E18 001C8E18 BF03004A */  vwaitq
    /* C8E1C 001C8E1C 00B04248 */  cfc2.ni    $v0, $vi22
    /* C8E20 001C8E20 00008244 */  mtc1       $v0, $f0
    /* C8E24 001C8E24 0800E003 */  jr         $ra
    /* C8E28 001C8E28 00000000 */   nop
endlabel func_001C8E08
