.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001C8EAC, 0x4

glabel func_001C8EAC
    /* C8EAC 001C8EAC 00000000 */  nop
endlabel func_001C8EAC
