.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001C8ED8, 0x1C

glabel func_001C8ED8
    /* C8ED8 001C8ED8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* C8EDC 001C8EDC 00600844 */  mfc1       $t0, $f12
    /* C8EE0 001C8EE0 0028A848 */  qmtc2.ni   $t0, $vf5
    /* C8EE4 001C8EE4 1821454B */  vmulx.xz   $vf4, $vf4, $vf5x
    /* C8EE8 001C8EE8 000084F8 */  sqc2       $vf4, 0x0($a0)
    /* C8EEC 001C8EEC 0800E003 */  jr         $ra
    /* C8EF0 001C8EF0 00000000 */   nop
endlabel func_001C8ED8
