.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001C8EB0, 0x24

glabel func_001C8EB0
    /* C8EB0 001C8EB0 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* C8EB4 001C8EB4 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* C8EB8 001C8EB8 00600844 */  mfc1       $t0, $f12
    /* C8EBC 001C8EBC 0030A848 */  qmtc2.ni   $t0, $vf6
    /* C8EC0 001C8EC0 5829C64B */  vmulx.xyz  $vf5, $vf5, $vf6x
    /* C8EC4 001C8EC4 2821C54B */  vadd.xyz   $vf4, $vf4, $vf5
    /* C8EC8 001C8EC8 000084F8 */  sqc2       $vf4, 0x0($a0)
    /* C8ECC 001C8ECC 0800E003 */  jr         $ra
    /* C8ED0 001C8ED0 00000000 */   nop
endlabel func_001C8EB0
