.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001CE6EC, 0x4

glabel func_001CE6EC
    /* CE6EC 001CE6EC 00000000 */  nop
endlabel func_001CE6EC
