.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001CEC2C, 0x4

glabel func_001CEC2C
    /* CEC2C 001CEC2C 00000000 */  nop
endlabel func_001CEC2C
