.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001D4DA4, 0x4

glabel func_001D4DA4
    /* D4DA4 001D4DA4 00000000 */  nop
endlabel func_001D4DA4
