.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001E994C, 0x4

glabel func_001E994C
    /* E994C 001E994C 00000000 */  nop
endlabel func_001E994C
