.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001EBA14, 0x4

glabel func_001EBA14
    /* EBA14 001EBA14 00000000 */  nop
endlabel func_001EBA14
