.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001F231C, 0x4

glabel func_001F231C
    /* F231C 001F231C 00000000 */  nop
endlabel func_001F231C
