.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001F5604, 0x4

glabel func_001F5604
    /* F5604 001F5604 00000000 */  nop
endlabel func_001F5604
