.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001FAA3C, 0x4

glabel func_001FAA3C
    /* FAA3C 001FAA3C 00000000 */  nop
endlabel func_001FAA3C
