.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001FC4BC, 0x4

glabel func_001FC4BC
    /* FC4BC 001FC4BC 00000000 */  nop
endlabel func_001FC4BC
