.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00205A94, 0x4

glabel func_00205A94
    /* 105A94 00205A94 00000000 */  nop
endlabel func_00205A94
