.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0021F684, 0x4

glabel func_0021F684
    /* 11F684 0021F684 00000000 */  nop
endlabel func_0021F684
