.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00229DDC, 0x4

glabel func_00229DDC
    /* 129DDC 00229DDC 00000000 */  nop
endlabel func_00229DDC
