.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00229D2C, 0x4

glabel func_00229D2C
    /* 129D2C 00229D2C 00000000 */  nop
endlabel func_00229D2C
