.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0023AD54, 0x4

glabel func_0023AD54
    /* 13AD54 0023AD54 00000000 */  nop
endlabel func_0023AD54
