.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0023F774, 0x4

glabel func_0023F774
    /* 13F774 0023F774 00000000 */  nop
endlabel func_0023F774
