.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_00240960, 0xC0

glabel func_00240960
    /* 140960 00240960 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 140964 00240964 1000B1FF */  sd         $s1, 0x10($sp)
    /* 140968 00240968 2D888000 */  daddu      $s1, $a0, $zero
    /* 14096C 0024096C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 140970 00240970 2000BFFF */  sd         $ra, 0x20($sp)
    /* 140974 00240974 9006040C */  jal        func_00101A40
    /* 140978 00240978 05001024 */   addiu     $s0, $zero, 0x5
    /* 14097C 0024097C 0010063C */  lui        $a2, (0x1000F520 >> 16)
    /* 140980 00240980 0100073C */  lui        $a3, (0x10000 >> 16)
    /* 140984 00240984 20F5C634 */  ori        $a2, $a2, (0x1000F520 & 0xFFFF)
    /* 140988 00240988 0010053C */  lui        $a1, (0x1000F590 >> 16)
    /* 14098C 0024098C 0000C28C */  lw         $v0, 0x0($a2)
    /* 140990 00240990 90F5A534 */  ori        $a1, $a1, (0x1000F590 & 0xFFFF)
    /* 140994 00240994 0010033C */  lui        $v1, (0x1000B400 >> 16)
    /* 140998 00240998 FEFF043C */  lui        $a0, (0xFFFEFFFF >> 16)
    /* 14099C 0024099C 25104700 */  or         $v0, $v0, $a3
    /* 1409A0 002409A0 00B46334 */  ori        $v1, $v1, (0x1000B400 & 0xFFFF)
    /* 1409A4 002409A4 0000A2AC */  sw         $v0, 0x0($a1)
    /* 1409A8 002409A8 FFFF8434 */  ori        $a0, $a0, (0xFFFEFFFF & 0xFFFF)
    /* 1409AC 002409AC 000070AC */  sw         $s0, 0x0($v1)
    /* 1409B0 002409B0 0000C28C */  lw         $v0, 0x0($a2)
    /* 1409B4 002409B4 24104400 */  and        $v0, $v0, $a0
    /* 1409B8 002409B8 0000A2AC */  sw         $v0, 0x0($a1)
    /* 1409BC 002409BC 0F000000 */  sync
    /* 1409C0 002409C0 38000042 */  ei /* handwritten instruction */
    /* 1409C4 002409C4 0010033C */  lui        $v1, (0x1000B420 >> 16)
    /* 1409C8 002409C8 0010043C */  lui        $a0, (0x1000B410 >> 16)
    /* 1409CC 002409CC 20B46334 */  ori        $v1, $v1, (0x1000B420 & 0xFFFF)
    /* 1409D0 002409D0 10B48434 */  ori        $a0, $a0, (0x1000B410 & 0xFFFF)
    /* 1409D4 002409D4 000060AC */  sw         $zero, 0x0($v1)
    /* 1409D8 002409D8 0010023C */  lui        $v0, (0x1000B430 >> 16)
    /* 1409DC 002409DC 000080AC */  sw         $zero, 0x0($a0)
    /* 1409E0 002409E0 30B44234 */  ori        $v0, $v0, (0x1000B430 & 0xFFFF)
    /* 1409E4 002409E4 000040AC */  sw         $zero, 0x0($v0)
    /* 1409E8 002409E8 60002382 */  lb         $v1, 0x60($s1)
    /* 1409EC 002409EC 04006050 */  beql       $v1, $zero, .L00240A00
    /* 1409F0 002409F0 600020A2 */   sb        $zero, 0x60($s1)
    /* 1409F4 002409F4 4C01040C */  jal        func_00100530
    /* 1409F8 002409F8 4000248E */   lw        $a0, 0x40($s1)
    /* 1409FC 002409FC 600020A2 */  sb         $zero, 0x60($s1)
.align 2
  .L00240A00:
    /* 140A00 00240A00 4AFE080C */  jal        func_0023F928
    /* 140A04 00240A04 2D202002 */   daddu     $a0, $s1, $zero
    /* 140A08 00240A08 2000BFDF */  ld         $ra, 0x20($sp)
    /* 140A0C 00240A0C 01000224 */  addiu      $v0, $zero, 0x1
    /* 140A10 00240A10 1000B1DF */  ld         $s1, 0x10($sp)
    /* 140A14 00240A14 0000B0DF */  ld         $s0, 0x0($sp)
    /* 140A18 00240A18 0800E003 */  jr         $ra
    /* 140A1C 00240A1C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00240960
