.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002438E4, 0x4

glabel func_002438E4
    /* 1438E4 002438E4 00000000 */  nop
endlabel func_002438E4

/* Handwritten function */
nonmatching func_002438E8, 0x44

glabel func_002438E8
    /* 1438E8 002438E8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 1438EC 002438EC 1000A5D8 */  lqc2       $vf5, 0x10($a1)
    /* 1438F0 002438F0 2000A6D8 */  lqc2       $vf6, 0x20($a1)
    /* 1438F4 002438F4 3000A7D8 */  lqc2       $vf7, 0x30($a1)
    /* 1438F8 002438F8 04000724 */  addiu      $a3, $zero, 0x4
.align 2
  .L002438FC:
    /* 1438FC 002438FC 0000C8D8 */  lqc2       $vf8, 0x0($a2)
    /* 143900 00243900 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 143904 00243904 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 143908 00243908 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 14390C 0024390C 4B3AE84B */  vmaddw.xyzw $vf9, $vf7, $vf8w
    /* 143910 00243910 000089F8 */  sqc2       $vf9, 0x0($a0)
    /* 143914 00243914 FFFFE720 */  addi       $a3, $a3, -0x1 /* handwritten instruction */
    /* 143918 00243918 1000C620 */  addi       $a2, $a2, 0x10 /* handwritten instruction */
    /* 14391C 0024391C F7FF0714 */  bne        $zero, $a3, .L002438FC
    /* 143920 00243920 10008420 */   addi      $a0, $a0, 0x10 /* handwritten instruction */
    /* 143924 00243924 0800E003 */  jr         $ra
    /* 143928 00243928 00000000 */   nop
endlabel func_002438E8
    /* 14392C 0024392C 00000000 */  nop
