.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_002438B8, 0x2C

glabel func_002438B8
    /* 1438B8 002438B8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 1438BC 002438BC 1000A5D8 */  lqc2       $vf5, 0x10($a1)
    /* 1438C0 002438C0 2000A6D8 */  lqc2       $vf6, 0x20($a1)
    /* 1438C4 002438C4 3000A7D8 */  lqc2       $vf7, 0x30($a1)
    /* 1438C8 002438C8 0000C8D8 */  lqc2       $vf8, 0x0($a2)
    /* 1438CC 002438CC BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 1438D0 002438D0 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 1438D4 002438D4 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 1438D8 002438D8 4B3AE84B */  vmaddw.xyzw $vf9, $vf7, $vf8w
    /* 1438DC 002438DC 0800E003 */  jr         $ra
    /* 1438E0 002438E0 000089F8 */   sqc2      $vf9, 0x0($a0)
endlabel func_002438B8
