.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002439F4, 0x4

glabel func_002439F4
    /* 1439F4 002439F4 00000000 */  nop
endlabel func_002439F4

nonmatching func_002439F8, 0x6C

glabel func_002439F8
    /* 1439F8 002439F8 0000A878 */  lq         $t0, 0x0($a1)
    /* 1439FC 002439FC 1000A978 */  lq         $t1, 0x10($a1)
    /* 143A00 00243A00 2000AA78 */  lq         $t2, 0x20($a1)
    /* 143A04 00243A04 3000A4D8 */  lqc2       $vf4, 0x30($a1)
    /* 143A08 00243A08 3C23E54B */  vmove.xyzw $vf5, $vf4
    /* 143A0C 00243A0C 2C21C44B */  vsub.xyz   $vf4, $vf4, $vf4
    /* 143A10 00243A10 3C23E94B */  vmove.xyzw $vf9, $vf4
    /* 143A14 00243A14 00202B48 */  qmfc2.ni   $t3, $vf4
    /* 143A18 00243A18 88642871 */  pextlw     $t4, $t1, $t0
    /* 143A1C 00243A1C A86C2871 */  pextuw     $t5, $t1, $t0
    /* 143A20 00243A20 88746A71 */  pextlw     $t6, $t3, $t2
    /* 143A24 00243A24 A87C6A71 */  pextuw     $t7, $t3, $t2
    /* 143A28 00243A28 8943CC71 */  pcpyld     $t0, $t6, $t4
    /* 143A2C 00243A2C A94B8E71 */  pcpyud     $t1, $t4, $t6
    /* 143A30 00243A30 8953ED71 */  pcpyld     $t2, $t7, $t5
    /* 143A34 00243A34 0030A848 */  qmtc2.ni   $t0, $vf6
    /* 143A38 00243A38 0038A948 */  qmtc2.ni   $t1, $vf7
    /* 143A3C 00243A3C 0040AA48 */  qmtc2.ni   $t2, $vf8
    /* 143A40 00243A40 BC31C54B */  vmulax.xyz $ACC, $vf6, $vf5x
    /* 143A44 00243A44 BD38C54B */  vmadday.xyz $ACC, $vf7, $vf5y
    /* 143A48 00243A48 0A41C54B */  vmaddz.xyz $vf4, $vf8, $vf5z
    /* 143A4C 00243A4C 2C49C44B */  vsub.xyz   $vf4, $vf9, $vf4
    /* 143A50 00243A50 0000887C */  sq         $t0, 0x0($a0)
    /* 143A54 00243A54 1000897C */  sq         $t1, 0x10($a0)
    /* 143A58 00243A58 20008A7C */  sq         $t2, 0x20($a0)
    /* 143A5C 00243A5C 0800E003 */  jr         $ra
    /* 143A60 00243A60 300084F8 */   sqc2      $vf4, 0x30($a0)
endlabel func_002439F8
    /* 143A64 00243A64 00000000 */  nop
