.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243950, 0x24

glabel func_00243950
    /* 143950 00243950 000084D8 */  lqc2       $vf4, 0x0($a0)
    /* 143954 00243954 0000A5D8 */  lqc2       $vf5, 0x0($a1)
    /* 143958 00243958 6A21C54B */  vmul.xyz   $vf5, $vf4, $vf5
    /* 14395C 0024395C 4129054B */  vaddy.x    $vf5, $vf5, $vf5y
    /* 143960 00243960 4229054B */  vaddz.x    $vf5, $vf5, $vf5z
    /* 143964 00243964 00282248 */  qmfc2.ni   $v0, $vf5
    /* 143968 00243968 00008244 */  mtc1       $v0, $f0
    /* 14396C 0024396C 0800E003 */  jr         $ra
    /* 143970 00243970 00000000 */   nop
endlabel func_00243950
