.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243930, 0x1C

glabel func_00243930
    /* 143930 00243930 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143934 00243934 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 143938 00243938 FE22C54B */  vopmula.xyz $ACC, $vf4, $vf5
    /* 14393C 0024393C AE29C44B */  vopmsub.xyz $vf6, $vf5, $vf4
    /* 143940 00243940 AC31264A */  vsub.w     $vf6, $vf6, $vf6
    /* 143944 00243944 0800E003 */  jr         $ra
    /* 143948 00243948 000086F8 */   sqc2      $vf6, 0x0($a0)
endlabel func_00243930
