.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243A68, 0x20

glabel func_00243A68
    /* 143A68 00243A68 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143A6C 00243A6C 00600844 */  mfc1       $t0, $f12
    /* 143A70 00243A70 0028A848 */  qmtc2.ni   $t0, $vf5
    /* 143A74 00243A74 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 143A78 00243A78 BF03004A */  vwaitq
    /* 143A7C 00243A7C 1C21E04B */  vmulq.xyzw $vf4, $vf4, $Q
    /* 143A80 00243A80 0800E003 */  jr         $ra
    /* 143A84 00243A84 000084F8 */   sqc2      $vf4, 0x0($a0)
endlabel func_00243A68
