.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243AA8, 0x28

glabel func_00243AA8
    /* 143AA8 00243AA8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143AAC 00243AAC 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 143AB0 00243AB0 00600844 */  mfc1       $t0, $f12
    /* 143AB4 00243AB4 0030A848 */  qmtc2.ni   $t0, $vf6
    /* 143AB8 00243AB8 C301004B */  vaddw.x    $vf7, $vf0, $vf0w
    /* 143ABC 00243ABC 2C3A064B */  vsub.x     $vf8, $vf7, $vf6
    /* 143AC0 00243AC0 BC21E64B */  vmulax.xyzw $ACC, $vf4, $vf6x
    /* 143AC4 00243AC4 482AE84B */  vmaddx.xyzw $vf9, $vf5, $vf8x
    /* 143AC8 00243AC8 0800E003 */  jr         $ra
    /* 143ACC 00243ACC 000089F8 */   sqc2      $vf9, 0x0($a0)
endlabel func_00243AA8
