.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243AE8, 0x14

glabel func_00243AE8
    /* 143AE8 00243AE8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143AEC 00243AEC 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 143AF0 00243AF0 AC21E54B */  vsub.xyzw  $vf6, $vf4, $vf5
    /* 143AF4 00243AF4 0800E003 */  jr         $ra
    /* 143AF8 00243AF8 000086F8 */   sqc2      $vf6, 0x0($a0)
endlabel func_00243AE8
