.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243AD0, 0x14

glabel func_00243AD0
    /* 143AD0 00243AD0 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143AD4 00243AD4 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 143AD8 00243AD8 A821E54B */  vadd.xyzw  $vf6, $vf4, $vf5
    /* 143ADC 00243ADC 0800E003 */  jr         $ra
    /* 143AE0 00243AE0 000086F8 */   sqc2      $vf6, 0x0($a0)
endlabel func_00243AD0
