.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243A88, 0x20

glabel func_00243A88
    /* 143A88 00243A88 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143A8C 00243A8C 00600844 */  mfc1       $t0, $f12
    /* 143A90 00243A90 0028A848 */  qmtc2.ni   $t0, $vf5
    /* 143A94 00243A94 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 143A98 00243A98 BF03004A */  vwaitq
    /* 143A9C 00243A9C 1C21C04B */  vmulq.xyz  $vf4, $vf4, $Q
    /* 143AA0 00243AA0 0800E003 */  jr         $ra
    /* 143AA4 00243AA4 000084F8 */   sqc2      $vf4, 0x0($a0)
endlabel func_00243A88
