.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243B00, 0x14

glabel func_00243B00
    /* 143B00 00243B00 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143B04 00243B04 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 143B08 00243B08 AA21E54B */  vmul.xyzw  $vf6, $vf4, $vf5
    /* 143B0C 00243B0C 0800E003 */  jr         $ra
    /* 143B10 00243B10 000086F8 */   sqc2      $vf6, 0x0($a0)
endlabel func_00243B00
