.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243BA8, 0x10

glabel func_00243BA8
    /* 143BA8 00243BA8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143BAC 00243BAC 7C21E54B */  vftoi0.xyzw $vf5, $vf4
    /* 143BB0 00243BB0 0800E003 */  jr         $ra
    /* 143BB4 00243BB4 000085F8 */   sqc2      $vf5, 0x0($a0)
endlabel func_00243BA8
