.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243BD8, 0x28

glabel func_00243BD8
    /* 143BD8 00243BD8 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 143BDC 00243BDC 2821204A */  vadd.w     $vf4, $vf4, $vf0
    /* 143BE0 00243BE0 3D23E54B */  vmr32.xyzw $vf5, $vf4
    /* 143BE4 00243BE4 3D2BE64B */  vmr32.xyzw $vf6, $vf5
    /* 143BE8 00243BE8 3D33E74B */  vmr32.xyzw $vf7, $vf6
    /* 143BEC 00243BEC 300084F8 */  sqc2       $vf4, 0x30($a0)
    /* 143BF0 00243BF0 200085F8 */  sqc2       $vf5, 0x20($a0)
    /* 143BF4 00243BF4 100086F8 */  sqc2       $vf6, 0x10($a0)
    /* 143BF8 00243BF8 0800E003 */  jr         $ra
    /* 143BFC 00243BFC 000087F8 */   sqc2      $vf7, 0x0($a0)
endlabel func_00243BD8
