.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243B98, 0x10

glabel func_00243B98
    /* 143B98 00243B98 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143B9C 00243B9C 7D21E54B */  vftoi4.xyzw $vf5, $vf4
    /* 143BA0 00243BA0 0800E003 */  jr         $ra
    /* 143BA4 00243BA4 000085F8 */   sqc2      $vf5, 0x0($a0)
endlabel func_00243B98
