.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243B30, 0x2C

glabel func_00243B30
    /* 143B30 00243B30 0000C4D8 */  lqc2       $vf4, 0x0($a2)
    /* 143B34 00243B34 3000A5D8 */  lqc2       $vf5, 0x30($a1)
    /* 143B38 00243B38 0000A778 */  lq         $a3, 0x0($a1)
    /* 143B3C 00243B3C 1000A878 */  lq         $t0, 0x10($a1)
    /* 143B40 00243B40 2000A978 */  lq         $t1, 0x20($a1)
    /* 143B44 00243B44 6829C44B */  vadd.xyz   $vf5, $vf5, $vf4
    /* 143B48 00243B48 0000877C */  sq         $a3, 0x0($a0)
    /* 143B4C 00243B4C 1000887C */  sq         $t0, 0x10($a0)
    /* 143B50 00243B50 2000897C */  sq         $t1, 0x20($a0)
    /* 143B54 00243B54 0800E003 */  jr         $ra
    /* 143B58 00243B58 300085F8 */   sqc2      $vf5, 0x30($a0)
endlabel func_00243B30
