.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243BB8, 0x10

glabel func_00243BB8
    /* 143BB8 00243BB8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143BBC 00243BBC 3D21E54B */  vitof4.xyzw $vf5, $vf4
    /* 143BC0 00243BC0 0800E003 */  jr         $ra
    /* 143BC4 00243BC4 000085F8 */   sqc2      $vf5, 0x0($a0)
endlabel func_00243BB8
