.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00243B94, 0x4

glabel func_00243B94
    /* 143B94 00243B94 00000000 */  nop
endlabel func_00243B94
