.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243B70, 0x24

glabel func_00243B70
    /* 143B70 00243B70 0000A678 */  lq         $a2, 0x0($a1)
    /* 143B74 00243B74 1000A778 */  lq         $a3, 0x10($a1)
    /* 143B78 00243B78 2000A878 */  lq         $t0, 0x20($a1)
    /* 143B7C 00243B7C 3000A978 */  lq         $t1, 0x30($a1)
    /* 143B80 00243B80 0000867C */  sq         $a2, 0x0($a0)
    /* 143B84 00243B84 1000877C */  sq         $a3, 0x10($a0)
    /* 143B88 00243B88 2000887C */  sq         $t0, 0x20($a0)
    /* 143B8C 00243B8C 0800E003 */  jr         $ra
    /* 143B90 00243B90 3000897C */   sq        $t1, 0x30($a0)
endlabel func_00243B70
