.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243B18, 0x18

glabel func_00243B18
    /* 143B18 00243B18 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143B1C 00243B1C 00600844 */  mfc1       $t0, $f12
    /* 143B20 00243B20 0028A848 */  qmtc2.ni   $t0, $vf5
    /* 143B24 00243B24 9821E54B */  vmulx.xyzw $vf6, $vf4, $vf5x
    /* 143B28 00243B28 0800E003 */  jr         $ra
    /* 143B2C 00243B2C 000086F8 */   sqc2      $vf6, 0x0($a0)
endlabel func_00243B18
