.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243BC8, 0x10

glabel func_00243BC8
    /* 143BC8 00243BC8 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 143BCC 00243BCC 3C21E54B */  vitof0.xyzw $vf5, $vf4
    /* 143BD0 00243BD0 0800E003 */  jr         $ra
    /* 143BD4 00243BD4 000085F8 */   sqc2      $vf5, 0x0($a0)
endlabel func_00243BC8
