.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00243EC0, 0x24

glabel func_00243EC0
    /* 143EC0 00243EC0 00600844 */  mfc1       $t0, $f12
    /* 143EC4 00243EC4 00680944 */  mfc1       $t1, $f13
    /* 143EC8 00243EC8 0000A6D8 */  lqc2       $vf6, 0x0($a1)
    /* 143ECC 00243ECC 0020A848 */  qmtc2.ni   $t0, $vf4
    /* 143ED0 00243ED0 0028A948 */  qmtc2.ni   $t1, $vf5
    /* 143ED4 00243ED4 9031E44B */  vmaxx.xyzw $vf6, $vf6, $vf4x
    /* 143ED8 00243ED8 9431E54B */  vminix.xyzw $vf6, $vf6, $vf5x
    /* 143EDC 00243EDC 0800E003 */  jr         $ra
    /* 143EE0 00243EE0 000086F8 */   sqc2      $vf6, 0x0($a0)
endlabel func_00243EC0
