.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00244444, 0x4

glabel func_00244444
    /* 144444 00244444 00000000 */  nop
endlabel func_00244444
