.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00244448, 0x18

glabel func_00244448
    /* 144448 00244448 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 14444C 0024444C 00600844 */  mfc1       $t0, $f12
    /* 144450 00244450 0028A848 */  qmtc2.ni   $t0, $vf5
    /* 144454 00244454 1821C54B */  vmulx.xyz  $vf4, $vf4, $vf5x
    /* 144458 00244458 0800E003 */  jr         $ra
    /* 14445C 0024445C 000084F8 */   sqc2      $vf4, 0x0($a0)
endlabel func_00244448
