.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00244418, 0x2C

glabel func_00244418
    /* 144418 00244418 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 14441C 0024441C 0000C5D8 */  lqc2       $vf5, 0x0($a2)
    /* 144420 00244420 00600844 */  mfc1       $t0, $f12
    /* 144424 00244424 0030A848 */  qmtc2.ni   $t0, $vf6
    /* 144428 00244428 3C23294A */  vmove.w    $vf9, $vf4
    /* 14442C 0024442C C301004B */  vaddw.x    $vf7, $vf0, $vf0w
    /* 144430 00244430 2C3A064B */  vsub.x     $vf8, $vf7, $vf6
    /* 144434 00244434 BC21C64B */  vmulax.xyz $ACC, $vf4, $vf6x
    /* 144438 00244438 482AC84B */  vmaddx.xyz $vf9, $vf5, $vf8x
    /* 14443C 0024443C 0800E003 */  jr         $ra
    /* 144440 00244440 000089F8 */   sqc2      $vf9, 0x0($a0)
endlabel func_00244418
