.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002450A4, 0x4

glabel func_002450A4
    /* 1450A4 002450A4 00000000 */  nop
endlabel func_002450A4
