.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002453CC, 0x4

glabel func_002453CC
    /* 1453CC 002453CC 00000000 */  nop
endlabel func_002453CC
