.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_002455A8, 0xAC

glabel func_002455A8
    /* 1455A8 002455A8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 1455AC 002455AC 3000BFFF */  sd         $ra, 0x30($sp)
    /* 1455B0 002455B0 2000B2FF */  sd         $s2, 0x20($sp)
    /* 1455B4 002455B4 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1455B8 002455B8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1455BC 002455BC 00601140 */  mfc0       $s1, $12 /* handwritten instruction */
    /* 1455C0 002455C0 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 1455C4 002455C4 24882202 */  and        $s1, $s1, $v0
    /* 1455C8 002455C8 0A002012 */  beqz       $s1, .L002455F4
    /* 1455CC 002455CC 5500123C */   lui       $s2, %hi(D_005507D4)
.align 2
  .L002455D0:
    /* 1455D0 002455D0 39000042 */  di /* handwritten instruction */
    /* 1455D4 002455D4 0F040000 */  sync.p
    /* 1455D8 002455D8 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 1455DC 002455DC 0100033C */  lui        $v1, (0x10000 >> 16)
    /* 1455E0 002455E0 24104300 */  and        $v0, $v0, $v1
    /* 1455E4 002455E4 FAFF4014 */  bnez       $v0, .L002455D0
    /* 1455E8 002455E8 00000000 */   nop
    /* 1455EC 002455EC 02000010 */  b          .L002455F8
    /* 1455F0 002455F0 D407428E */   lw        $v0, %lo(D_005507D4)($s2)
.align 2
  .L002455F4:
    /* 1455F4 002455F4 D407428E */  lw         $v0, %lo(D_005507D4)($s2)
.align 2
  .L002455F8:
    /* 1455F8 002455F8 4001040C */  jal        func_00100500
    /* 1455FC 002455FC 21804400 */   addu      $s0, $v0, $a0
    /* 145600 00245600 2B105000 */  sltu       $v0, $v0, $s0
    /* 145604 00245604 0A004010 */  beqz       $v0, .L00245630
    /* 145608 00245608 D407428E */   lw        $v0, %lo(D_005507D4)($s2)
    /* 14560C 0024560C 1490090C */  jal        func_00264050
    /* 145610 00245610 00000000 */   nop
    /* 145614 00245614 0C000324 */  addiu      $v1, $zero, 0xC
    /* 145618 00245618 02002012 */  beqz       $s1, .L00245624
    /* 14561C 0024561C 000043AC */   sw        $v1, 0x0($v0)
    /* 145620 00245620 38000042 */  ei /* handwritten instruction */
.align 2
  .L00245624:
    /* 145624 00245624 FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 145628 00245628 04000010 */  b          .L0024563C
    /* 14562C 0024562C FFFF4234 */   ori       $v0, $v0, (0xFFFFFFFF & 0xFFFF)
.align 2
  .L00245630:
    /* 145630 00245630 02002012 */  beqz       $s1, .L0024563C
    /* 145634 00245634 D40750AE */   sw        $s0, %lo(D_005507D4)($s2)
    /* 145638 00245638 38000042 */  ei /* handwritten instruction */
.align 2
  .L0024563C:
    /* 14563C 0024563C 3000BFDF */  ld         $ra, 0x30($sp)
    /* 145640 00245640 2000B2DF */  ld         $s2, 0x20($sp)
    /* 145644 00245644 1000B1DF */  ld         $s1, 0x10($sp)
    /* 145648 00245648 0000B0DF */  ld         $s0, 0x0($sp)
    /* 14564C 0024564C 0800E003 */  jr         $ra
    /* 145650 00245650 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_002455A8
    /* 145654 00245654 00000000 */  nop
