.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00245674, 0x4

glabel func_00245674
    /* 145674 00245674 00000000 */  nop
endlabel func_00245674
