.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024571C, 0x4

glabel func_0024571C
    /* 14571C 0024571C 00000000 */  nop
endlabel func_0024571C
