.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002470D4, 0x4

glabel func_002470D4
    /* 1470D4 002470D4 00000000 */  nop
endlabel func_002470D4
