.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00247104, 0x4

glabel func_00247104
    /* 147104 00247104 00000000 */  nop
endlabel func_00247104
