.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_0024AE38, 0x48

glabel func_0024AE38
    /* 14AE38 0024AE38 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 14AE3C 0024AE3C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 14AE40 0024AE40 4C02040C */  jal        func_00100930
    /* 14AE44 0024AE44 04000424 */   addiu     $a0, $zero, 0x4
    /* 14AE48 0024AE48 0400033C */  lui        $v1, (0x40000 >> 16)
    /* 14AE4C 0024AE4C 24104300 */  and        $v0, $v0, $v1
    /* 14AE50 0024AE50 07004010 */  beqz       $v0, .L0024AE70
    /* 14AE54 0024AE54 04000424 */   addiu     $a0, $zero, 0x4
    /* 14AE58 0024AE58 4802040C */  jal        func_00100920
    /* 14AE5C 0024AE5C 0400053C */   lui       $a1, (0x40000 >> 16)
    /* 14AE60 0024AE60 F014090C */  jal        func_002453C0
    /* 14AE64 0024AE64 00000000 */   nop
    /* 14AE68 0024AE68 02000010 */  b          .L0024AE74
    /* 14AE6C 0024AE6C 01000224 */   addiu     $v0, $zero, 0x1
.align 2
  .L0024AE70:
    /* 14AE70 0024AE70 2D100000 */  daddu      $v0, $zero, $zero
.align 2
  .L0024AE74:
    /* 14AE74 0024AE74 0000BFDF */  ld         $ra, 0x0($sp)
    /* 14AE78 0024AE78 0800E003 */  jr         $ra
    /* 14AE7C 0024AE7C 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0024AE38

.align 3
nonmatching func_0024AE80, 0x110

glabel func_0024AE80
    /* 14AE80 0024AE80 80FFBD27 */  addiu      $sp, $sp, -0x80
    /* 14AE84 0024AE84 6300023C */  lui        $v0, %hi(D_0062E670)
    /* 14AE88 0024AE88 6000B1FF */  sd         $s1, 0x60($sp)
    /* 14AE8C 0024AE8C 5000B0FF */  sd         $s0, 0x50($sp)
    /* 14AE90 0024AE90 7000BFFF */  sd         $ra, 0x70($sp)
    /* 14AE94 0024AE94 2D808000 */  daddu      $s0, $a0, $zero
    /* 14AE98 0024AE98 00000382 */  lb         $v1, 0x0($s0)
    /* 14AE9C 0024AE9C 0B006010 */  beqz       $v1, .L0024AECC
    /* 14AEA0 0024AEA0 70E65124 */   addiu     $s1, $v0, %lo(D_0062E670)
    /* 14AEA4 0024AEA4 F5FF0326 */  addiu      $v1, $s0, -0xB
.align 2
  .L0024AEA8:
    /* 14AEA8 0024AEA8 01008424 */  addiu      $a0, $a0, 0x1
    /* 14AEAC 0024AEAC 00008280 */  lb         $v0, 0x0($a0)
    /* 14AEB0 0024AEB0 00000000 */  nop
    /* 14AEB4 0024AEB4 00000000 */  nop
    /* 14AEB8 0024AEB8 00000000 */  nop
    /* 14AEBC 0024AEBC FAFF4014 */  bnez       $v0, .L0024AEA8
    /* 14AEC0 0024AEC0 00000000 */   nop
    /* 14AEC4 0024AEC4 03000010 */  b          .L0024AED4
    /* 14AEC8 0024AEC8 23108300 */   subu      $v0, $a0, $v1
.align 2
  .L0024AECC:
    /* 14AECC 0024AECC F5FF0326 */  addiu      $v1, $s0, -0xB
    /* 14AED0 0024AED0 23108300 */  subu       $v0, $a0, $v1
.align 2
  .L0024AED4:
    /* 14AED4 0024AED4 5100422C */  sltiu      $v0, $v0, 0x51
    /* 14AED8 0024AED8 06004014 */  bnez       $v0, .L0024AEF4
    /* 14AEDC 0024AEDC 6300043C */   lui       $a0, %hi(D_0062E680)
    /* 14AEE0 0024AEE0 2D280002 */  daddu      $a1, $s0, $zero
    /* 14AEE4 0024AEE4 B690090C */  jal        func_002642D8
    /* 14AEE8 0024AEE8 80E68424 */   addiu     $a0, $a0, %lo(D_0062E680)
    /* 14AEEC 0024AEEC 23000010 */  b          .L0024AF7C
    /* 14AEF0 0024AEF0 2D100000 */   daddu     $v0, $zero, $zero
.align 2
  .L0024AEF4:
    /* 14AEF4 0024AEF4 0617090C */  jal        func_00245C18
    /* 14AEF8 0024AEF8 2D200000 */   daddu     $a0, $zero, $zero
    /* 14AEFC 0024AEFC 6E17090C */  jal        func_00245DB8
    /* 14AF00 0024AF00 00000000 */   nop
    /* 14AF04 0024AF04 00002282 */  lb         $v0, 0x0($s1)
    /* 14AF08 0024AF08 2D18A003 */  daddu      $v1, $sp, $zero
    /* 14AF0C 0024AF0C 0B004010 */  beqz       $v0, .L0024AF3C
    /* 14AF10 0024AF10 00002492 */   lbu       $a0, 0x0($s1)
    /* 14AF14 0024AF14 00000592 */  lbu        $a1, 0x0($s0)
.align 2
  .L0024AF18:
    /* 14AF18 0024AF18 000064A0 */  sb         $a0, 0x0($v1)
    /* 14AF1C 0024AF1C 01003126 */  addiu      $s1, $s1, 0x1
    /* 14AF20 0024AF20 01006324 */  addiu      $v1, $v1, 0x1
    /* 14AF24 0024AF24 00002492 */  lbu        $a0, 0x0($s1)
    /* 14AF28 0024AF28 00002282 */  lb         $v0, 0x0($s1)
    /* 14AF2C 0024AF2C FAFF4014 */  bnez       $v0, .L0024AF18
    /* 14AF30 0024AF30 00000000 */   nop
    /* 14AF34 0024AF34 03000010 */  b          .L0024AF44
    /* 14AF38 0024AF38 2D20A000 */   daddu     $a0, $a1, $zero
.align 2
  .L0024AF3C:
    /* 14AF3C 0024AF3C 00000592 */  lbu        $a1, 0x0($s0)
    /* 14AF40 0024AF40 2D20A000 */  daddu      $a0, $a1, $zero
.align 2
  .L0024AF44:
    /* 14AF44 0024AF44 0A008050 */  beql       $a0, $zero, .L0024AF70
    /* 14AF48 0024AF48 000060A0 */   sb        $zero, 0x0($v1)
    /* 14AF4C 0024AF4C 00000000 */  nop
.align 2
  .L0024AF50:
    /* 14AF50 0024AF50 000064A0 */  sb         $a0, 0x0($v1)
    /* 14AF54 0024AF54 01001026 */  addiu      $s0, $s0, 0x1
    /* 14AF58 0024AF58 01006324 */  addiu      $v1, $v1, 0x1
    /* 14AF5C 0024AF5C 00000282 */  lb         $v0, 0x0($s0)
    /* 14AF60 0024AF60 2D204000 */  daddu      $a0, $v0, $zero
    /* 14AF64 0024AF64 FAFF4014 */  bnez       $v0, .L0024AF50
    /* 14AF68 0024AF68 00000000 */   nop
    /* 14AF6C 0024AF6C 000060A0 */  sb         $zero, 0x0($v1)
.align 2
  .L0024AF70:
    /* 14AF70 0024AF70 2D20A003 */  daddu      $a0, $sp, $zero
    /* 14AF74 0024AF74 382B090C */  jal        func_0024ACE0
    /* 14AF78 0024AF78 2D280000 */   daddu     $a1, $zero, $zero
.align 2
  .L0024AF7C:
    /* 14AF7C 0024AF7C 7000BFDF */  ld         $ra, 0x70($sp)
    /* 14AF80 0024AF80 6000B1DF */  ld         $s1, 0x60($sp)
    /* 14AF84 0024AF84 5000B0DF */  ld         $s0, 0x50($sp)
    /* 14AF88 0024AF88 0800E003 */  jr         $ra
    /* 14AF8C 0024AF8C 8000BD27 */   addiu     $sp, $sp, 0x80
endlabel func_0024AE80

.align 3
/* Handwritten function */
nonmatching func_0024AF90, 0x98

glabel func_0024AF90
    /* 14AF90 0024AF90 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 14AF94 0024AF94 4000BFFF */  sd         $ra, 0x40($sp)
    /* 14AF98 0024AF98 3000B3FF */  sd         $s3, 0x30($sp)
    /* 14AF9C 0024AF9C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 14AFA0 0024AFA0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 14AFA4 0024AFA4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 14AFA8 0024AFA8 00301140 */  mfc0       $s1, $6 /* handwritten instruction */
    /* 14AFAC 0024AFAC 6300133C */  lui        $s3, %hi(D_0062E6A0)
    /* 14AFB0 0024AFB0 6300123C */  lui        $s2, %hi(D_0062E6E0)
    /* 14AFB4 0024AFB4 2D800000 */  daddu      $s0, $zero, $zero
    /* 14AFB8 0024AFB8 A0E66426 */  addiu      $a0, $s3, %lo(D_0062E6A0)
    /* 14AFBC 0024AFBC 00000000 */  nop
.align 2
  .L0024AFC0:
    /* 14AFC0 0024AFC0 03001116 */  bne        $s0, $s1, .L0024AFD0
    /* 14AFC4 0024AFC4 2D280002 */   daddu     $a1, $s0, $zero
    /* 14AFC8 0024AFC8 7806040C */  jal        func_001019E0
    /* 14AFCC 0024AFCC 00000000 */   nop
.align 2
  .L0024AFD0:
    /* 14AFD0 0024AFD0 00009040 */  mtc0       $s0, $0 /* handwritten instruction */
    /* 14AFD4 0024AFD4 0F040000 */  sync.p
    /* 14AFD8 0024AFD8 01000042 */  tlbr /* handwritten instruction */
    /* 14AFDC 0024AFDC 0F040000 */  sync.p
    /* 14AFE0 0024AFE0 00100840 */  mfc0       $t0, $2 /* handwritten instruction */
    /* 14AFE4 0024AFE4 00180940 */  mfc0       $t1, $3 /* handwritten instruction */
    /* 14AFE8 0024AFE8 00280640 */  mfc0       $a2, $5 /* handwritten instruction */
    /* 14AFEC 0024AFEC 00500740 */  mfc0       $a3, $10 /* handwritten instruction */
    /* 14AFF0 0024AFF0 2D280002 */  daddu      $a1, $s0, $zero
    /* 14AFF4 0024AFF4 7806040C */  jal        func_001019E0
    /* 14AFF8 0024AFF8 E0E64426 */   addiu     $a0, $s2, %lo(D_0062E6E0)
    /* 14AFFC 0024AFFC 01001026 */  addiu      $s0, $s0, 0x1
    /* 14B000 0024B000 3000022A */  slti       $v0, $s0, 0x30
    /* 14B004 0024B004 EEFF4054 */  bnel       $v0, $zero, .L0024AFC0
    /* 14B008 0024B008 A0E66426 */   addiu     $a0, $s3, %lo(D_0062E6A0)
    /* 14B00C 0024B00C 4000BFDF */  ld         $ra, 0x40($sp)
    /* 14B010 0024B010 3000B3DF */  ld         $s3, 0x30($sp)
    /* 14B014 0024B014 2000B2DF */  ld         $s2, 0x20($sp)
    /* 14B018 0024B018 1000B1DF */  ld         $s1, 0x10($sp)
    /* 14B01C 0024B01C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 14B020 0024B020 0800E003 */  jr         $ra
    /* 14B024 0024B024 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_0024AF90

.align 3
/* Handwritten function */
nonmatching func_0024B028, 0xBC

glabel func_0024B028
    /* 14B028 0024B028 021E0500 */  srl        $v1, $a1, 24
    /* 14B02C 0024B02C 30000224 */  addiu      $v0, $zero, 0x30
    /* 14B030 0024B030 1A006210 */  beq        $v1, $v0, .L0024B09C
    /* 14B034 0024B034 3100622C */   sltiu     $v0, $v1, 0x31
    /* 14B038 0024B038 0D004010 */  beqz       $v0, .L0024B070
    /* 14B03C 0024B03C 10000224 */   addiu     $v0, $zero, 0x10
    /* 14B040 0024B040 1A006210 */  beq        $v1, $v0, .L0024B0AC
    /* 14B044 0024B044 1100622C */   sltiu     $v0, $v1, 0x11
    /* 14B048 0024B048 05004010 */  beqz       $v0, .L0024B060
    /* 14B04C 0024B04C 20000224 */   addiu     $v0, $zero, 0x20
    /* 14B050 0024B050 13006010 */  beqz       $v1, .L0024B0A0
    /* 14B054 0024B054 0F006230 */   andi      $v0, $v1, 0xF
    /* 14B058 0024B058 16000010 */  b          .L0024B0B4
    /* 14B05C 0024B05C 00000000 */   nop
.align 2
  .L0024B060:
    /* 14B060 0024B060 0F006210 */  beq        $v1, $v0, .L0024B0A0
    /* 14B064 0024B064 0F006230 */   andi      $v0, $v1, 0xF
    /* 14B068 0024B068 12000010 */  b          .L0024B0B4
    /* 14B06C 0024B06C 00000000 */   nop
.align 2
  .L0024B070:
    /* 14B070 0024B070 50000224 */  addiu      $v0, $zero, 0x50
    /* 14B074 0024B074 0D006210 */  beq        $v1, $v0, .L0024B0AC
    /* 14B078 0024B078 5100622C */   sltiu     $v0, $v1, 0x51
    /* 14B07C 0024B07C 0D004014 */  bnez       $v0, .L0024B0B4
    /* 14B080 0024B080 60000224 */   addiu     $v0, $zero, 0x60
    /* 14B084 0024B084 09006210 */  beq        $v1, $v0, .L0024B0AC
    /* 14B088 0024B088 70000224 */   addiu     $v0, $zero, 0x70
    /* 14B08C 0024B08C 07006210 */  beq        $v1, $v0, .L0024B0AC
    /* 14B090 0024B090 00000000 */   nop
    /* 14B094 0024B094 07000010 */  b          .L0024B0B4
    /* 14B098 0024B098 00000000 */   nop
.align 2
  .L0024B09C:
    /* 14B09C 0024B09C 0F006230 */  andi       $v0, $v1, 0xF
.align 2
  .L0024B0A0:
    /* 14B0A0 0024B0A0 0800422C */  sltiu      $v0, $v0, 0x8
    /* 14B0A4 0024B0A4 03004010 */  beqz       $v0, .L0024B0B4
    /* 14B0A8 0024B0A8 00000000 */   nop
.align 2
  .L0024B0AC:
    /* 14B0AC 0024B0AC 0800E003 */  jr         $ra
    /* 14B0B0 0024B0B0 FFFF0224 */   addiu     $v0, $zero, -0x1
.align 2
  .L0024B0B4:
    /* 14B0B4 0024B0B4 00288440 */  mtc0       $a0, $5 /* handwritten instruction */
    /* 14B0B8 0024B0B8 00508540 */  mtc0       $a1, $10 /* handwritten instruction */
    /* 14B0BC 0024B0BC 00108640 */  mtc0       $a2, $2 /* handwritten instruction */
    /* 14B0C0 0024B0C0 00188740 */  mtc0       $a3, $3 /* handwritten instruction */
    /* 14B0C4 0024B0C4 0F040000 */  sync.p
    /* 14B0C8 0024B0C8 06000042 */  tlbwr /* handwritten instruction */
    /* 14B0CC 0024B0CC 0F040000 */  sync.p
    /* 14B0D0 0024B0D0 08000042 */  tlbp /* handwritten instruction */
    /* 14B0D4 0024B0D4 0F040000 */  sync.p
    /* 14B0D8 0024B0D8 00000240 */  mfc0       $v0, $0 /* handwritten instruction */
    /* 14B0DC 0024B0DC 0800E003 */  jr         $ra
    /* 14B0E0 0024B0E0 00000000 */   nop
endlabel func_0024B028
    /* 14B0E4 0024B0E4 00000000 */  nop

.align 3
/* Handwritten function */
nonmatching func_0024B0E8, 0x48

glabel func_0024B0E8
    /* 14B0E8 0024B0E8 00300240 */  mfc0       $v0, $6 /* handwritten instruction */
    /* 14B0EC 0024B0EC 2A108200 */  slt        $v0, $a0, $v0
    /* 14B0F0 0024B0F0 03004014 */  bnez       $v0, .L0024B100
    /* 14B0F4 0024B0F4 30008228 */   slti      $v0, $a0, 0x30
    /* 14B0F8 0024B0F8 03004014 */  bnez       $v0, .L0024B108
    /* 14B0FC 0024B0FC 00000000 */   nop
.align 2
  .L0024B100:
    /* 14B100 0024B100 0800E003 */  jr         $ra
    /* 14B104 0024B104 FFFF0224 */   addiu     $v0, $zero, -0x1
.align 2
  .L0024B108:
    /* 14B108 0024B108 00008440 */  mtc0       $a0, $0 /* handwritten instruction */
    /* 14B10C 0024B10C 00288540 */  mtc0       $a1, $5 /* handwritten instruction */
    /* 14B110 0024B110 00508640 */  mtc0       $a2, $10 /* handwritten instruction */
    /* 14B114 0024B114 00108740 */  mtc0       $a3, $2 /* handwritten instruction */
    /* 14B118 0024B118 00188840 */  mtc0       $t0, $3 /* handwritten instruction */
    /* 14B11C 0024B11C 0F040000 */  sync.p
    /* 14B120 0024B120 02000042 */  tlbwi /* handwritten instruction */
    /* 14B124 0024B124 0F040000 */  sync.p
    /* 14B128 0024B128 0800E003 */  jr         $ra
    /* 14B12C 0024B12C 2D108000 */   daddu     $v0, $a0, $zero
endlabel func_0024B0E8

.align 3
/* Handwritten function */
nonmatching func_0024B130, 0x4C

glabel func_0024B130
    /* 14B130 0024B130 3000822C */  sltiu      $v0, $a0, 0x30
    /* 14B134 0024B134 03004014 */  bnez       $v0, .L0024B144
    /* 14B138 0024B138 00000000 */   nop
    /* 14B13C 0024B13C 0800E003 */  jr         $ra
    /* 14B140 0024B140 FFFF0224 */   addiu     $v0, $zero, -0x1
.align 2
  .L0024B144:
    /* 14B144 0024B144 00008440 */  mtc0       $a0, $0 /* handwritten instruction */
    /* 14B148 0024B148 0F040000 */  sync.p
    /* 14B14C 0024B14C 01000042 */  tlbr /* handwritten instruction */
    /* 14B150 0024B150 0F040000 */  sync.p
    /* 14B154 0024B154 00280240 */  mfc0       $v0, $5 /* handwritten instruction */
    /* 14B158 0024B158 0000A2AC */  sw         $v0, 0x0($a1)
    /* 14B15C 0024B15C 00500340 */  mfc0       $v1, $10 /* handwritten instruction */
    /* 14B160 0024B160 0000C3AC */  sw         $v1, 0x0($a2)
    /* 14B164 0024B164 00100240 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 14B168 0024B168 0000E2AC */  sw         $v0, 0x0($a3)
    /* 14B16C 0024B16C 00180340 */  mfc0       $v1, $3 /* handwritten instruction */
    /* 14B170 0024B170 000003AD */  sw         $v1, 0x0($t0)
    /* 14B174 0024B174 0800E003 */  jr         $ra
    /* 14B178 0024B178 2D108000 */   daddu     $v0, $a0, $zero
endlabel func_0024B130
    /* 14B17C 0024B17C 00000000 */  nop

.align 3
/* Handwritten function */
nonmatching func_0024B180, 0x4C

glabel func_0024B180
    /* 14B180 0024B180 00508440 */  mtc0       $a0, $10 /* handwritten instruction */
    /* 14B184 0024B184 0F040000 */  sync.p
    /* 14B188 0024B188 08000042 */  tlbp /* handwritten instruction */
    /* 14B18C 0024B18C 0F040000 */  sync.p
    /* 14B190 0024B190 00000440 */  mfc0       $a0, $0 /* handwritten instruction */
    /* 14B194 0024B194 03008104 */  bgez       $a0, .L0024B1A4
    /* 14B198 0024B198 00000000 */   nop
    /* 14B19C 0024B19C 09000010 */  b          .L0024B1C4
    /* 14B1A0 0024B1A0 FFFF0424 */   addiu     $a0, $zero, -0x1
.align 2
  .L0024B1A4:
    /* 14B1A4 0024B1A4 01000042 */  tlbr /* handwritten instruction */
    /* 14B1A8 0024B1A8 0F040000 */  sync.p
    /* 14B1AC 0024B1AC 00280240 */  mfc0       $v0, $5 /* handwritten instruction */
    /* 14B1B0 0024B1B0 0000A2AC */  sw         $v0, 0x0($a1)
    /* 14B1B4 0024B1B4 00100340 */  mfc0       $v1, $2 /* handwritten instruction */
    /* 14B1B8 0024B1B8 0000C3AC */  sw         $v1, 0x0($a2)
    /* 14B1BC 0024B1BC 00180240 */  mfc0       $v0, $3 /* handwritten instruction */
    /* 14B1C0 0024B1C0 0000E2AC */  sw         $v0, 0x0($a3)
.align 2
  .L0024B1C4:
    /* 14B1C4 0024B1C4 0800E003 */  jr         $ra
    /* 14B1C8 0024B1C8 2D108000 */   daddu     $v0, $a0, $zero
endlabel func_0024B180
    /* 14B1CC 0024B1CC 00000000 */  nop

.align 3
/* Handwritten function */
nonmatching func_0024B1D0, 0x130

glabel func_0024B1D0
    /* 14B1D0 0024B1D0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 14B1D4 0024B1D4 1000B0FF */  sd         $s0, 0x10($sp)
    /* 14B1D8 0024B1D8 2D808000 */  daddu      $s0, $a0, $zero
    /* 14B1DC 0024B1DC FF0F0232 */  andi       $v0, $s0, 0xFFF
    /* 14B1E0 0024B1E0 07004014 */  bnez       $v0, .L0024B200
    /* 14B1E4 0024B1E4 2000BFFF */   sd        $ra, 0x20($sp)
    /* 14B1E8 0024B1E8 0F00023C */  lui        $v0, (0xFFFFE >> 16)
    /* 14B1EC 0024B1EC FFFF0326 */  addiu      $v1, $s0, -0x1
    /* 14B1F0 0024B1F0 FEFF4234 */  ori        $v0, $v0, (0xFFFFE & 0xFFFF)
    /* 14B1F4 0024B1F4 2B104300 */  sltu       $v0, $v0, $v1
    /* 14B1F8 0024B1F8 03004014 */  bnez       $v0, .L0024B208
    /* 14B1FC 0024B1FC 0070043C */   lui       $a0, (0x70004000 >> 16)
.align 2
  .L0024B200:
    /* 14B200 0024B200 3B000010 */  b          .L0024B2F0
    /* 14B204 0024B204 FFFF0224 */   addiu     $v0, $zero, -0x1
.align 2
  .L0024B208:
    /* 14B208 0024B208 2D28A003 */  daddu      $a1, $sp, $zero
    /* 14B20C 0024B20C 00408434 */  ori        $a0, $a0, (0x70004000 & 0xFFFF)
    /* 14B210 0024B210 0400A637 */  ori        $a2, $sp, 0x4
    /* 14B214 0024B214 602C090C */  jal        func_0024B180
    /* 14B218 0024B218 0800A737 */   ori       $a3, $sp, 0x8
    /* 14B21C 0024B21C 2D284000 */  daddu      $a1, $v0, $zero
    /* 14B220 0024B220 0900A104 */  bgez       $a1, .L0024B248
    /* 14B224 0024B224 00000000 */   nop
    /* 14B228 0024B228 31000012 */  beqz       $s0, .L0024B2F0
    /* 14B22C 0024B22C 2D100000 */   daddu     $v0, $zero, $zero
    /* 14B230 0024B230 00300540 */  mfc0       $a1, $6 /* handwritten instruction */
    /* 14B234 0024B234 0100A224 */  addiu      $v0, $a1, 0x1
    /* 14B238 0024B238 00308240 */  mtc0       $v0, $6 /* handwritten instruction */
    /* 14B23C 0024B23C 0F040000 */  sync.p
    /* 14B240 0024B240 13000010 */  b          .L0024B290
    /* 14B244 0024B244 00000000 */   nop
.align 2
  .L0024B248:
    /* 14B248 0024B248 11000016 */  bnez       $s0, .L0024B290
    /* 14B24C 0024B24C FFFFA224 */   addiu     $v0, $a1, -0x1
    /* 14B250 0024B250 01E0033C */  lui        $v1, (0xE0010000 >> 16)
    /* 14B254 0024B254 40130200 */  sll        $v0, $v0, 13
    /* 14B258 0024B258 21304300 */  addu       $a2, $v0, $v1
    /* 14B25C 0024B25C 00300240 */  mfc0       $v0, $6 /* handwritten instruction */
    /* 14B260 0024B260 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 14B264 0024B264 00308240 */  mtc0       $v0, $6 /* handwritten instruction */
    /* 14B268 0024B268 00008540 */  mtc0       $a1, $0 /* handwritten instruction */
    /* 14B26C 0024B26C 00288040 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 14B270 0024B270 00508640 */  mtc0       $a2, $10 /* handwritten instruction */
    /* 14B274 0024B274 00108040 */  mtc0       $zero, $2 /* handwritten instruction */
    /* 14B278 0024B278 00188040 */  mtc0       $zero, $3 /* handwritten instruction */
    /* 14B27C 0024B27C 0F040000 */  sync.p
    /* 14B280 0024B280 02000042 */  tlbwi /* handwritten instruction */
    /* 14B284 0024B284 0F040000 */  sync.p
    /* 14B288 0024B288 19000010 */  b          .L0024B2F0
    /* 14B28C 0024B28C 2D100000 */   daddu     $v0, $zero, $zero
.align 2
  .L0024B290:
    /* 14B290 0024B290 FFFF023C */  lui        $v0, (0xFFFFF000 >> 16)
    /* 14B294 0024B294 00100426 */  addiu      $a0, $s0, 0x1000
    /* 14B298 0024B298 00F04234 */  ori        $v0, $v0, (0xFFFFF000 & 0xFFFF)
    /* 14B29C 0024B29C 0070063C */  lui        $a2, (0x70004000 >> 16)
    /* 14B2A0 0024B2A0 24208200 */  and        $a0, $a0, $v0
    /* 14B2A4 0024B2A4 0000A0AF */  sw         $zero, 0x0($sp)
    /* 14B2A8 0024B2A8 24100202 */  and        $v0, $s0, $v0
    /* 14B2AC 0024B2AC 82210400 */  srl        $a0, $a0, 6
    /* 14B2B0 0024B2B0 82110200 */  srl        $v0, $v0, 6
    /* 14B2B4 0024B2B4 1F008434 */  ori        $a0, $a0, 0x1F
    /* 14B2B8 0024B2B8 1F004234 */  ori        $v0, $v0, 0x1F
    /* 14B2BC 0024B2BC 0040C634 */  ori        $a2, $a2, (0x70004000 & 0xFFFF)
    /* 14B2C0 0024B2C0 0400A2AF */  sw         $v0, 0x4($sp)
    /* 14B2C4 0024B2C4 0800A4AF */  sw         $a0, 0x8($sp)
    /* 14B2C8 0024B2C8 00008540 */  mtc0       $a1, $0 /* handwritten instruction */
    /* 14B2CC 0024B2CC 2D180000 */  daddu      $v1, $zero, $zero
    /* 14B2D0 0024B2D0 00288340 */  mtc0       $v1, $5 /* handwritten instruction */
    /* 14B2D4 0024B2D4 00508640 */  mtc0       $a2, $10 /* handwritten instruction */
    /* 14B2D8 0024B2D8 00108240 */  mtc0       $v0, $2 /* handwritten instruction */
    /* 14B2DC 0024B2DC 00188440 */  mtc0       $a0, $3 /* handwritten instruction */
    /* 14B2E0 0024B2E0 0F040000 */  sync.p
    /* 14B2E4 0024B2E4 02000042 */  tlbwi /* handwritten instruction */
    /* 14B2E8 0024B2E8 0F040000 */  sync.p
    /* 14B2EC 0024B2EC 2D10A000 */  daddu      $v0, $a1, $zero
.align 2
  .L0024B2F0:
    /* 14B2F0 0024B2F0 2000BFDF */  ld         $ra, 0x20($sp)
    /* 14B2F4 0024B2F4 1000B0DF */  ld         $s0, 0x10($sp)
    /* 14B2F8 0024B2F8 0800E003 */  jr         $ra
    /* 14B2FC 0024B2FC 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0024B1D0

.align 3
nonmatching func_0024B300, 0x60

glabel func_0024B300
    /* 14B300 0024B300 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 14B304 0024B304 5500023C */  lui        $v0, %hi(D_00550880)
    /* 14B308 0024B308 0000B0FF */  sd         $s0, 0x0($sp)
    /* 14B30C 0024B30C 1000B1FF */  sd         $s1, 0x10($sp)
    /* 14B310 0024B310 2500103C */  lui        $s0, %hi(func_0024B500)
    /* 14B314 0024B314 00B51026 */  addiu      $s0, $s0, %lo(func_0024B500)
    /* 14B318 0024B318 2D888000 */  daddu      $s1, $a0, $zero
    /* 14B31C 0024B31C 800851AC */  sw         $s1, %lo(D_00550880)($v0)
    /* 14B320 0024B320 2D280002 */  daddu      $a1, $s0, $zero
    /* 14B324 0024B324 2000BFFF */  sd         $ra, 0x20($sp)
    /* 14B328 0024B328 7400040C */  jal        func_001001D0
    /* 14B32C 0024B32C 01000424 */   addiu     $a0, $zero, 0x1
    /* 14B330 0024B330 2D280002 */  daddu      $a1, $s0, $zero
    /* 14B334 0024B334 7400040C */  jal        func_001001D0
    /* 14B338 0024B338 02000424 */   addiu     $a0, $zero, 0x2
    /* 14B33C 0024B33C 2D280002 */  daddu      $a1, $s0, $zero
    /* 14B340 0024B340 7400040C */  jal        func_001001D0
    /* 14B344 0024B344 03000424 */   addiu     $a0, $zero, 0x3
    /* 14B348 0024B348 2D102002 */  daddu      $v0, $s1, $zero
    /* 14B34C 0024B34C 2000BFDF */  ld         $ra, 0x20($sp)
    /* 14B350 0024B350 1000B1DF */  ld         $s1, 0x10($sp)
    /* 14B354 0024B354 0000B0DF */  ld         $s0, 0x0($sp)
    /* 14B358 0024B358 0800E003 */  jr         $ra
    /* 14B35C 0024B35C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0024B300

.align 3
nonmatching func_0024B360, 0x84

glabel func_0024B360
    /* 14B360 0024B360 2D308000 */  daddu      $a2, $a0, $zero
    /* 14B364 0024B364 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 14B368 0024B368 FFFFC424 */  addiu      $a0, $a2, -0x1
    /* 14B36C 0024B36C 1000BFFF */  sd         $ra, 0x10($sp)
    /* 14B370 0024B370 0D00822C */  sltiu      $v0, $a0, 0xD
    /* 14B374 0024B374 04004014 */  bnez       $v0, .L0024B388
    /* 14B378 0024B378 0000B0FF */   sd        $s0, 0x0($sp)
    /* 14B37C 0024B37C FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 14B380 0024B380 14000010 */  b          .L0024B3D4
    /* 14B384 0024B384 FFFF4234 */   ori       $v0, $v0, (0xFFFFFFFF & 0xFFFF)
.align 2
  .L0024B388:
    /* 14B388 0024B388 5500023C */  lui        $v0, %hi(D_00550888)
    /* 14B38C 0024B38C 80180600 */  sll        $v1, $a2, 2
    /* 14B390 0024B390 88084224 */  addiu      $v0, $v0, %lo(D_00550888)
    /* 14B394 0024B394 0300842C */  sltiu      $a0, $a0, 0x3
    /* 14B398 0024B398 21186200 */  addu       $v1, $v1, $v0
    /* 14B39C 0024B39C 0000708C */  lw         $s0, 0x0($v1)
    /* 14B3A0 0024B3A0 07008010 */  beqz       $a0, .L0024B3C0
    /* 14B3A4 0024B3A4 000065AC */   sw        $a1, 0x0($v1)
    /* 14B3A8 0024B3A8 2500053C */  lui        $a1, %hi(D_0024B740)
    /* 14B3AC 0024B3AC 2D20C000 */  daddu      $a0, $a2, $zero
    /* 14B3B0 0024B3B0 7400040C */  jal        func_001001D0
    /* 14B3B4 0024B3B4 40B7A524 */   addiu     $a1, $a1, %lo(D_0024B740)
    /* 14B3B8 0024B3B8 06000010 */  b          .L0024B3D4
    /* 14B3BC 0024B3BC 2D100002 */   daddu     $v0, $s0, $zero
.align 2
  .L0024B3C0:
    /* 14B3C0 0024B3C0 2500053C */  lui        $a1, %hi(D_0024B740)
    /* 14B3C4 0024B3C4 2D20C000 */  daddu      $a0, $a2, $zero
    /* 14B3C8 0024B3C8 7800040C */  jal        func_001001E0
    /* 14B3CC 0024B3CC 40B7A524 */   addiu     $a1, $a1, %lo(D_0024B740)
    /* 14B3D0 0024B3D0 2D100002 */  daddu      $v0, $s0, $zero
.align 2
  .L0024B3D4:
    /* 14B3D4 0024B3D4 1000BFDF */  ld         $ra, 0x10($sp)
    /* 14B3D8 0024B3D8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 14B3DC 0024B3DC 0800E003 */  jr         $ra
    /* 14B3E0 0024B3E0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0024B360
    /* 14B3E4 0024B3E4 00000000 */  nop
