.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B3E8, 0x10

glabel func_0024B3E8
    /* 14B3E8 0024B3E8 74000324 */  addiu      $v1, $zero, 0x74
    /* 14B3EC 0024B3EC 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B3F0 0024B3F0 0800E003 */  jr         $ra
    /* 14B3F4 0024B3F4 00000000 */   nop
endlabel func_0024B3E8
