.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B468, 0x10

glabel func_0024B468
    /* 14B468 0024B468 56000324 */  addiu      $v1, $zero, 0x56
    /* 14B46C 0024B46C 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B470 0024B470 0800E003 */  jr         $ra
    /* 14B474 0024B474 00000000 */   nop
endlabel func_0024B468
