.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B4C8, 0x10

glabel func_0024B4C8
    /* 14B4C8 0024B4C8 59000324 */  addiu      $v1, $zero, 0x59
    /* 14B4CC 0024B4CC 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B4D0 0024B4D0 0800E003 */  jr         $ra
    /* 14B4D4 0024B4D4 00000000 */   nop
endlabel func_0024B4C8
