.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B498, 0x10

glabel func_0024B498
    /* 14B498 0024B498 A9FF0324 */  addiu      $v1, $zero, -0x57
    /* 14B49C 0024B49C 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B4A0 0024B4A0 0800E003 */  jr         $ra
    /* 14B4A4 0024B4A4 00000000 */   nop
endlabel func_0024B498
