.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B448, 0x10

glabel func_0024B448
    /* 14B448 0024B448 55000324 */  addiu      $v1, $zero, 0x55
    /* 14B44C 0024B44C 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B450 0024B450 0800E003 */  jr         $ra
    /* 14B454 0024B454 00000000 */   nop
endlabel func_0024B448
