.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B478, 0x10

glabel func_0024B478
    /* 14B478 0024B478 AAFF0324 */  addiu      $v1, $zero, -0x56
    /* 14B47C 0024B47C 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B480 0024B480 0800E003 */  jr         $ra
    /* 14B484 0024B484 00000000 */   nop
endlabel func_0024B478
