.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B458, 0x10

glabel func_0024B458
    /* 14B458 0024B458 ABFF0324 */  addiu      $v1, $zero, -0x55
    /* 14B45C 0024B45C 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B460 0024B460 0800E003 */  jr         $ra
    /* 14B464 0024B464 00000000 */   nop
endlabel func_0024B458
