.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B4A8, 0x10

glabel func_0024B4A8
    /* 14B4A8 0024B4A8 58000324 */  addiu      $v1, $zero, 0x58
    /* 14B4AC 0024B4AC 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B4B0 0024B4B0 0800E003 */  jr         $ra
    /* 14B4B4 0024B4B4 00000000 */   nop
endlabel func_0024B4A8
