.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function */
nonmatching func_0024B488, 0x10

glabel func_0024B488
    /* 14B488 0024B488 57000324 */  addiu      $v1, $zero, 0x57
    /* 14B48C 0024B48C 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B490 0024B490 0800E003 */  jr         $ra
    /* 14B494 0024B494 00000000 */   nop
endlabel func_0024B488
