.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024BFA4, 0x8

glabel func_0024BFA4
    /* 14BFA4 0024BFA4 0800E003 */  jr         $ra
    /* 14BFA8 0024BFA8 F0FFBD27 */   addiu     $sp, $sp, -0x10
endlabel func_0024BFA4
