.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024DCE4, 0x4

glabel func_0024DCE4
    /* 14DCE4 0024DCE4 00000000 */  nop
endlabel func_0024DCE4
