.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00251CF4, 0x4

glabel func_00251CF4
    /* 151CF4 00251CF4 00000000 */  nop
endlabel func_00251CF4
