.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00251E14, 0x4

glabel func_00251E14
    /* 151E14 00251E14 00000000 */  nop
endlabel func_00251E14
