.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00252434, 0x4

glabel func_00252434
    /* 152434 00252434 00000000 */  nop
endlabel func_00252434
