.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00258CCC, 0x4

glabel func_00258CCC
    /* 158CCC 00258CCC 00000000 */  nop
endlabel func_00258CCC
