.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025C5B4, 0x4

glabel func_0025C5B4
    /* 15C5B4 0025C5B4 00000000 */  nop
endlabel func_0025C5B4
