.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025C67C, 0x4

glabel func_0025C67C
    /* 15C67C 0025C67C 00000000 */  nop
endlabel func_0025C67C
