.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025CD0C, 0x4

glabel func_0025CD0C
    /* 15CD0C 0025CD0C 00000000 */  nop
endlabel func_0025CD0C
