.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025DD04, 0x4

glabel func_0025DD04
    /* 15DD04 0025DD04 00000000 */  nop
endlabel func_0025DD04
