.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025E034, 0x4

glabel func_0025E034
    /* 15E034 0025E034 00000000 */  nop
endlabel func_0025E034
