.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025E114, 0x4

glabel func_0025E114
    /* 15E114 0025E114 00000000 */  nop
endlabel func_0025E114
