.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00265B24, 0x4

glabel func_00265B24
    /* 165B24 00265B24 00000000 */  nop
endlabel func_00265B24
