.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0026A5EC, 0x4

glabel func_0026A5EC
    /* 16A5EC 0026A5EC 00000000 */  nop
endlabel func_0026A5EC
