.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0026B144, 0x4

glabel func_0026B144
    /* 16B144 0026B144 00000000 */  nop
endlabel func_0026B144
