.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0026D484, 0x4

glabel func_0026D484
    /* 16D484 0026D484 00000000 */  nop
endlabel func_0026D484
