.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00100A04, 0x4

glabel func_00100A04
    /* A04 00100A04 00000000 */  nop
endlabel func_00100A04

/* Handwritten function */
nonmatching func_00100A08, 0x68

glabel func_00100A08
    /* A08 00100A08 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* A0C 00100A0C 1000B1FF */  sd         $s1, 0x10($sp)
    /* A10 00100A10 2000BFFF */  sd         $ra, 0x20($sp)
    /* A14 00100A14 2D888000 */  daddu      $s1, $a0, $zero
    /* A18 00100A18 0000B0FF */  sd         $s0, 0x0($sp)
    /* A1C 00100A1C 00601040 */  mfc0       $s0, $12 /* handwritten instruction */
    /* A20 00100A20 0100023C */  lui        $v0, (0x10000 >> 16)
    /* A24 00100A24 24800202 */  and        $s0, $s0, $v0
    /* A28 00100A28 03000012 */  beqz       $s0, .L00100A38
    /* A2C 00100A2C 00000000 */   nop
    /* A30 00100A30 9006040C */  jal        func_00101A40
    /* A34 00100A34 00000000 */   nop
.align 2
  .L00100A38:
    /* A38 00100A38 9C00040C */  jal        func_00100270
    /* A3C 00100A3C 2D202002 */   daddu     $a0, $s1, $zero
    /* A40 00100A40 2D884000 */  daddu      $s1, $v0, $zero
    /* A44 00100A44 0F000000 */  sync
    /* A48 00100A48 04000012 */  beqz       $s0, .L00100A5C
    /* A4C 00100A4C 2D102002 */   daddu     $v0, $s1, $zero
    /* A50 00100A50 A206040C */  jal        func_00101A88
    /* A54 00100A54 00000000 */   nop
    /* A58 00100A58 2D102002 */  daddu      $v0, $s1, $zero
.align 2
  .L00100A5C:
    /* A5C 00100A5C 2000BFDF */  ld         $ra, 0x20($sp)
    /* A60 00100A60 1000B1DF */  ld         $s1, 0x10($sp)
    /* A64 00100A64 0000B0DF */  ld         $s0, 0x0($sp)
    /* A68 00100A68 0800E003 */  jr         $ra
    /* A6C 00100A6C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00100A08

/* Handwritten function */
nonmatching func_00100A70, 0x68

glabel func_00100A70
    /* A70 00100A70 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* A74 00100A74 1000B1FF */  sd         $s1, 0x10($sp)
    /* A78 00100A78 2000BFFF */  sd         $ra, 0x20($sp)
    /* A7C 00100A7C 2D888000 */  daddu      $s1, $a0, $zero
    /* A80 00100A80 0000B0FF */  sd         $s0, 0x0($sp)
    /* A84 00100A84 00601040 */  mfc0       $s0, $12 /* handwritten instruction */
    /* A88 00100A88 0100023C */  lui        $v0, (0x10000 >> 16)
    /* A8C 00100A8C 24800202 */  and        $s0, $s0, $v0
    /* A90 00100A90 03000012 */  beqz       $s0, .L00100AA0
    /* A94 00100A94 00000000 */   nop
    /* A98 00100A98 9006040C */  jal        func_00101A40
    /* A9C 00100A9C 00000000 */   nop
.align 2
  .L00100AA0:
    /* AA0 00100AA0 9800040C */  jal        func_00100260
    /* AA4 00100AA4 2D202002 */   daddu     $a0, $s1, $zero
    /* AA8 00100AA8 2D884000 */  daddu      $s1, $v0, $zero
    /* AAC 00100AAC 0F000000 */  sync
    /* AB0 00100AB0 04000012 */  beqz       $s0, .L00100AC4
    /* AB4 00100AB4 2D102002 */   daddu     $v0, $s1, $zero
    /* AB8 00100AB8 A206040C */  jal        func_00101A88
    /* ABC 00100ABC 00000000 */   nop
    /* AC0 00100AC0 2D102002 */  daddu      $v0, $s1, $zero
.align 2
  .L00100AC4:
    /* AC4 00100AC4 2000BFDF */  ld         $ra, 0x20($sp)
    /* AC8 00100AC8 1000B1DF */  ld         $s1, 0x10($sp)
    /* ACC 00100ACC 0000B0DF */  ld         $s0, 0x0($sp)
    /* AD0 00100AD0 0800E003 */  jr         $ra
    /* AD4 00100AD4 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00100A70

/* Handwritten function */
nonmatching func_00100AD8, 0x68

glabel func_00100AD8
    /* AD8 00100AD8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* ADC 00100ADC 1000B1FF */  sd         $s1, 0x10($sp)
    /* AE0 00100AE0 2000BFFF */  sd         $ra, 0x20($sp)
    /* AE4 00100AE4 2D888000 */  daddu      $s1, $a0, $zero
    /* AE8 00100AE8 0000B0FF */  sd         $s0, 0x0($sp)
    /* AEC 00100AEC 00601040 */  mfc0       $s0, $12 /* handwritten instruction */
    /* AF0 00100AF0 0100023C */  lui        $v0, (0x10000 >> 16)
    /* AF4 00100AF4 24800202 */  and        $s0, $s0, $v0
    /* AF8 00100AF8 03000012 */  beqz       $s0, .L00100B08
    /* AFC 00100AFC 00000000 */   nop
    /* B00 00100B00 9006040C */  jal        func_00101A40
    /* B04 00100B04 00000000 */   nop
.align 2
  .L00100B08:
    /* B08 00100B08 A400040C */  jal        func_00100290
    /* B0C 00100B0C 2D202002 */   daddu     $a0, $s1, $zero
    /* B10 00100B10 2D884000 */  daddu      $s1, $v0, $zero
    /* B14 00100B14 0F000000 */  sync
    /* B18 00100B18 04000012 */  beqz       $s0, .L00100B2C
    /* B1C 00100B1C 2D102002 */   daddu     $v0, $s1, $zero
    /* B20 00100B20 A206040C */  jal        func_00101A88
    /* B24 00100B24 00000000 */   nop
    /* B28 00100B28 2D102002 */  daddu      $v0, $s1, $zero
.align 2
  .L00100B2C:
    /* B2C 00100B2C 2000BFDF */  ld         $ra, 0x20($sp)
    /* B30 00100B30 1000B1DF */  ld         $s1, 0x10($sp)
    /* B34 00100B34 0000B0DF */  ld         $s0, 0x0($sp)
    /* B38 00100B38 0800E003 */  jr         $ra
    /* B3C 00100B3C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00100AD8

/* Handwritten function */
nonmatching func_00100B40, 0x68

glabel func_00100B40
    /* B40 00100B40 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* B44 00100B44 1000B1FF */  sd         $s1, 0x10($sp)
    /* B48 00100B48 2000BFFF */  sd         $ra, 0x20($sp)
    /* B4C 00100B4C 2D888000 */  daddu      $s1, $a0, $zero
    /* B50 00100B50 0000B0FF */  sd         $s0, 0x0($sp)
    /* B54 00100B54 00601040 */  mfc0       $s0, $12 /* handwritten instruction */
    /* B58 00100B58 0100023C */  lui        $v0, (0x10000 >> 16)
    /* B5C 00100B5C 24800202 */  and        $s0, $s0, $v0
    /* B60 00100B60 03000012 */  beqz       $s0, .L00100B70
    /* B64 00100B64 00000000 */   nop
    /* B68 00100B68 9006040C */  jal        func_00101A40
    /* B6C 00100B6C 00000000 */   nop
.align 2
  .L00100B70:
    /* B70 00100B70 A000040C */  jal        func_00100280
    /* B74 00100B74 2D202002 */   daddu     $a0, $s1, $zero
    /* B78 00100B78 2D884000 */  daddu      $s1, $v0, $zero
    /* B7C 00100B7C 0F000000 */  sync
    /* B80 00100B80 04000012 */  beqz       $s0, .L00100B94
    /* B84 00100B84 2D102002 */   daddu     $v0, $s1, $zero
    /* B88 00100B88 A206040C */  jal        func_00101A88
    /* B8C 00100B8C 00000000 */   nop
    /* B90 00100B90 2D102002 */  daddu      $v0, $s1, $zero
.align 2
  .L00100B94:
    /* B94 00100B94 2000BFDF */  ld         $ra, 0x20($sp)
    /* B98 00100B98 1000B1DF */  ld         $s1, 0x10($sp)
    /* B9C 00100B9C 0000B0DF */  ld         $s0, 0x0($sp)
    /* BA0 00100BA0 0800E003 */  jr         $ra
    /* BA4 00100BA4 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00100B40
