.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
/* Handwritten function — COP0 status read + EI + return prev EIE state.
 * See ps2sdk's EnableIntc() pattern. */
nonmatching func_00101A88, 0x18

glabel func_00101A88
    /* 1A88 00101A88 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 1A8C 00101A8C 0100033C */  lui        $v1, (0x10000 >> 16)
    /* 1A90 00101A90 24104300 */  and        $v0, $v0, $v1
    /* 1A94 00101A94 38000042 */  ei /* handwritten instruction */
    /* 1A98 00101A98 0800E003 */  jr         $ra
    /* 1A9C 00101A9C 2B100200 */   sltu      $v0, $zero, $v0
endlabel func_00101A88
