.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00101B9C, 0x4

glabel func_00101B9C
    /* 1B9C 00101B9C 00000000 */  nop
endlabel func_00101B9C
