.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00101B64, 0x4

glabel func_00101B64
    /* 1B64 00101B64 00000000 */  nop
endlabel func_00101B64
