.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00101C54, 0x4

glabel func_00101C54
    /* 1C54 00101C54 00000000 */  nop
endlabel func_00101C54
