.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00104F1C, 0x4

glabel func_00104F1C
    /* 4F1C 00104F1C 00000000 */  nop
endlabel func_00104F1C
