.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0010A15C, 0x4

glabel func_0010A15C
    /* A15C 0010A15C 00000000 */  nop
endlabel func_0010A15C
