.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0010D424, 0x4

glabel func_0010D424
    /* D424 0010D424 00000000 */  nop
endlabel func_0010D424
