.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0011193C, 0x4

glabel func_0011193C
    /* 1193C 0011193C 100045AC */  sw         $a1, 0x10($v0)
endlabel func_0011193C
