.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00117FE4, 0x4

glabel func_00117FE4
    /* 17FE4 00117FE4 00000000 */  nop
endlabel func_00117FE4
