.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0011815C, 0x4

glabel func_0011815C
    /* 1815C 0011815C 00000000 */  nop
endlabel func_0011815C
