.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00118544, 0x4

glabel func_00118544
    /* 18544 00118544 00000000 */  nop
endlabel func_00118544
