.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00122C7C, 0x4

glabel func_00122C7C
    /* 22C7C 00122C7C 00000000 */  nop
endlabel func_00122C7C
