.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00136084, 0x4

glabel func_00136084
    /* 36084 00136084 00000000 */  nop
endlabel func_00136084
