.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00137F88, 0x4

glabel func_00137F88
    /* 37F88 00137F88 1000BD27 */  addiu      $sp, $sp, 0x10
endlabel func_00137F88
    /* 37F8C 00137F8C 00000000 */  nop
