.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00137FD0, 0x4

glabel func_00137FD0
    /* 37FD0 00137FD0 1000BD27 */  addiu      $sp, $sp, 0x10
endlabel func_00137FD0
    /* 37FD4 00137FD4 00000000 */  nop
