.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00138060, 0x4

glabel func_00138060
    /* 38060 00138060 1000BD27 */  addiu      $sp, $sp, 0x10
endlabel func_00138060
    /* 38064 00138064 00000000 */  nop
