.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00138018, 0x4

glabel func_00138018
    /* 38018 00138018 1000BD27 */  addiu      $sp, $sp, 0x10
endlabel func_00138018
    /* 3801C 0013801C 00000000 */  nop
