.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001380F0, 0x4

glabel func_001380F0
    /* 380F0 001380F0 1000BD27 */  addiu      $sp, $sp, 0x10
endlabel func_001380F0
    /* 380F4 001380F4 00000000 */  nop
