.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00138180, 0x8

glabel func_00138180
    /* 38180 00138180 0800E003 */  jr         $ra
    /* 38184 00138184 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_00138180
