.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00138214, 0x4

glabel func_00138214
    /* 38214 00138214 00000000 */  nop
endlabel func_00138214
