.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001383D4, 0x4

glabel func_001383D4
    /* 383D4 001383D4 00000000 */  nop
endlabel func_001383D4
