.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013A21C, 0x4

glabel func_0013A21C
    /* 3A21C 0013A21C 00000000 */  nop
endlabel func_0013A21C
