.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013F874, 0x4

glabel func_0013F874
    /* 3F874 0013F874 00000000 */  nop
endlabel func_0013F874
