.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0013F804, 0x4

glabel func_0013F804
    /* 3F804 0013F804 00000000 */  nop
endlabel func_0013F804
