.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0015EE74, 0x4

glabel func_0015EE74
    /* 5EE74 0015EE74 00000000 */  nop
endlabel func_0015EE74
