.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0015F224, 0x4

glabel func_0015F224
    /* 5F224 0015F224 00000000 */  nop
endlabel func_0015F224
