.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0015F31C, 0x4

glabel func_0015F31C
    /* 5F31C 0015F31C 00000000 */  nop
endlabel func_0015F31C
