.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0015F54C, 0x4

glabel func_0015F54C
    /* 5F54C 0015F54C 00000000 */  nop
endlabel func_0015F54C
