.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00166024, 0x4

glabel func_00166024
    /* 66024 00166024 00000000 */  nop
endlabel func_00166024
