.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00178924, 0x4

glabel func_00178924
    /* 78924 00178924 00000000 */  nop
endlabel func_00178924
