.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017B1EC, 0x4

glabel func_0017B1EC
    /* 7B1EC 0017B1EC 00000000 */  nop
endlabel func_0017B1EC
