.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017B254, 0x4

glabel func_0017B254
    /* 7B254 0017B254 00000000 */  nop
endlabel func_0017B254
