.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017B314, 0x4

glabel func_0017B314
    /* 7B314 0017B314 00000000 */  nop
endlabel func_0017B314
