.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017C8F4, 0x4

glabel func_0017C8F4
    /* 7C8F4 0017C8F4 00000000 */  nop
endlabel func_0017C8F4
