.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017C92C, 0x4

glabel func_0017C92C
    /* 7C92C 0017C92C 00000000 */  nop
endlabel func_0017C92C
