.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0017D0CC, 0x4

glabel func_0017D0CC
    /* 7D0CC 0017D0CC 00000000 */  nop
endlabel func_0017D0CC
