.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001873BC, 0x4

glabel func_001873BC
    /* 873BC 001873BC 00000000 */  nop
endlabel func_001873BC
