.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00187904, 0x4

glabel func_00187904
    /* 87904 00187904 00000000 */  nop
endlabel func_00187904
