.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0018CEEC, 0x4

glabel func_0018CEEC
    /* 8CEEC 0018CEEC 00000000 */  nop
endlabel func_0018CEEC
