.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0018CFDC, 0x4

glabel func_0018CFDC
    /* 8CFDC 0018CFDC 00000000 */  nop
endlabel func_0018CFDC
