.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0018CFEC, 0x4

glabel func_0018CFEC
    /* 8CFEC 0018CFEC 00000000 */  nop
endlabel func_0018CFEC
