.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001939D4, 0x4

glabel func_001939D4
    /* 939D4 001939D4 00000000 */  nop
endlabel func_001939D4
