.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0019E51C, 0x4

glabel func_0019E51C
    /* 9E51C 0019E51C 00000000 */  nop
endlabel func_0019E51C

/* Handwritten function */
nonmatching func_0019E520, 0x78

glabel func_0019E520
    /* 9E520 0019E520 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 9E524 0019E524 0000B0FF */  sd         $s0, 0x0($sp)
    /* 9E528 0019E528 1000BFFF */  sd         $ra, 0x10($sp)
    /* 9E52C 0019E52C 9006040C */  jal        func_00101A40
    /* 9E530 0019E530 2D808000 */   daddu     $s0, $a0, $zero
    /* 9E534 0019E534 0800038E */  lw         $v1, 0x8($s0)
    /* 9E538 0019E538 0A00023C */  lui        $v0, (0xA0A40 >> 16)
    /* 9E53C 0019E53C 400A4234 */  ori        $v0, $v0, (0xA0A40 & 0xFFFF)
    /* 9E540 0019E540 0400058E */  lw         $a1, 0x4($s0)
    /* 9E544 0019E544 18186200 */  mult       $v1, $v1, $v0
    /* 9E548 0019E548 02000424 */  addiu      $a0, $zero, 0x2
    /* 9E54C 0019E54C 21186500 */  addu       $v1, $v1, $a1
    /* 9E550 0019E550 000064AC */  sw         $a0, 0x0($v1)
    /* 9E554 0019E554 0C00028E */  lw         $v0, 0xC($s0)
    /* 9E558 0019E558 1000048E */  lw         $a0, 0x10($s0)
    /* 9E55C 0019E55C 01004224 */  addiu      $v0, $v0, 0x1
    /* 9E560 0019E560 0C0002AE */  sw         $v0, 0xC($s0)
    /* 9E564 0019E564 01008050 */  beql       $a0, $zero, .L0019E56C
    /* 9E568 0019E568 CD010000 */   break     0, 7
.align 2
  .L0019E56C:
    /* 9E56C 0019E56C 0800028E */  lw         $v0, 0x8($s0)
    /* 9E570 0019E570 01004224 */  addiu      $v0, $v0, 0x1
    /* 9E574 0019E574 1A004400 */  div        $zero, $v0, $a0
    /* 9E578 0019E578 10180000 */  mfhi       $v1
    /* 9E57C 0019E57C 080003AE */  sw         $v1, 0x8($s0)
    /* 9E580 0019E580 0F000000 */  sync
    /* 9E584 0019E584 38000042 */  ei /* handwritten instruction */
    /* 9E588 0019E588 1000BFDF */  ld         $ra, 0x10($sp)
    /* 9E58C 0019E58C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 9E590 0019E590 0800E003 */  jr         $ra
    /* 9E594 0019E594 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0019E520
