.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001A6E00, 0x24

glabel func_001A6E00
    /* A6E00 001A6E00 90FFBD27 */  addiu      $sp, $sp, -0x70
    /* A6E04 001A6E04 4000A6FF */  sd         $a2, 0x40($sp)
    /* A6E08 001A6E08 4800A7FF */  sd         $a3, 0x48($sp)
    /* A6E0C 001A6E0C 5000A8FF */  sd         $t0, 0x50($sp)
    /* A6E10 001A6E10 5800A9FF */  sd         $t1, 0x58($sp)
    /* A6E14 001A6E14 6000AAFF */  sd         $t2, 0x60($sp)
    /* A6E18 001A6E18 6800ABFF */  sd         $t3, 0x68($sp)
    /* A6E1C 001A6E1C 0800E003 */  jr         $ra
    /* A6E20 001A6E20 7000BD27 */   addiu     $sp, $sp, 0x70
endlabel func_001A6E00
