.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AA57C, 0x4

glabel func_001AA57C
    /* AA57C 001AA57C 00000000 */  nop
endlabel func_001AA57C
