.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AA65C, 0x4

glabel func_001AA65C
    /* AA65C 001AA65C 00000000 */  nop
endlabel func_001AA65C
