.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AAE9C, 0x4

glabel func_001AAE9C
    /* AAE9C 001AAE9C 00000000 */  nop
endlabel func_001AAE9C
