.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AB1B4, 0x4

glabel func_001AB1B4
    /* AB1B4 001AB1B4 00000000 */  nop
endlabel func_001AB1B4
