.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AB334, 0x4

glabel func_001AB334
    /* AB334 001AB334 00000000 */  nop
endlabel func_001AB334
