.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_001AD748, 0x1C

glabel func_001AD748
    /* AD748 001AD748 00000000 */  nop
    /* AD74C 001AD74C 00000000 */  nop
    /* AD750 001AD750 00000000 */  nop
    /* AD754 001AD754 00000000 */  nop
    /* AD758 001AD758 00000000 */  nop
    /* AD75C 001AD75C FAFF0010 */  b          func_001AD748
    /* AD760 001AD760 00000000 */   nop
endlabel func_001AD748
