.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AE3E4, 0x4

glabel func_001AE3E4
    /* AE3E4 001AE3E4 00000000 */  nop
endlabel func_001AE3E4
