.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AE82C, 0x4

glabel func_001AE82C
    /* AE82C 001AE82C 00000000 */  nop
endlabel func_001AE82C
