.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001AE9EC, 0x4

glabel func_001AE9EC
    /* AE9EC 001AE9EC 00000000 */  nop
endlabel func_001AE9EC
