.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001B5994, 0x4

glabel func_001B5994
    /* B5994 001B5994 00000000 */  nop
endlabel func_001B5994
