.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001BA7E4, 0x4

glabel func_001BA7E4
    /* BA7E4 001BA7E4 00000000 */  nop
endlabel func_001BA7E4
