.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001BB85C, 0x4

glabel func_001BB85C
    /* BB85C 001BB85C 00000000 */  nop
endlabel func_001BB85C
