.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001BBFCC, 0x4

glabel func_001BBFCC
    /* BBFCC 001BBFCC 00000000 */  nop
endlabel func_001BBFCC
