.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001C8E74, 0x4

glabel func_001C8E74
    /* C8E74 001C8E74 00000000 */  nop
endlabel func_001C8E74
