.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001C9324, 0x4

glabel func_001C9324
    /* C9324 001C9324 00000000 */  nop
endlabel func_001C9324
