.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001CE75C, 0x4

glabel func_001CE75C
    /* CE75C 001CE75C 00000000 */  nop
endlabel func_001CE75C
