.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001CE994, 0x4

glabel func_001CE994
    /* CE994 001CE994 00000000 */  nop
endlabel func_001CE994
