.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001D03DC, 0x4

glabel func_001D03DC
    /* D03DC 001D03DC 00000000 */  nop
endlabel func_001D03DC
