.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001D12BC, 0x4

glabel func_001D12BC
    /* D12BC 001D12BC 00000000 */  nop
endlabel func_001D12BC
