.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001D143C, 0x4

glabel func_001D143C
    /* D143C 001D143C 00000000 */  nop
endlabel func_001D143C
