.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001E990C, 0x4

glabel func_001E990C
    /* E990C 001E990C 00000000 */  nop
endlabel func_001E990C
