.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001EF9CC, 0x4

glabel func_001EF9CC
    /* EF9CC 001EF9CC 00000000 */  nop
endlabel func_001EF9CC
