.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001EFA54, 0x4

glabel func_001EFA54
    /* EFA54 001EFA54 00000000 */  nop
endlabel func_001EFA54
