.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001F23BC, 0x4

glabel func_001F23BC
    /* F23BC 001F23BC 00000000 */  nop
endlabel func_001F23BC
