.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001FAA4C, 0x4

glabel func_001FAA4C
    /* FAA4C 001FAA4C 00000000 */  nop
endlabel func_001FAA4C
