.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_001FC2CC, 0x4

glabel func_001FC2CC
    /* FC2CC 001FC2CC 00000000 */  nop
endlabel func_001FC2CC
