.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0020566C, 0x4

glabel func_0020566C
    /* 10566C 0020566C 00000000 */  nop
endlabel func_0020566C
