.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00205B2C, 0x4

glabel func_00205B2C
    /* 105B2C 00205B2C 00000000 */  nop
endlabel func_00205B2C
