.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002194C4, 0x4

glabel func_002194C4
    /* 1194C4 002194C4 00000000 */  nop
endlabel func_002194C4
