.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0021F5F4, 0x4

glabel func_0021F5F4
    /* 11F5F4 0021F5F4 00000000 */  nop
endlabel func_0021F5F4
