.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00229E34, 0x4

glabel func_00229E34
    /* 129E34 00229E34 00000000 */  nop
endlabel func_00229E34
