.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0023D04C, 0x4

glabel func_0023D04C
    /* 13D04C 0023D04C 00000000 */  nop
endlabel func_0023D04C
