.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0023E294, 0x4

glabel func_0023E294
    /* 13E294 0023E294 00000000 */  nop
endlabel func_0023E294
