.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0023E32C, 0x4

glabel func_0023E32C
    /* 13E32C 0023E32C 00000000 */  nop
endlabel func_0023E32C
