.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0023EE24, 0x4

glabel func_0023EE24
    /* 13EE24 0023EE24 00000000 */  nop
endlabel func_0023EE24

/* Handwritten function */
nonmatching func_0023EE28, 0x188

glabel func_0023EE28
    /* 13EE28 0023EE28 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 13EE2C 0023EE2C 0012023C */  lui        $v0, (0x12001000 >> 16)
    /* 13EE30 0023EE30 2000BFFF */  sd         $ra, 0x20($sp)
    /* 13EE34 0023EE34 00104234 */  ori        $v0, $v0, (0x12001000 & 0xFFFF)
    /* 13EE38 0023EE38 1000B1FF */  sd         $s1, 0x10($sp)
    /* 13EE3C 0023EE3C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 13EE40 0023EE40 000043DC */  ld         $v1, 0x0($v0)
    /* 13EE44 0023EE44 7A1B0300 */  dsrl       $v1, $v1, 13
    /* 13EE48 0023EE48 01006330 */  andi       $v1, $v1, 0x1
    /* 13EE4C 0023EE4C 3C180300 */  dsll32     $v1, $v1, 0
    /* 13EE50 0023EE50 3F180300 */  dsra32     $v1, $v1, 0
    /* 13EE54 0023EE54 A0B283AF */  sw         $v1, %gp_rel(D_00633B90)($gp)
    /* 13EE58 0023EE58 98B2828F */  lw         $v0, %gp_rel(D_00633B88)($gp)
    /* 13EE5C 0023EE5C 4C004010 */  beqz       $v0, .L0023EF90
    /* 13EE60 0023EE60 00000000 */   nop
    /* 13EE64 0023EE64 94B2828F */  lw         $v0, %gp_rel(D_00633B84)($gp)
    /* 13EE68 0023EE68 01000424 */  addiu      $a0, $zero, 0x1
    /* 13EE6C 0023EE6C 2D280000 */  daddu      $a1, $zero, $zero
    /* 13EE70 0023EE70 01004224 */  addiu      $v0, $v0, 0x1
    /* 13EE74 0023EE74 94B282AF */  sw         $v0, %gp_rel(D_00633B84)($gp)
    /* 13EE78 0023EE78 9009090C */  jal        func_00242640
    /* 13EE7C 0023EE7C 00000000 */   nop
    /* 13EE80 0023EE80 A4B282AF */  sw         $v0, %gp_rel(D_00633B94)($gp)
    /* 13EE84 0023EE84 A4B2828F */  lw         $v0, %gp_rel(D_00633B94)($gp)
    /* 13EE88 0023EE88 41004014 */  bnez       $v0, .L0023EF90
    /* 13EE8C 0023EE8C 2900043C */   lui       $a0, %hi(D_0028CA30)
    /* 13EE90 0023EE90 7479060C */  jal        func_0019E5D0
    /* 13EE94 0023EE94 30CA8424 */   addiu     $a0, $a0, %lo(D_0028CA30)
    /* 13EE98 0023EE98 2D804000 */  daddu      $s0, $v0, $zero
    /* 13EE9C 0023EE9C 07000016 */  bnez       $s0, .L0023EEBC
    /* 13EEA0 0023EEA0 ECB6828F */   lw        $v0, %gp_rel(D_00633FDC)($gp)
    /* 13EEA4 0023EEA4 01004224 */  addiu      $v0, $v0, 0x1
    /* 13EEA8 0023EEA8 ECB682AF */  sw         $v0, %gp_rel(D_00633FDC)($gp)
    /* 13EEAC 0023EEAC 0F000000 */  sync
    /* 13EEB0 0023EEB0 38000042 */  ei /* handwritten instruction */
    /* 13EEB4 0023EEB4 39000010 */  b          .L0023EF9C
    /* 13EEB8 0023EEB8 2D100000 */   daddu     $v0, $zero, $zero
.align 2
  .L0023EEBC:
    /* 13EEBC 0023EEBC A0B2828F */  lw         $v0, %gp_rel(D_00633B90)($gp)
    /* 13EEC0 0023EEC0 1A004014 */  bnez       $v0, .L0023EF2C
    /* 13EEC4 0023EEC4 02000224 */   addiu     $v0, $zero, 0x2
    /* 13EEC8 0023EEC8 0000038E */  lw         $v1, 0x0($s0)
    /* 13EECC 0023EECC 17006214 */  bne        $v1, $v0, .L0023EF2C
    /* 13EED0 0023EED0 2900043C */   lui       $a0, %hi(D_0028CA48)
    /* 13EED4 0023EED4 2D280000 */  daddu      $a1, $zero, $zero
    /* 13EED8 0023EED8 7CFB080C */  jal        func_0023EDF0
    /* 13EEDC 0023EEDC 48CA8424 */   addiu     $a0, $a0, %lo(D_0028CA48)
    /* 13EEE0 0023EEE0 0200023C */  lui        $v0, (0x20240 >> 16)
    /* 13EEE4 0023EEE4 FF0F043C */  lui        $a0, (0xFFFFFFF >> 16)
    /* 13EEE8 0023EEE8 40024234 */  ori        $v0, $v0, (0x20240 & 0xFFFF)
    /* 13EEEC 0023EEEC FFFF8434 */  ori        $a0, $a0, (0xFFFFFFF & 0xFFFF)
    /* 13EEF0 0023EEF0 21100202 */  addu       $v0, $s0, $v0
    /* 13EEF4 0023EEF4 0010033C */  lui        $v1, (0x1000A030 >> 16)
    /* 13EEF8 0023EEF8 24104400 */  and        $v0, $v0, $a0
    /* 13EEFC 0023EEFC 30A06334 */  ori        $v1, $v1, (0x1000A030 & 0xFFFF)
    /* 13EF00 0023EF00 000062AC */  sw         $v0, 0x0($v1)
    /* 13EF04 0023EF04 0010043C */  lui        $a0, (0x1000A020 >> 16)
    /* 13EF08 0023EF08 20A08434 */  ori        $a0, $a0, (0x1000A020 & 0xFFFF)
    /* 13EF0C 0023EF0C 0010023C */  lui        $v0, (0x1000A000 >> 16)
    /* 13EF10 0023EF10 000080AC */  sw         $zero, 0x0($a0)
    /* 13EF14 0023EF14 00A04234 */  ori        $v0, $v0, (0x1000A000 & 0xFFFF)
    /* 13EF18 0023EF18 05010324 */  addiu      $v1, $zero, 0x105
    /* 13EF1C 0023EF1C 01000424 */  addiu      $a0, $zero, 0x1
    /* 13EF20 0023EF20 000043AC */  sw         $v1, 0x0($v0)
    /* 13EF24 0023EF24 1A000010 */  b          .L0023EF90
    /* 13EF28 0023EF28 000004AE */   sw        $a0, 0x0($s0)
.align 2
  .L0023EF2C:
    /* 13EF2C 0023EF2C A0B2828F */  lw         $v0, %gp_rel(D_00633B90)($gp)
    /* 13EF30 0023EF30 17004010 */  beqz       $v0, .L0023EF90
    /* 13EF34 0023EF34 01000224 */   addiu     $v0, $zero, 0x1
    /* 13EF38 0023EF38 0000118E */  lw         $s1, 0x0($s0)
    /* 13EF3C 0023EF3C 14002216 */  bne        $s1, $v0, .L0023EF90
    /* 13EF40 0023EF40 2900043C */   lui       $a0, %hi(D_0028CA48)
    /* 13EF44 0023EF44 01000524 */  addiu      $a1, $zero, 0x1
    /* 13EF48 0023EF48 7CFB080C */  jal        func_0023EDF0
    /* 13EF4C 0023EF4C 48CA8424 */   addiu     $a0, $a0, %lo(D_0028CA48)
    /* 13EF50 0023EF50 FF0F023C */  lui        $v0, (0xFFFFFFF >> 16)
    /* 13EF54 0023EF54 40000426 */  addiu      $a0, $s0, 0x40
    /* 13EF58 0023EF58 FFFF4234 */  ori        $v0, $v0, (0xFFFFFFF & 0xFFFF)
    /* 13EF5C 0023EF5C 0010033C */  lui        $v1, (0x1000A030 >> 16)
    /* 13EF60 0023EF60 24208200 */  and        $a0, $a0, $v0
    /* 13EF64 0023EF64 30A06334 */  ori        $v1, $v1, (0x1000A030 & 0xFFFF)
    /* 13EF68 0023EF68 0010023C */  lui        $v0, (0x1000A020 >> 16)
    /* 13EF6C 0023EF6C 000064AC */  sw         $a0, 0x0($v1)
    /* 13EF70 0023EF70 20A04234 */  ori        $v0, $v0, (0x1000A020 & 0xFFFF)
    /* 13EF74 0023EF74 0010033C */  lui        $v1, (0x1000A000 >> 16)
    /* 13EF78 0023EF78 000040AC */  sw         $zero, 0x0($v0)
    /* 13EF7C 0023EF7C 00A06334 */  ori        $v1, $v1, (0x1000A000 & 0xFFFF)
    /* 13EF80 0023EF80 05010224 */  addiu      $v0, $zero, 0x105
    /* 13EF84 0023EF84 000062AC */  sw         $v0, 0x0($v1)
    /* 13EF88 0023EF88 000000AE */  sw         $zero, 0x0($s0)
    /* 13EF8C 0023EF8C 9CB291AF */  sw         $s1, %gp_rel(D_00633B8C)($gp)
.align 2
  .L0023EF90:
    /* 13EF90 0023EF90 0F000000 */  sync
    /* 13EF94 0023EF94 38000042 */  ei /* handwritten instruction */
    /* 13EF98 0023EF98 2D100000 */  daddu      $v0, $zero, $zero
.align 2
  .L0023EF9C:
    /* 13EF9C 0023EF9C 2000BFDF */  ld         $ra, 0x20($sp)
    /* 13EFA0 0023EFA0 1000B1DF */  ld         $s1, 0x10($sp)
    /* 13EFA4 0023EFA4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 13EFA8 0023EFA8 0800E003 */  jr         $ra
    /* 13EFAC 0023EFAC 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0023EE28
