.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0023F95C, 0x4

glabel func_0023F95C
    /* 13F95C 0023F95C 00000000 */  nop
endlabel func_0023F95C

nonmatching func_0023F960, 0x1C0

glabel func_0023F960
    /* 13F960 0023F960 80FFBD27 */  addiu      $sp, $sp, -0x80
    /* 13F964 0023F964 6200023C */  lui        $v0, %hi(D_0061C6C8)
    /* 13F968 0023F968 3000B1FF */  sd         $s1, 0x30($sp)
    /* 13F96C 0023F96C 0800053C */  lui        $a1, (0x80000 >> 16)
    /* 13F970 0023F970 6000B4FF */  sd         $s4, 0x60($sp)
    /* 13F974 0023F974 2D888000 */  daddu      $s1, $a0, $zero
    /* 13F978 0023F978 4000B2FF */  sd         $s2, 0x40($sp)
    /* 13F97C 0023F97C 40000624 */  addiu      $a2, $zero, 0x40
    /* 13F980 0023F980 7000BFFF */  sd         $ra, 0x70($sp)
    /* 13F984 0023F984 C8C65224 */  addiu      $s2, $v0, %lo(D_0061C6C8)
    /* 13F988 0023F988 5000B3FF */  sd         $s3, 0x50($sp)
    /* 13F98C 0023F98C 2D384002 */  daddu      $a3, $s2, $zero
    /* 13F990 0023F990 2000B0FF */  sd         $s0, 0x20($sp)
    /* 13F994 0023F994 2A000824 */  addiu      $t0, $zero, 0x2A
    /* 13F998 0023F998 600020A2 */  sb         $zero, 0x60($s1)
    /* 13F99C 0023F99C AAE4040C */  jal        func_001392A8
    /* 13F9A0 0023F9A0 5097848F */   lw        $a0, %gp_rel(D_00632040)($gp)
    /* 13F9A4 0023F9A4 2DA04000 */  daddu      $s4, $v0, $zero
    /* 13F9A8 0023F9A8 0A008016 */  bnez       $s4, .L0023F9D4
    /* 13F9AC 0023F9AC 2D208002 */   daddu     $a0, $s4, $zero
    /* 13F9B0 0023F9B0 2D204002 */  daddu      $a0, $s2, $zero
    /* 13F9B4 0023F9B4 DAB5060C */  jal        func_001AD768
    /* 13F9B8 0023F9B8 2B000524 */   addiu     $a1, $zero, 0x2B
    /* 13F9BC 0023F9BC 6200063C */  lui        $a2, %hi(D_0061C6E8)
    /* 13F9C0 0023F9C0 2D204002 */  daddu      $a0, $s2, $zero
    /* 13F9C4 0023F9C4 E8C6C624 */  addiu      $a2, $a2, %lo(D_0061C6E8)
    /* 13F9C8 0023F9C8 FC8F090C */  jal        func_00263FF0
    /* 13F9CC 0023F9CC 2B000524 */   addiu     $a1, $zero, 0x2B
    /* 13F9D0 0023F9D0 2D208002 */  daddu      $a0, $s4, $zero
.align 2
  .L0023F9D4:
    /* 13F9D4 0023F9D4 2D280000 */  daddu      $a1, $zero, $zero
    /* 13F9D8 0023F9D8 7690090C */  jal        func_002641D8
    /* 13F9DC 0023F9DC 0800063C */   lui       $a2, (0x80000 >> 16)
    /* 13F9E0 0023F9E0 2D008012 */  beqz       $s4, .L0023FA98
    /* 13F9E4 0023F9E4 5097848F */   lw        $a0, %gp_rel(D_00632040)($gp)
    /* 13F9E8 0023F9E8 10100524 */  addiu      $a1, $zero, 0x1010
    /* 13F9EC 0023F9EC 40000624 */  addiu      $a2, $zero, 0x40
    /* 13F9F0 0023F9F0 2D384002 */  daddu      $a3, $s2, $zero
    /* 13F9F4 0023F9F4 AAE4040C */  jal        func_001392A8
    /* 13F9F8 0023F9F8 2A000824 */   addiu     $t0, $zero, 0x2A
    /* 13F9FC 0023F9FC 2D984000 */  daddu      $s3, $v0, $zero
    /* 13FA00 0023FA00 0A006016 */  bnez       $s3, .L0023FA2C
    /* 13FA04 0023FA04 2D206002 */   daddu     $a0, $s3, $zero
    /* 13FA08 0023FA08 2D204002 */  daddu      $a0, $s2, $zero
    /* 13FA0C 0023FA0C DAB5060C */  jal        func_001AD768
    /* 13FA10 0023FA10 2B000524 */   addiu     $a1, $zero, 0x2B
    /* 13FA14 0023FA14 6200063C */  lui        $a2, %hi(D_0061C6E8)
    /* 13FA18 0023FA18 2D204002 */  daddu      $a0, $s2, $zero
    /* 13FA1C 0023FA1C E8C6C624 */  addiu      $a2, $a2, %lo(D_0061C6E8)
    /* 13FA20 0023FA20 FC8F090C */  jal        func_00263FF0
    /* 13FA24 0023FA24 2B000524 */   addiu     $a1, $zero, 0x2B
    /* 13FA28 0023FA28 2D206002 */  daddu      $a0, $s3, $zero
.align 2
  .L0023FA2C:
    /* 13FA2C 0023FA2C 2D280000 */  daddu      $a1, $zero, $zero
    /* 13FA30 0023FA30 7690090C */  jal        func_002641D8
    /* 13FA34 0023FA34 10100624 */   addiu     $a2, $zero, 0x1010
    /* 13FA38 0023FA38 17006012 */  beqz       $s3, .L0023FA98
    /* 13FA3C 0023FA3C 5097848F */   lw        $a0, %gp_rel(D_00632040)($gp)
    /* 13FA40 0023FA40 00300524 */  addiu      $a1, $zero, 0x3000
    /* 13FA44 0023FA44 04000624 */  addiu      $a2, $zero, 0x4
    /* 13FA48 0023FA48 2D384002 */  daddu      $a3, $s2, $zero
    /* 13FA4C 0023FA4C AAE4040C */  jal        func_001392A8
    /* 13FA50 0023FA50 2A000824 */   addiu     $t0, $zero, 0x2A
    /* 13FA54 0023FA54 2D804000 */  daddu      $s0, $v0, $zero
    /* 13FA58 0023FA58 0A000016 */  bnez       $s0, .L0023FA84
    /* 13FA5C 0023FA5C 2D200002 */   daddu     $a0, $s0, $zero
    /* 13FA60 0023FA60 2D204002 */  daddu      $a0, $s2, $zero
    /* 13FA64 0023FA64 DAB5060C */  jal        func_001AD768
    /* 13FA68 0023FA68 2B000524 */   addiu     $a1, $zero, 0x2B
    /* 13FA6C 0023FA6C 6200063C */  lui        $a2, %hi(D_0061C6E8)
    /* 13FA70 0023FA70 2D204002 */  daddu      $a0, $s2, $zero
    /* 13FA74 0023FA74 E8C6C624 */  addiu      $a2, $a2, %lo(D_0061C6E8)
    /* 13FA78 0023FA78 FC8F090C */  jal        func_00263FF0
    /* 13FA7C 0023FA7C 2B000524 */   addiu     $a1, $zero, 0x2B
    /* 13FA80 0023FA80 2D200002 */  daddu      $a0, $s0, $zero
.align 2
  .L0023FA84:
    /* 13FA84 0023FA84 2D280000 */  daddu      $a1, $zero, $zero
    /* 13FA88 0023FA88 7690090C */  jal        func_002641D8
    /* 13FA8C 0023FA8C 00300624 */   addiu     $a2, $zero, 0x3000
    /* 13FA90 0023FA90 03000016 */  bnez       $s0, .L0023FAA0
    /* 13FA94 0023FA94 00010224 */   addiu     $v0, $zero, 0x100
.align 2
  .L0023FA98:
    /* 13FA98 0023FA98 19000010 */  b          .L0023FB00
    /* 13FA9C 0023FA9C FFFF0224 */   addiu     $v0, $zero, -0x1
.align 2
  .L0023FAA0:
    /* 13FAA0 0023FAA0 FF0F033C */  lui        $v1, (0xFFFFFFF >> 16)
    /* 13FAA4 0023FAA4 080022AE */  sw         $v0, 0x8($s1)
    /* 13FAA8 0023FAA8 FFFF6334 */  ori        $v1, $v1, (0xFFFFFFF & 0xFFFF)
    /* 13FAAC 0023FAAC 00020224 */  addiu      $v0, $zero, 0x200
    /* 13FAB0 0023FAB0 0020043C */  lui        $a0, (0x20000000 >> 16)
    /* 13FAB4 0023FAB4 540022AE */  sw         $v0, 0x54($s1)
    /* 13FAB8 0023FAB8 24186302 */  and        $v1, $s3, $v1
    /* 13FABC 0023FABC 500030AE */  sw         $s0, 0x50($s1)
    /* 13FAC0 0023FAC0 25186400 */  or         $v1, $v1, $a0
    /* 13FAC4 0023FAC4 0800023C */  lui        $v0, (0x80000 >> 16)
    /* 13FAC8 0023FAC8 000034AE */  sw         $s4, 0x0($s1)
    /* 13FACC 0023FACC 01001024 */  addiu      $s0, $zero, 0x1
    /* 13FAD0 0023FAD0 040023AE */  sw         $v1, 0x4($s1)
    /* 13FAD4 0023FAD4 180022AE */  sw         $v0, 0x18($s1)
    /* 13FAD8 0023FAD8 2D20A003 */  daddu      $a0, $sp, $zero
    /* 13FADC 0023FADC 0800B0AF */  sw         $s0, 0x8($sp)
    /* 13FAE0 0023FAE0 4801040C */  jal        func_00100520
    /* 13FAE4 0023FAE4 0400B0AF */   sw        $s0, 0x4($sp)
    /* 13FAE8 0023FAE8 600030A2 */  sb         $s0, 0x60($s1)
    /* 13FAEC 0023FAEC 2D202002 */  daddu      $a0, $s1, $zero
    /* 13FAF0 0023FAF0 C8FE080C */  jal        func_0023FB20
    /* 13FAF4 0023FAF4 400022AE */   sw        $v0, 0x40($s1)
    /* 13FAF8 0023FAF8 480020FE */  sd         $zero, 0x48($s1)
    /* 13FAFC 0023FAFC 2D100000 */  daddu      $v0, $zero, $zero
.align 2
  .L0023FB00:
    /* 13FB00 0023FB00 7000BFDF */  ld         $ra, 0x70($sp)
    /* 13FB04 0023FB04 6000B4DF */  ld         $s4, 0x60($sp)
    /* 13FB08 0023FB08 5000B3DF */  ld         $s3, 0x50($sp)
    /* 13FB0C 0023FB0C 4000B2DF */  ld         $s2, 0x40($sp)
    /* 13FB10 0023FB10 3000B1DF */  ld         $s1, 0x30($sp)
    /* 13FB14 0023FB14 2000B0DF */  ld         $s0, 0x20($sp)
    /* 13FB18 0023FB18 0800E003 */  jr         $ra
    /* 13FB1C 0023FB1C 8000BD27 */   addiu     $sp, $sp, 0x80
endlabel func_0023F960

/* Handwritten function */
nonmatching func_0023FB20, 0x194

glabel func_0023FB20
    /* 13FB20 0023FB20 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 13FB24 0023FB24 2D388000 */  daddu      $a3, $a0, $zero
    /* 13FB28 0023FB28 1000BFFF */  sd         $ra, 0x10($sp)
    /* 13FB2C 0023FB2C 01000224 */  addiu      $v0, $zero, 0x1
    /* 13FB30 0023FB30 0000B0FF */  sd         $s0, 0x0($sp)
    /* 13FB34 0023FB34 2D280000 */  daddu      $a1, $zero, $zero
    /* 13FB38 0023FB38 4400E2AC */  sw         $v0, 0x44($a3)
    /* 13FB3C 0023FB3C 5400E38C */  lw         $v1, 0x54($a3)
    /* 13FB40 0023FB40 0C00E0AC */  sw         $zero, 0xC($a3)
    /* 13FB44 0023FB44 1000E0AC */  sw         $zero, 0x10($a3)
    /* 13FB48 0023FB48 1400E0AC */  sw         $zero, 0x14($a3)
    /* 13FB4C 0023FB4C 5800E0AC */  sw         $zero, 0x58($a3)
    /* 13FB50 0023FB50 11006018 */  blez       $v1, .L0023FB98
    /* 13FB54 0023FB54 5C00E0AC */   sw        $zero, 0x5C($a3)
    /* 13FB58 0023FB58 5000E68C */  lw         $a2, 0x50($a3)
    /* 13FB5C 0023FB5C 0400E88C */  lw         $t0, 0x4($a3)
.align 2
  .L0023FB60:
    /* 13FB60 0023FB60 18000224 */  addiu      $v0, $zero, 0x18
    /* 13FB64 0023FB64 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 13FB68 0023FB68 1818A200 */  mult       $v1, $a1, $v0
    /* 13FB6C 0023FB6C 0100A524 */  addiu      $a1, $a1, 0x1
    /* 13FB70 0023FB70 21106600 */  addu       $v0, $v1, $a2
    /* 13FB74 0023FB74 140040AC */  sw         $zero, 0x14($v0)
    /* 13FB78 0023FB78 100040AC */  sw         $zero, 0x10($v0)
    /* 13FB7C 0023FB7C 080044FC */  sd         $a0, 0x8($v0)
    /* 13FB80 0023FB80 5400E38C */  lw         $v1, 0x54($a3)
    /* 13FB84 0023FB84 2A18A300 */  slt        $v1, $a1, $v1
    /* 13FB88 0023FB88 F5FF6014 */  bnez       $v1, .L0023FB60
    /* 13FB8C 0023FB8C 000044FC */   sd        $a0, 0x0($v0)
    /* 13FB90 0023FB90 03000010 */  b          .L0023FBA0
    /* 13FB94 0023FB94 0800E28C */   lw        $v0, 0x8($a3)
.align 2
  .L0023FB98:
    /* 13FB98 0023FB98 0400E88C */  lw         $t0, 0x4($a3)
    /* 13FB9C 0023FB9C 0800E28C */  lw         $v0, 0x8($a3)
.align 2
  .L0023FBA0:
    /* 13FBA0 0023FBA0 14004018 */  blez       $v0, .L0023FBF4
    /* 13FBA4 0023FBA4 2D280000 */   daddu     $a1, $zero, $zero
    /* 13FBA8 0023FBA8 FF0F063C */  lui        $a2, (0xFFFFFFF >> 16)
    /* 13FBAC 0023FBAC 00300A3C */  lui        $t2, (0x30000000 >> 16)
    /* 13FBB0 0023FBB0 FFFFC634 */  ori        $a2, $a2, (0xFFFFFFF & 0xFFFF)
    /* 13FBB4 0023FBB4 80000924 */  addiu      $t1, $zero, 0x80
.align 2
  .L0023FBB8:
    /* 13FBB8 0023FBB8 0000E28C */  lw         $v0, 0x0($a3)
    /* 13FBBC 0023FBBC C01A0500 */  sll        $v1, $a1, 11
    /* 13FBC0 0023FBC0 00210500 */  sll        $a0, $a1, 4
    /* 13FBC4 0023FBC4 21186200 */  addu       $v1, $v1, $v0
    /* 13FBC8 0023FBC8 21208800 */  addu       $a0, $a0, $t0
    /* 13FBCC 0023FBCC 24186600 */  and        $v1, $v1, $a2
    /* 13FBD0 0023FBD0 0100A524 */  addiu      $a1, $a1, 0x1
    /* 13FBD4 0023FBD4 3C180300 */  dsll32     $v1, $v1, 0
    /* 13FBD8 0023FBD8 25186A00 */  or         $v1, $v1, $t2
    /* 13FBDC 0023FBDC 25186900 */  or         $v1, $v1, $t1
    /* 13FBE0 0023FBE0 000083FC */  sd         $v1, 0x0($a0)
    /* 13FBE4 0023FBE4 0800E28C */  lw         $v0, 0x8($a3)
    /* 13FBE8 0023FBE8 2A10A200 */  slt        $v0, $a1, $v0
    /* 13FBEC 0023FBEC F2FF4014 */  bnez       $v0, .L0023FBB8
    /* 13FBF0 0023FBF0 0400E88C */   lw        $t0, 0x4($a3)
.align 2
  .L0023FBF4:
    /* 13FBF4 0023FBF4 FF0F063C */  lui        $a2, (0xFFFFFFF >> 16)
    /* 13FBF8 0023FBF8 00210500 */  sll        $a0, $a1, 4
    /* 13FBFC 0023FBFC FFFFC634 */  ori        $a2, $a2, (0xFFFFFFF & 0xFFFF)
    /* 13FC00 0023FC00 0020053C */  lui        $a1, (0x20000000 >> 16)
    /* 13FC04 0023FC04 24100601 */  and        $v0, $t0, $a2
    /* 13FC08 0023FC08 21208800 */  addu       $a0, $a0, $t0
    /* 13FC0C 0023FC0C 3C100200 */  dsll32     $v0, $v0, 0
    /* 13FC10 0023FC10 0010033C */  lui        $v1, (0x1000B420 >> 16)
    /* 13FC14 0023FC14 25104500 */  or         $v0, $v0, $a1
    /* 13FC18 0023FC18 20B46334 */  ori        $v1, $v1, (0x1000B420 & 0xFFFF)
    /* 13FC1C 0023FC1C 000082FC */  sd         $v0, 0x0($a0)
    /* 13FC20 0023FC20 0010053C */  lui        $a1, (0x1000B410 >> 16)
    /* 13FC24 0023FC24 000060AC */  sw         $zero, 0x0($v1)
    /* 13FC28 0023FC28 10B4A534 */  ori        $a1, $a1, (0x1000B410 & 0xFFFF)
    /* 13FC2C 0023FC2C 0000E28C */  lw         $v0, 0x0($a3)
    /* 13FC30 0023FC30 0010043C */  lui        $a0, (0x1000B430 >> 16)
    /* 13FC34 0023FC34 0400E38C */  lw         $v1, 0x4($a3)
    /* 13FC38 0023FC38 30B48434 */  ori        $a0, $a0, (0x1000B430 & 0xFFFF)
    /* 13FC3C 0023FC3C 24104600 */  and        $v0, $v0, $a2
    /* 13FC40 0023FC40 05001024 */  addiu      $s0, $zero, 0x5
    /* 13FC44 0023FC44 0000A2AC */  sw         $v0, 0x0($a1)
    /* 13FC48 0023FC48 24186600 */  and        $v1, $v1, $a2
    /* 13FC4C 0023FC4C 000083AC */  sw         $v1, 0x0($a0)
    /* 13FC50 0023FC50 9006040C */  jal        func_00101A40
    /* 13FC54 0023FC54 00000000 */   nop
    /* 13FC58 0023FC58 0010063C */  lui        $a2, (0x1000F520 >> 16)
    /* 13FC5C 0023FC5C 0100073C */  lui        $a3, (0x10000 >> 16)
    /* 13FC60 0023FC60 20F5C634 */  ori        $a2, $a2, (0x1000F520 & 0xFFFF)
    /* 13FC64 0023FC64 0010053C */  lui        $a1, (0x1000F590 >> 16)
    /* 13FC68 0023FC68 0000C28C */  lw         $v0, 0x0($a2)
    /* 13FC6C 0023FC6C 90F5A534 */  ori        $a1, $a1, (0x1000F590 & 0xFFFF)
    /* 13FC70 0023FC70 0010033C */  lui        $v1, (0x1000B400 >> 16)
    /* 13FC74 0023FC74 FEFF043C */  lui        $a0, (0xFFFEFFFF >> 16)
    /* 13FC78 0023FC78 25104700 */  or         $v0, $v0, $a3
    /* 13FC7C 0023FC7C 00B46334 */  ori        $v1, $v1, (0x1000B400 & 0xFFFF)
    /* 13FC80 0023FC80 0000A2AC */  sw         $v0, 0x0($a1)
    /* 13FC84 0023FC84 FFFF8434 */  ori        $a0, $a0, (0xFFFEFFFF & 0xFFFF)
    /* 13FC88 0023FC88 000070AC */  sw         $s0, 0x0($v1)
    /* 13FC8C 0023FC8C 0000C28C */  lw         $v0, 0x0($a2)
    /* 13FC90 0023FC90 24104400 */  and        $v0, $v0, $a0
    /* 13FC94 0023FC94 0000A2AC */  sw         $v0, 0x0($a1)
    /* 13FC98 0023FC98 0F000000 */  sync
    /* 13FC9C 0023FC9C 38000042 */  ei /* handwritten instruction */
    /* 13FCA0 0023FCA0 1000BFDF */  ld         $ra, 0x10($sp)
    /* 13FCA4 0023FCA4 01000224 */  addiu      $v0, $zero, 0x1
    /* 13FCA8 0023FCA8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 13FCAC 0023FCAC 0800E003 */  jr         $ra
    /* 13FCB0 0023FCB0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0023FB20
    /* 13FCB4 0023FCB4 00000000 */  nop

nonmatching func_0023FCB8, 0xE8

glabel func_0023FCB8
    /* 13FCB8 0023FCB8 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 13FCBC 0023FCBC 4000B4FF */  sd         $s4, 0x40($sp)
    /* 13FCC0 0023FCC0 3000B3FF */  sd         $s3, 0x30($sp)
    /* 13FCC4 0023FCC4 2DA0E000 */  daddu      $s4, $a3, $zero
    /* 13FCC8 0023FCC8 2000B2FF */  sd         $s2, 0x20($sp)
    /* 13FCCC 0023FCCC 2D98A000 */  daddu      $s3, $a1, $zero
    /* 13FCD0 0023FCD0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 13FCD4 0023FCD4 2D900001 */  daddu      $s2, $t0, $zero
    /* 13FCD8 0023FCD8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 13FCDC 0023FCDC 2D88C000 */  daddu      $s1, $a2, $zero
    /* 13FCE0 0023FCE0 5000BFFF */  sd         $ra, 0x50($sp)
    /* 13FCE4 0023FCE4 2D808000 */  daddu      $s0, $a0, $zero
    /* 13FCE8 0023FCE8 5801040C */  jal        func_00100560
    /* 13FCEC 0023FCEC 4000048E */   lw        $a0, 0x40($s0)
    /* 13FCF0 0023FCF0 1000038E */  lw         $v1, 0x10($s0)
    /* 13FCF4 0023FCF4 0C00028E */  lw         $v0, 0xC($s0)
    /* 13FCF8 0023FCF8 1400058E */  lw         $a1, 0x14($s0)
    /* 13FCFC 0023FCFC 02006624 */  addiu      $a2, $v1, 0x2
    /* 13FD00 0023FD00 21104300 */  addu       $v0, $v0, $v1
    /* 13FD04 0023FD04 1800048E */  lw         $a0, 0x18($s0)
    /* 13FD08 0023FD08 C0120200 */  sll        $v0, $v0, 11
    /* 13FD0C 0023FD0C 0800038E */  lw         $v1, 0x8($s0)
    /* 13FD10 0023FD10 21104500 */  addu       $v0, $v0, $a1
    /* 13FD14 0023FD14 01008050 */  beql       $a0, $zero, .L0023FD1C
    /* 13FD18 0023FD18 CD010000 */   break     0, 7
.align 2
  .L0023FD1C:
    /* 13FD1C 0023FD1C 1A004400 */  div        $zero, $v0, $a0
    /* 13FD20 0023FD20 23186600 */  subu       $v1, $v1, $a2
    /* 13FD24 0023FD24 C01A0300 */  sll        $v1, $v1, 11
    /* 13FD28 0023FD28 23286500 */  subu       $a1, $v1, $a1
    /* 13FD2C 0023FD2C 10380000 */  mfhi       $a3
    /* 13FD30 0023FD30 23208700 */  subu       $a0, $a0, $a3
    /* 13FD34 0023FD34 2A108500 */  slt        $v0, $a0, $a1
    /* 13FD38 0023FD38 08004054 */  bnel       $v0, $zero, .L0023FD5C
    /* 13FD3C 0023FD3C 000024AE */   sw        $a0, 0x0($s1)
    /* 13FD40 0023FD40 0000028E */  lw         $v0, 0x0($s0)
    /* 13FD44 0023FD44 000025AE */  sw         $a1, 0x0($s1)
    /* 13FD48 0023FD48 21104700 */  addu       $v0, $v0, $a3
    /* 13FD4C 0023FD4C 000040AE */  sw         $zero, 0x0($s2)
    /* 13FD50 0023FD50 000062AE */  sw         $v0, 0x0($s3)
    /* 13FD54 0023FD54 09000010 */  b          .L0023FD7C
    /* 13FD58 0023FD58 000080AE */   sw        $zero, 0x0($s4)
.align 2
  .L0023FD5C:
    /* 13FD5C 0023FD5C 0000028E */  lw         $v0, 0x0($s0)
    /* 13FD60 0023FD60 1800038E */  lw         $v1, 0x18($s0)
    /* 13FD64 0023FD64 21204700 */  addu       $a0, $v0, $a3
    /* 13FD68 0023FD68 23186700 */  subu       $v1, $v1, $a3
    /* 13FD6C 0023FD6C 000064AE */  sw         $a0, 0x0($s3)
    /* 13FD70 0023FD70 2318A300 */  subu       $v1, $a1, $v1
    /* 13FD74 0023FD74 000082AE */  sw         $v0, 0x0($s4)
    /* 13FD78 0023FD78 000043AE */  sw         $v1, 0x0($s2)
.align 2
  .L0023FD7C:
    /* 13FD7C 0023FD7C 4000048E */  lw         $a0, 0x40($s0)
    /* 13FD80 0023FD80 5000BFDF */  ld         $ra, 0x50($sp)
    /* 13FD84 0023FD84 4000B4DF */  ld         $s4, 0x40($sp)
    /* 13FD88 0023FD88 3000B3DF */  ld         $s3, 0x30($sp)
    /* 13FD8C 0023FD8C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 13FD90 0023FD90 1000B1DF */  ld         $s1, 0x10($sp)
    /* 13FD94 0023FD94 0000B0DF */  ld         $s0, 0x0($sp)
    /* 13FD98 0023FD98 50010408 */  j          func_00100540
    /* 13FD9C 0023FD9C 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_0023FCB8
