.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00243974, 0x4

glabel func_00243974
    /* 143974 00243974 00000000 */  nop
endlabel func_00243974

nonmatching func_00243978, 0x34

glabel func_00243978
    /* 143978 00243978 0000A4D8 */  lqc2       $vf4, 0x0($a1)
    /* 14397C 0024397C 6A21C44B */  vmul.xyz   $vf5, $vf4, $vf4
    /* 143980 00243980 4129054B */  vaddy.x    $vf5, $vf5, $vf5y
    /* 143984 00243984 4229054B */  vaddz.x    $vf5, $vf5, $vf5z
    /* 143988 00243988 BD03054A */  .word      0x4A0503BD                    # vsqrt      $Q, $vf5x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 14398C 0024398C BF03004A */  vwaitq
    /* 143990 00243990 6001004B */  vaddq.x    $vf5, $vf0, $Q
    /* 143994 00243994 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 143998 00243998 AC01E04B */  vsub.xyzw  $vf6, $vf0, $vf0
    /* 14399C 0024399C BF03004A */  vwaitq
    /* 1439A0 002439A0 9C21C04B */  vmulq.xyz  $vf6, $vf4, $Q
    /* 1439A4 002439A4 0800E003 */  jr         $ra
    /* 1439A8 002439A8 000086F8 */   sqc2      $vf6, 0x0($a0)
endlabel func_00243978
