.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002439AC, 0x4

glabel func_002439AC
    /* 1439AC 002439AC 00000000 */  nop
endlabel func_002439AC

nonmatching func_002439B0, 0x44

glabel func_002439B0
    /* 1439B0 002439B0 0000A878 */  lq         $t0, 0x0($a1)
    /* 1439B4 002439B4 1000A978 */  lq         $t1, 0x10($a1)
    /* 1439B8 002439B8 2000AA78 */  lq         $t2, 0x20($a1)
    /* 1439BC 002439BC 3000AB78 */  lq         $t3, 0x30($a1)
    /* 1439C0 002439C0 88642871 */  pextlw     $t4, $t1, $t0
    /* 1439C4 002439C4 A86C2871 */  pextuw     $t5, $t1, $t0
    /* 1439C8 002439C8 88746A71 */  pextlw     $t6, $t3, $t2
    /* 1439CC 002439CC A87C6A71 */  pextuw     $t7, $t3, $t2
    /* 1439D0 002439D0 8943CC71 */  pcpyld     $t0, $t6, $t4
    /* 1439D4 002439D4 A94B8E71 */  pcpyud     $t1, $t4, $t6
    /* 1439D8 002439D8 8953ED71 */  pcpyld     $t2, $t7, $t5
    /* 1439DC 002439DC A95BAF71 */  pcpyud     $t3, $t5, $t7
    /* 1439E0 002439E0 0000887C */  sq         $t0, 0x0($a0)
    /* 1439E4 002439E4 1000897C */  sq         $t1, 0x10($a0)
    /* 1439E8 002439E8 20008A7C */  sq         $t2, 0x20($a0)
    /* 1439EC 002439EC 0800E003 */  jr         $ra
    /* 1439F0 002439F0 30008B7C */   sq        $t3, 0x30($a0)
endlabel func_002439B0
