.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00243B14, 0x4

glabel func_00243B14
    /* 143B14 00243B14 00000000 */  nop
endlabel func_00243B14
