.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_00244460, 0x48

glabel func_00244460
    /* 144460 00244460 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 144464 00244464 8045023C */  lui        $v0, (0x45800000 >> 16)
    /* 144468 00244468 38140200 */  dsll       $v0, $v0, 16
    /* 14446C 0024446C 80454234 */  ori        $v0, $v0, 0x4580
    /* 144470 00244470 38140200 */  dsll       $v0, $v0, 16
    /* 144474 00244474 000087D8 */  lqc2       $vf7, 0x0($a0)
    /* 144478 00244478 0030A248 */  qmtc2.ni   $v0, $vf6
    /* 14447C 0024447C 0080C048 */  ctc2.ni    $zero, $vi16
    /* 144480 00244480 6C39A44B */  vsub.xyw   $vf5, $vf7, $vf4
    /* 144484 00244484 6C31874B */  vsub.xy    $vf5, $vf6, $vf7
    /* 144488 00244488 FF02004A */  vnop
    /* 14448C 0024448C FF02004A */  vnop
    /* 144490 00244490 FF02004A */  vnop
    /* 144494 00244494 FF02004A */  vnop
    /* 144498 00244498 FF02004A */  vnop
    /* 14449C 0024449C 00804248 */  cfc2.ni    $v0, $vi16
    /* 1444A0 002444A0 0800E003 */  jr         $ra
    /* 1444A4 002444A4 C0004230 */   andi      $v0, $v0, 0xC0
endlabel func_00244460

.align 3
nonmatching func_002444A8, 0x60

glabel func_002444A8
    /* 1444A8 002444A8 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 1444AC 002444AC 8045023C */  lui        $v0, (0x45800000 >> 16)
    /* 1444B0 002444B0 38140200 */  dsll       $v0, $v0, 16
    /* 1444B4 002444B4 80454234 */  ori        $v0, $v0, 0x4580
    /* 1444B8 002444B8 38140200 */  dsll       $v0, $v0, 16
    /* 1444BC 002444BC 000086D8 */  lqc2       $vf6, 0x0($a0)
    /* 1444C0 002444C0 0000A8D8 */  lqc2       $vf8, 0x0($a1)
    /* 1444C4 002444C4 0000C9D8 */  lqc2       $vf9, 0x0($a2)
    /* 1444C8 002444C8 0038A248 */  qmtc2.ni   $v0, $vf7
    /* 1444CC 002444CC 0080C048 */  ctc2.ni    $zero, $vi16
    /* 1444D0 002444D0 6C31A44B */  vsub.xyw   $vf5, $vf6, $vf4
    /* 1444D4 002444D4 6C39864B */  vsub.xy    $vf5, $vf7, $vf6
    /* 1444D8 002444D8 6C41A44B */  vsub.xyw   $vf5, $vf8, $vf4
    /* 1444DC 002444DC 6C39884B */  vsub.xy    $vf5, $vf7, $vf8
    /* 1444E0 002444E0 6C49A44B */  vsub.xyw   $vf5, $vf9, $vf4
    /* 1444E4 002444E4 6C39894B */  vsub.xy    $vf5, $vf7, $vf9
    /* 1444E8 002444E8 FF02004A */  vnop
    /* 1444EC 002444EC FF02004A */  vnop
    /* 1444F0 002444F0 FF02004A */  vnop
    /* 1444F4 002444F4 FF02004A */  vnop
    /* 1444F8 002444F8 FF02004A */  vnop
    /* 1444FC 002444FC 00804248 */  cfc2.ni    $v0, $vi16
    /* 144500 00244500 0800E003 */  jr         $ra
    /* 144504 00244504 C0004230 */   andi      $v0, $v0, 0xC0
endlabel func_002444A8

.align 3
/* Handwritten function */
nonmatching func_00244508, 0x8C

glabel func_00244508
    /* 144508 00244508 0000E8D8 */  lqc2       $vf8, 0x0($a3)
    /* 14450C 0024450C 0000C4D8 */  lqc2       $vf4, 0x0($a2)
    /* 144510 00244510 1000C5D8 */  lqc2       $vf5, 0x10($a2)
    /* 144514 00244514 2000C6D8 */  lqc2       $vf6, 0x20($a2)
    /* 144518 00244518 3000C7D8 */  lqc2       $vf7, 0x30($a2)
    /* 14451C 0024451C 000089D8 */  lqc2       $vf9, 0x0($a0)
    /* 144520 00244520 0000AAD8 */  lqc2       $vf10, 0x0($a1)
    /* 144524 00244524 00008BD8 */  lqc2       $vf11, 0x0($a0)
    /* 144528 00244528 0000ACD8 */  lqc2       $vf12, 0x0($a1)
.align 2
  .L0024452C:
    /* 14452C 0024452C BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 144530 00244530 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 144534 00244534 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 144538 00244538 0B3AE84B */  vmaddw.xyzw $vf8, $vf7, $vf8w
    /* 14453C 0024453C DB4AC84B */  vmulw.xyz  $vf11, $vf9, $vf8w
    /* 144540 00244540 1B53C84B */  vmulw.xyz  $vf12, $vf10, $vf8w
    /* 144544 00244544 FF02004A */  vnop
    /* 144548 00244548 FF02004A */  vnop
    /* 14454C 0024454C 0080C048 */  ctc2.ni    $zero, $vi16
    /* 144550 00244550 EC42AB4B */  vsub.xyw   $vf11, $vf8, $vf11
    /* 144554 00244554 2C63A84B */  vsub.xyw   $vf12, $vf12, $vf8
    /* 144558 00244558 3C4B2B4A */  vmove.w    $vf11, $vf9
    /* 14455C 0024455C 3C532C4A */  vmove.w    $vf12, $vf10
    /* 144560 00244560 FF02004A */  vnop
    /* 144564 00244564 1000E720 */  addi       $a3, $a3, 0x10 /* handwritten instruction */
    /* 144568 00244568 0000E8D8 */  lqc2       $vf8, 0x0($a3)
    /* 14456C 0024456C FFFF0821 */  addi       $t0, $t0, -0x1 /* handwritten instruction */
    /* 144570 00244570 00804248 */  cfc2.ni    $v0, $vi16
    /* 144574 00244574 C0004230 */  andi       $v0, $v0, 0xC0
    /* 144578 00244578 04004010 */  beqz       $v0, .L0024458C
    /* 14457C 0024457C 00000000 */   nop
    /* 144580 00244580 EAFF0814 */  bne        $zero, $t0, .L0024452C
    /* 144584 00244584 00000000 */   nop
    /* 144588 00244588 01000220 */  addi       $v0, $zero, 0x1 /* handwritten instruction */
.align 2
  .L0024458C:
    /* 14458C 0024458C 0800E003 */  jr         $ra
    /* 144590 00244590 00000000 */   nop
endlabel func_00244508
    /* 144594 00244594 00000000 */  nop

.align 3
nonmatching func_00244598, 0x5C

glabel func_00244598
    /* 144598 00244598 0010023C */  lui        $v0, (0x10003830 >> 16)
    /* 14459C 0024459C 0010043C */  lui        $a0, (0x10003820 >> 16)
    /* 1445A0 002445A0 30384234 */  ori        $v0, $v0, (0x10003830 & 0xFFFF)
    /* 1445A4 002445A4 20388434 */  ori        $a0, $a0, (0x10003820 & 0xFFFF)
    /* 1445A8 002445A8 000040AC */  sw         $zero, 0x0($v0)
    /* 1445AC 002445AC 0010033C */  lui        $v1, (0x10003810 >> 16)
    /* 1445B0 002445B0 000080AC */  sw         $zero, 0x0($a0)
    /* 1445B4 002445B4 10386334 */  ori        $v1, $v1, (0x10003810 & 0xFFFF)
    /* 1445B8 002445B8 01000224 */  addiu      $v0, $zero, 0x1
    /* 1445BC 002445BC 000062AC */  sw         $v0, 0x0($v1)
    /* 1445C0 002445C0 00E04848 */  cfc2.ni    $t0, $vi28
    /* 1445C4 002445C4 02000835 */  ori        $t0, $t0, 0x2
    /* 1445C8 002445C8 00E0C848 */  ctc2.ni    $t0, $vi28
    /* 1445CC 002445CC 0F040000 */  sync.p
    /* 1445D0 002445D0 5500043C */  lui        $a0, %hi(D_005506F0)
    /* 1445D4 002445D4 0010053C */  lui        $a1, (0x10004000 >> 16)
    /* 1445D8 002445D8 F0068424 */  addiu      $a0, $a0, %lo(D_005506F0)
    /* 1445DC 002445DC 0040A534 */  ori        $a1, $a1, (0x10004000 & 0xFFFF)
    /* 1445E0 002445E0 00008278 */  lq         $v0, 0x0($a0)
    /* 1445E4 002445E4 0000A27C */  sq         $v0, 0x0($a1)
    /* 1445E8 002445E8 10008378 */  lq         $v1, 0x10($a0)
    /* 1445EC 002445EC 0800E003 */  jr         $ra
    /* 1445F0 002445F0 0000A37C */   sq        $v1, 0x0($a1)
endlabel func_00244598
    /* 1445F4 002445F4 00000000 */  nop
