.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00244414, 0x4

glabel func_00244414
    /* 144414 00244414 00000000 */  nop
endlabel func_00244414
