.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00245254, 0x4

glabel func_00245254
    /* 145254 00245254 00000000 */  nop
endlabel func_00245254
