.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024575C, 0x4

glabel func_0024575C
    /* 14575C 0024575C 00000000 */  nop
endlabel func_0024575C
