.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00245EA4, 0x4

glabel func_00245EA4
    /* 145EA4 00245EA4 00000000 */  nop
endlabel func_00245EA4
