.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024A734, 0x4

glabel func_0024A734
    /* 14A734 0024A734 00000000 */  nop
endlabel func_0024A734
