.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024AAE4, 0x4

glabel func_0024AAE4
    /* 14AAE4 0024AAE4 00000000 */  nop
endlabel func_0024AAE4
