.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_0024B4D8, 0x4

glabel func_0024B4D8
    /* 14B4D8 0024B4D8 00000000 */  nop
endlabel func_0024B4D8
    /* 14B4DC 0024B4DC 00000000 */  nop
    /* 14B4E0 0024B4E0 00000000 */  nop
    /* 14B4E4 0024B4E4 00000000 */  nop
    /* 14B4E8 0024B4E8 00000000 */  nop
    /* 14B4EC 0024B4EC 00000000 */  nop
    /* 14B4F0 0024B4F0 00000000 */  nop
    /* 14B4F4 0024B4F4 00000000 */  nop
    /* 14B4F8 0024B4F8 00000000 */  nop
    /* 14B4FC 0024B4FC 00000000 */  nop

.align 3
/* Handwritten function */
nonmatching func_0024B500, 0x37C

glabel func_0024B500
    /* 14B500 0024B500 71001A3C */  lui        $k0, %hi(D_00717440) /* handwritten instruction */
    /* 14B504 0024B504 40745A27 */  addiu      $k0, $k0, %lo(D_00717440) /* handwritten instruction */
    /* 14B508 0024B508 1000417F */  sq         $at, 0x10($k0) /* handwritten instruction */
    /* 14B50C 0024B50C 2000427F */  sq         $v0, 0x20($k0) /* handwritten instruction */
    /* 14B510 0024B510 3000437F */  sq         $v1, 0x30($k0) /* handwritten instruction */
    /* 14B514 0024B514 4000447F */  sq         $a0, 0x40($k0) /* handwritten instruction */
    /* 14B518 0024B518 5000457F */  sq         $a1, 0x50($k0) /* handwritten instruction */
    /* 14B51C 0024B51C 6000467F */  sq         $a2, 0x60($k0) /* handwritten instruction */
    /* 14B520 0024B520 7000477F */  sq         $a3, 0x70($k0) /* handwritten instruction */
    /* 14B524 0024B524 8000487F */  sq         $t0, 0x80($k0) /* handwritten instruction */
    /* 14B528 0024B528 9000497F */  sq         $t1, 0x90($k0) /* handwritten instruction */
    /* 14B52C 0024B52C A0004A7F */  sq         $t2, 0xA0($k0) /* handwritten instruction */
    /* 14B530 0024B530 B0004B7F */  sq         $t3, 0xB0($k0) /* handwritten instruction */
    /* 14B534 0024B534 C0004C7F */  sq         $t4, 0xC0($k0) /* handwritten instruction */
    /* 14B538 0024B538 D0004D7F */  sq         $t5, 0xD0($k0) /* handwritten instruction */
    /* 14B53C 0024B53C E0004E7F */  sq         $t6, 0xE0($k0) /* handwritten instruction */
    /* 14B540 0024B540 F0004F7F */  sq         $t7, 0xF0($k0) /* handwritten instruction */
    /* 14B544 0024B544 0001507F */  sq         $s0, 0x100($k0) /* handwritten instruction */
    /* 14B548 0024B548 1001517F */  sq         $s1, 0x110($k0) /* handwritten instruction */
    /* 14B54C 0024B54C 2001527F */  sq         $s2, 0x120($k0) /* handwritten instruction */
    /* 14B550 0024B550 3001537F */  sq         $s3, 0x130($k0) /* handwritten instruction */
    /* 14B554 0024B554 4001547F */  sq         $s4, 0x140($k0) /* handwritten instruction */
    /* 14B558 0024B558 5001557F */  sq         $s5, 0x150($k0) /* handwritten instruction */
    /* 14B55C 0024B55C 6001567F */  sq         $s6, 0x160($k0) /* handwritten instruction */
    /* 14B560 0024B560 7001577F */  sq         $s7, 0x170($k0) /* handwritten instruction */
    /* 14B564 0024B564 8001587F */  sq         $t8, 0x180($k0) /* handwritten instruction */
    /* 14B568 0024B568 9001597F */  sq         $t9, 0x190($k0) /* handwritten instruction */
    /* 14B56C 0024B56C C0015C7F */  sq         $gp, 0x1C0($k0) /* handwritten instruction */
    /* 14B570 0024B570 D0015D7F */  sq         $sp, 0x1D0($k0) /* handwritten instruction */
    /* 14B574 0024B574 E0015E7F */  sq         $fp, 0x1E0($k0) /* handwritten instruction */
    /* 14B578 0024B578 F0015F7F */  sq         $ra, 0x1F0($k0) /* handwritten instruction */
    /* 14B57C 0024B57C 10100000 */  mfhi       $v0
    /* 14B580 0024B580 7100013C */  lui        $at, %hi(D_00717640)
    /* 14B584 0024B584 407622FC */  sd         $v0, %lo(D_00717640)($at)
    /* 14B588 0024B588 10100070 */  mfhi1      $v0
    /* 14B58C 0024B58C 7100013C */  lui        $at, %hi(D_00717648)
    /* 14B590 0024B590 487622FC */  sd         $v0, %lo(D_00717648)($at)
    /* 14B594 0024B594 12100000 */  mflo       $v0
    /* 14B598 0024B598 7100013C */  lui        $at, %hi(D_00717650)
    /* 14B59C 0024B59C 507622FC */  sd         $v0, %lo(D_00717650)($at)
    /* 14B5A0 0024B5A0 12100070 */  mflo1      $v0
    /* 14B5A4 0024B5A4 7100013C */  lui        $at, %hi(D_00717658)
    /* 14B5A8 0024B5A8 587622FC */  sd         $v0, %lo(D_00717658)($at)
    /* 14B5AC 0024B5AC 28100000 */  mfsa       $v0
    /* 14B5B0 0024B5B0 7100013C */  lui        $at, %hi(D_00717660)
    /* 14B5B4 0024B5B4 607622FC */  sd         $v0, %lo(D_00717660)($at)
    /* 14B5B8 0024B5B8 00600440 */  mfc0       $a0, $12 /* handwritten instruction */
    /* 14B5BC 0024B5BC 00680540 */  mfc0       $a1, $13 /* handwritten instruction */
    /* 14B5C0 0024B5C0 00700640 */  mfc0       $a2, $14 /* handwritten instruction */
    /* 14B5C4 0024B5C4 00400740 */  mfc0       $a3, $8 /* handwritten instruction */
    /* 14B5C8 0024B5C8 7100083C */  lui        $t0, %hi(D_00717440)
    /* 14B5CC 0024B5CC 40740825 */  addiu      $t0, $t0, %lo(D_00717440)
    /* 14B5D0 0024B5D0 7100013C */  lui        $at, %hi(D_00717668)
    /* 14B5D4 0024B5D4 687626AC */  sw         $a2, %lo(D_00717668)($at)
    /* 14B5D8 0024B5D8 2500013C */  lui        $at, %hi(D_0024B600)
    /* 14B5DC 0024B5DC 00B62124 */  addiu      $at, $at, %lo(D_0024B600)
    /* 14B5E0 0024B5E0 00708140 */  mtc0       $at, $14 /* handwritten instruction */
    /* 14B5E4 0024B5E4 0F040000 */  sync.p
    /* 14B5E8 0024B5E8 00600140 */  mfc0       $at, $12 /* handwritten instruction */
    /* 14B5EC 0024B5EC FEFF0224 */  addiu      $v0, $zero, -0x2
    /* 14B5F0 0024B5F0 24082200 */  and        $at, $at, $v0
    /* 14B5F4 0024B5F4 00608140 */  mtc0       $at, $12 /* handwritten instruction */
    /* 14B5F8 0024B5F8 0F040000 */  sync.p
    /* 14B5FC 0024B5FC 18000042 */  eret /* handwritten instruction */
.align 2
  alabel D_0024B600
    /* 14B600 0024B600 5500013C */  lui        $at, %hi(D_00550880)
    /* 14B604 0024B604 8008218C */  lw         $at, %lo(D_00550880)($at)
    /* 14B608 0024B608 71001D3C */  lui        $sp, %hi(D_00717440)
    /* 14B60C 0024B60C 09F82000 */  jalr       $at
    /* 14B610 0024B610 4074BD27 */   addiu     $sp, $sp, %lo(D_00717440)
    /* 14B614 0024B614 ACFF0324 */  addiu      $v1, $zero, -0x54
    /* 14B618 0024B618 0C000000 */  syscall    0 /* handwritten instruction */
    /* 14B61C 0024B61C 00000000 */  nop
    /* 14B620 0024B620 00000000 */  nop
    /* 14B624 0024B624 00000000 */  nop
    /* 14B628 0024B628 00000000 */  nop
    /* 14B62C 0024B62C 00000000 */  nop
    /* 14B630 0024B630 00000000 */  nop
    /* 14B634 0024B634 00000000 */  nop
    /* 14B638 0024B638 00000000 */  nop
    /* 14B63C 0024B63C 00000000 */  nop
    /* 14B640 0024B640 00600140 */  mfc0       $at, $12 /* handwritten instruction */
    /* 14B644 0024B644 E4FF1A24 */  addiu      $k0, $zero, -0x1C /* handwritten instruction */
    /* 14B648 0024B648 24083A00 */  and        $at, $at, $k0
    /* 14B64C 0024B64C 00608140 */  mtc0       $at, $12 /* handwritten instruction */
    /* 14B650 0024B650 0F040000 */  sync.p
    /* 14B654 0024B654 7100023C */  lui        $v0, %hi(D_00717668)
    /* 14B658 0024B658 6876428C */  lw         $v0, %lo(D_00717668)($v0)
    /* 14B65C 0024B65C 00708240 */  mtc0       $v0, $14 /* handwritten instruction */
    /* 14B660 0024B660 0F040000 */  sync.p
    /* 14B664 0024B664 7100023C */  lui        $v0, %hi(D_00717640)
    /* 14B668 0024B668 407642DC */  ld         $v0, %lo(D_00717640)($v0)
    /* 14B66C 0024B66C 11004000 */  mthi       $v0
    /* 14B670 0024B670 7100023C */  lui        $v0, %hi(D_00717648)
    /* 14B674 0024B674 487642DC */  ld         $v0, %lo(D_00717648)($v0)
    /* 14B678 0024B678 11004070 */  mthi1      $v0
    /* 14B67C 0024B67C 7100023C */  lui        $v0, %hi(D_00717650)
    /* 14B680 0024B680 507642DC */  ld         $v0, %lo(D_00717650)($v0)
    /* 14B684 0024B684 13004000 */  mtlo       $v0
    /* 14B688 0024B688 7100023C */  lui        $v0, %hi(D_00717658)
    /* 14B68C 0024B68C 587642DC */  ld         $v0, %lo(D_00717658)($v0)
    /* 14B690 0024B690 13004070 */  mtlo1      $v0
    /* 14B694 0024B694 7100023C */  lui        $v0, %hi(D_00717660)
    /* 14B698 0024B698 607642DC */  ld         $v0, %lo(D_00717660)($v0)
    /* 14B69C 0024B69C 29004000 */  mtsa       $v0
    /* 14B6A0 0024B6A0 0F040000 */  sync.p
    /* 14B6A4 0024B6A4 71001A3C */  lui        $k0, %hi(D_00717440) /* handwritten instruction */
    /* 14B6A8 0024B6A8 40745A27 */  addiu      $k0, $k0, %lo(D_00717440) /* handwritten instruction */
    /* 14B6AC 0024B6AC 1000417B */  lq         $at, 0x10($k0) /* handwritten instruction */
    /* 14B6B0 0024B6B0 2000427B */  lq         $v0, 0x20($k0) /* handwritten instruction */
    /* 14B6B4 0024B6B4 3000437B */  lq         $v1, 0x30($k0) /* handwritten instruction */
    /* 14B6B8 0024B6B8 4000447B */  lq         $a0, 0x40($k0) /* handwritten instruction */
    /* 14B6BC 0024B6BC 5000457B */  lq         $a1, 0x50($k0) /* handwritten instruction */
    /* 14B6C0 0024B6C0 6000467B */  lq         $a2, 0x60($k0) /* handwritten instruction */
    /* 14B6C4 0024B6C4 7000477B */  lq         $a3, 0x70($k0) /* handwritten instruction */
    /* 14B6C8 0024B6C8 8000487B */  lq         $t0, 0x80($k0) /* handwritten instruction */
    /* 14B6CC 0024B6CC 9000497B */  lq         $t1, 0x90($k0) /* handwritten instruction */
    /* 14B6D0 0024B6D0 A0004A7B */  lq         $t2, 0xA0($k0) /* handwritten instruction */
    /* 14B6D4 0024B6D4 B0004B7B */  lq         $t3, 0xB0($k0) /* handwritten instruction */
    /* 14B6D8 0024B6D8 C0004C7B */  lq         $t4, 0xC0($k0) /* handwritten instruction */
    /* 14B6DC 0024B6DC D0004D7B */  lq         $t5, 0xD0($k0) /* handwritten instruction */
    /* 14B6E0 0024B6E0 E0004E7B */  lq         $t6, 0xE0($k0) /* handwritten instruction */
    /* 14B6E4 0024B6E4 F0004F7B */  lq         $t7, 0xF0($k0) /* handwritten instruction */
    /* 14B6E8 0024B6E8 0001507B */  lq         $s0, 0x100($k0) /* handwritten instruction */
    /* 14B6EC 0024B6EC 1001517B */  lq         $s1, 0x110($k0) /* handwritten instruction */
    /* 14B6F0 0024B6F0 2001527B */  lq         $s2, 0x120($k0) /* handwritten instruction */
    /* 14B6F4 0024B6F4 3001537B */  lq         $s3, 0x130($k0) /* handwritten instruction */
    /* 14B6F8 0024B6F8 4001547B */  lq         $s4, 0x140($k0) /* handwritten instruction */
    /* 14B6FC 0024B6FC 5001557B */  lq         $s5, 0x150($k0) /* handwritten instruction */
    /* 14B700 0024B700 6001567B */  lq         $s6, 0x160($k0) /* handwritten instruction */
    /* 14B704 0024B704 7001577B */  lq         $s7, 0x170($k0) /* handwritten instruction */
    /* 14B708 0024B708 8001587B */  lq         $t8, 0x180($k0) /* handwritten instruction */
    /* 14B70C 0024B70C 9001597B */  lq         $t9, 0x190($k0) /* handwritten instruction */
    /* 14B710 0024B710 C0015C7B */  lq         $gp, 0x1C0($k0) /* handwritten instruction */
    /* 14B714 0024B714 D0015D7B */  lq         $sp, 0x1D0($k0) /* handwritten instruction */
    /* 14B718 0024B718 E0015E7B */  lq         $fp, 0x1E0($k0) /* handwritten instruction */
    /* 14B71C 0024B71C F0015F7B */  lq         $ra, 0x1F0($k0) /* handwritten instruction */
    /* 14B720 0024B720 00601A40 */  mfc0       $k0, $12 /* handwritten instruction */
    /* 14B724 0024B724 13005A37 */  ori        $k0, $k0, 0x13 /* handwritten instruction */
    /* 14B728 0024B728 00609A40 */  mtc0       $k0, $12 /* handwritten instruction */
    /* 14B72C 0024B72C 0F040000 */  sync.p
    /* 14B730 0024B730 18000042 */  eret /* handwritten instruction */
    /* 14B734 0024B734 00000000 */  nop
    /* 14B738 0024B738 00000000 */  nop
    /* 14B73C 0024B73C 00000000 */  nop
.align 2
  alabel D_0024B740
    /* 14B740 0024B740 71001A3C */  lui        $k0, %hi(D_00717440) /* handwritten instruction */
    /* 14B744 0024B744 40745A27 */  addiu      $k0, $k0, %lo(D_00717440) /* handwritten instruction */
    /* 14B748 0024B748 1000417F */  sq         $at, 0x10($k0) /* handwritten instruction */
    /* 14B74C 0024B74C 2000427F */  sq         $v0, 0x20($k0) /* handwritten instruction */
    /* 14B750 0024B750 3000437F */  sq         $v1, 0x30($k0) /* handwritten instruction */
    /* 14B754 0024B754 4000447F */  sq         $a0, 0x40($k0) /* handwritten instruction */
    /* 14B758 0024B758 5000457F */  sq         $a1, 0x50($k0) /* handwritten instruction */
    /* 14B75C 0024B75C 6000467F */  sq         $a2, 0x60($k0) /* handwritten instruction */
    /* 14B760 0024B760 7000477F */  sq         $a3, 0x70($k0) /* handwritten instruction */
    /* 14B764 0024B764 8000487F */  sq         $t0, 0x80($k0) /* handwritten instruction */
    /* 14B768 0024B768 9000497F */  sq         $t1, 0x90($k0) /* handwritten instruction */
    /* 14B76C 0024B76C A0004A7F */  sq         $t2, 0xA0($k0) /* handwritten instruction */
    /* 14B770 0024B770 B0004B7F */  sq         $t3, 0xB0($k0) /* handwritten instruction */
    /* 14B774 0024B774 C0004C7F */  sq         $t4, 0xC0($k0) /* handwritten instruction */
    /* 14B778 0024B778 D0004D7F */  sq         $t5, 0xD0($k0) /* handwritten instruction */
    /* 14B77C 0024B77C E0004E7F */  sq         $t6, 0xE0($k0) /* handwritten instruction */
    /* 14B780 0024B780 F0004F7F */  sq         $t7, 0xF0($k0) /* handwritten instruction */
    /* 14B784 0024B784 0001507F */  sq         $s0, 0x100($k0) /* handwritten instruction */
    /* 14B788 0024B788 1001517F */  sq         $s1, 0x110($k0) /* handwritten instruction */
    /* 14B78C 0024B78C 2001527F */  sq         $s2, 0x120($k0) /* handwritten instruction */
    /* 14B790 0024B790 3001537F */  sq         $s3, 0x130($k0) /* handwritten instruction */
    /* 14B794 0024B794 4001547F */  sq         $s4, 0x140($k0) /* handwritten instruction */
    /* 14B798 0024B798 5001557F */  sq         $s5, 0x150($k0) /* handwritten instruction */
    /* 14B79C 0024B79C 6001567F */  sq         $s6, 0x160($k0) /* handwritten instruction */
    /* 14B7A0 0024B7A0 7001577F */  sq         $s7, 0x170($k0) /* handwritten instruction */
    /* 14B7A4 0024B7A4 8001587F */  sq         $t8, 0x180($k0) /* handwritten instruction */
    /* 14B7A8 0024B7A8 9001597F */  sq         $t9, 0x190($k0) /* handwritten instruction */
    /* 14B7AC 0024B7AC C0015C7F */  sq         $gp, 0x1C0($k0) /* handwritten instruction */
    /* 14B7B0 0024B7B0 D0015D7F */  sq         $sp, 0x1D0($k0) /* handwritten instruction */
    /* 14B7B4 0024B7B4 E0015E7F */  sq         $fp, 0x1E0($k0) /* handwritten instruction */
    /* 14B7B8 0024B7B8 F0015F7F */  sq         $ra, 0x1F0($k0) /* handwritten instruction */
    /* 14B7BC 0024B7BC 10100000 */  mfhi       $v0
    /* 14B7C0 0024B7C0 7100013C */  lui        $at, %hi(D_00717640)
    /* 14B7C4 0024B7C4 407622FC */  sd         $v0, %lo(D_00717640)($at)
    /* 14B7C8 0024B7C8 10100070 */  mfhi1      $v0
    /* 14B7CC 0024B7CC 7100013C */  lui        $at, %hi(D_00717648)
    /* 14B7D0 0024B7D0 487622FC */  sd         $v0, %lo(D_00717648)($at)
    /* 14B7D4 0024B7D4 12100000 */  mflo       $v0
    /* 14B7D8 0024B7D8 7100013C */  lui        $at, %hi(D_00717650)
    /* 14B7DC 0024B7DC 507622FC */  sd         $v0, %lo(D_00717650)($at)
    /* 14B7E0 0024B7E0 12100070 */  mflo1      $v0
    /* 14B7E4 0024B7E4 7100013C */  lui        $at, %hi(D_00717658)
    /* 14B7E8 0024B7E8 587622FC */  sd         $v0, %lo(D_00717658)($at)
    /* 14B7EC 0024B7EC 28100000 */  mfsa       $v0
    /* 14B7F0 0024B7F0 7100013C */  lui        $at, %hi(D_00717660)
    /* 14B7F4 0024B7F4 607622FC */  sd         $v0, %lo(D_00717660)($at)
    /* 14B7F8 0024B7F8 00600440 */  mfc0       $a0, $12 /* handwritten instruction */
    /* 14B7FC 0024B7FC 00680540 */  mfc0       $a1, $13 /* handwritten instruction */
    /* 14B800 0024B800 00700640 */  mfc0       $a2, $14 /* handwritten instruction */
    /* 14B804 0024B804 00400740 */  mfc0       $a3, $8 /* handwritten instruction */
    /* 14B808 0024B808 00B80840 */  mfc0       $t0, $23 /* handwritten instruction */
    /* 14B80C 0024B80C 7100093C */  lui        $t1, %hi(D_00717440)
    /* 14B810 0024B810 40742925 */  addiu      $t1, $t1, %lo(D_00717440)
    /* 14B814 0024B814 2500013C */  lui        $at, %hi(D_0024B83C)
    /* 14B818 0024B818 3CB82124 */  addiu      $at, $at, %lo(D_0024B83C)
    /* 14B81C 0024B81C 00708140 */  mtc0       $at, $14 /* handwritten instruction */
    /* 14B820 0024B820 0F040000 */  sync.p
    /* 14B824 0024B824 00600140 */  mfc0       $at, $12 /* handwritten instruction */
    /* 14B828 0024B828 FEFF0224 */  addiu      $v0, $zero, -0x2
    /* 14B82C 0024B82C 24082200 */  and        $at, $at, $v0
    /* 14B830 0024B830 00608140 */  mtc0       $at, $12 /* handwritten instruction */
    /* 14B834 0024B834 0F040000 */  sync.p
    /* 14B838 0024B838 18000042 */  eret /* handwritten instruction */
.align 2
  alabel D_0024B83C
    /* 14B83C 0024B83C 7C00A230 */  andi       $v0, $a1, 0x7C
    /* 14B840 0024B840 5500013C */  lui        $at, %hi(D_00550888)
    /* 14B844 0024B844 21082200 */  addu       $at, $at, $v0
    /* 14B848 0024B848 8808218C */  lw         $at, %lo(D_00550888)($at)
    /* 14B84C 0024B84C 71001D3C */  lui        $sp, %hi(D_00717440)
    /* 14B850 0024B850 09F82000 */  jalr       $at
    /* 14B854 0024B854 4074BD27 */   addiu     $sp, $sp, %lo(D_00717440)
    /* 14B858 0024B858 CDFFFF03 */  break      1023, 1023
    /* 14B85C 0024B85C 00000000 */  nop
.align 2
  alabel D_0024B860
    /* 14B860 0024B860 1000828C */  lw         $v0, 0x10($a0)
    /* 14B864 0024B864 1C00A68C */  lw         $a2, 0x1C($a1)
    /* 14B868 0024B868 1400838C */  lw         $v1, 0x14($a0)
    /* 14B86C 0024B86C 80100200 */  sll        $v0, $v0, 2
    /* 14B870 0024B870 21104600 */  addu       $v0, $v0, $a2
    /* 14B874 0024B874 0800E003 */  jr         $ra
    /* 14B878 0024B878 000043AC */   sw        $v1, 0x0($v0)
endlabel func_0024B500
    /* 14B87C 0024B87C 00000000 */  nop
