.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024D9E4, 0x4

glabel func_0024D9E4
    /* 14D9E4 0024D9E4 00000000 */  nop
endlabel func_0024D9E4
