.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0024DA1C, 0x4

glabel func_0024DA1C
    /* 14DA1C 0024DA1C 00000000 */  nop
endlabel func_0024DA1C
