.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00251BE4, 0x4

glabel func_00251BE4
    /* 151BE4 00251BE4 00000000 */  nop
endlabel func_00251BE4
