.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00251C14, 0x4

glabel func_00251C14
    /* 151C14 00251C14 00000000 */  nop
endlabel func_00251C14
