.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00251DAC, 0x4

glabel func_00251DAC
    /* 151DAC 00251DAC 00000000 */  nop
endlabel func_00251DAC
