.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00251D84, 0x4

glabel func_00251D84
    /* 151D84 00251D84 00000000 */  nop
endlabel func_00251D84
