.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00251D6C, 0x4

glabel func_00251D6C
    /* 151D6C 00251D6C 00000000 */  nop
endlabel func_00251D6C
