.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00252F5C, 0x4

glabel func_00252F5C
    /* 152F5C 00252F5C 00000000 */  nop
endlabel func_00252F5C
