.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025C664, 0x4

glabel func_0025C664
    /* 15C664 0025C664 00000000 */  nop
endlabel func_0025C664
