.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0025E0FC, 0x4

glabel func_0025E0FC
    /* 15E0FC 0025E0FC 00000000 */  nop
endlabel func_0025E0FC
