.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00263FAC, 0x4

glabel func_00263FAC
    /* 163FAC 00263FAC 00000000 */  nop
endlabel func_00263FAC
