.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_00264024, 0x4

glabel func_00264024
    /* 164024 00264024 00000000 */  nop
endlabel func_00264024
