.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_002642D4, 0x4

glabel func_002642D4
    /* 1642D4 002642D4 00000000 */  nop
endlabel func_002642D4
