.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0026B174, 0x4

glabel func_0026B174
    /* 16B174 0026B174 00000000 */  nop
endlabel func_0026B174
