.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

.align 3
nonmatching func_0026ED88, 0x570

glabel func_0026ED88
    /* 16ED88 0026ED88 60FFBD27 */  addiu      $sp, $sp, -0xA0
    /* 16ED8C 0026ED8C 8000BEFF */  sd         $fp, 0x80($sp)
    /* 16ED90 0026ED90 2000B2FF */  sd         $s2, 0x20($sp)
    /* 16ED94 0026ED94 2DF08000 */  daddu      $fp, $a0, $zero
    /* 16ED98 0026ED98 0000B0FF */  sd         $s0, 0x0($sp)
    /* 16ED9C 0026ED9C 2D90C000 */  daddu      $s2, $a2, $zero
    /* 16EDA0 0026EDA0 9000BFFF */  sd         $ra, 0x90($sp)
    /* 16EDA4 0026EDA4 2D80A000 */  daddu      $s0, $a1, $zero
    /* 16EDA8 0026EDA8 7000B7FF */  sd         $s7, 0x70($sp)
    /* 16EDAC 0026EDAC 6000B6FF */  sd         $s6, 0x60($sp)
    /* 16EDB0 0026EDB0 5000B5FF */  sd         $s5, 0x50($sp)
    /* 16EDB4 0026EDB4 4000B4FF */  sd         $s4, 0x40($sp)
    /* 16EDB8 0026EDB8 3000B3FF */  sd         $s3, 0x30($sp)
    /* 16EDBC 0026EDBC 05000016 */  bnez       $s0, .L0026EDD4
    /* 16EDC0 0026EDC0 1000B1FF */   sd        $s1, 0x10($sp)
    /* 16EDC4 0026EDC4 52AD090C */  jal        func_0026B548
    /* 16EDC8 0026EDC8 2D284002 */   daddu     $a1, $s2, $zero
    /* 16EDCC 0026EDCC 3F010010 */  b          .L0026F2CC
    /* 16EDD0 0026EDD0 9000BFDF */   ld        $ra, 0x90($sp)
.align 2
  .L0026EDD4:
    /* 16EDD4 0026EDD4 2D20C003 */  daddu      $a0, $fp, $zero
    /* 16EDD8 0026EDD8 B8AF090C */  jal        func_0026BEE0
    /* 16EDDC 0026EDDC F8FF1126 */   addiu     $s1, $s0, -0x8
    /* 16EDE0 0026EDE0 2DA82002 */  daddu      $s5, $s1, $zero
    /* 16EDE4 0026EDE4 0400258E */  lw         $a1, 0x4($s1)
    /* 16EDE8 0026EDE8 FFFF023C */  lui        $v0, (0xFFFFFFFC >> 16)
    /* 16EDEC 0026EDEC FCFF4234 */  ori        $v0, $v0, (0xFFFFFFFC & 0xFFFF)
    /* 16EDF0 0026EDF0 13004426 */  addiu      $a0, $s2, 0x13
    /* 16EDF4 0026EDF4 24B8A200 */  and        $s7, $a1, $v0
    /* 16EDF8 0026EDF8 1F00832C */  sltiu      $v1, $a0, 0x1F
    /* 16EDFC 0026EDFC 05006014 */  bnez       $v1, .L0026EE14
    /* 16EE00 0026EE00 2D98E002 */   daddu     $s3, $s7, $zero
    /* 16EE04 0026EE04 FFFF023C */  lui        $v0, (0xFFFFFFF0 >> 16)
    /* 16EE08 0026EE08 F0FF4234 */  ori        $v0, $v0, (0xFFFFFFF0 & 0xFFFF)
    /* 16EE0C 0026EE0C 02000010 */  b          .L0026EE18
    /* 16EE10 0026EE10 24B08200 */   and       $s6, $a0, $v0
.align 2
  .L0026EE14:
    /* 16EE14 0026EE14 10001624 */  addiu      $s6, $zero, 0x10
.align 2
  .L0026EE18:
    /* 16EE18 0026EE18 2B107602 */  sltu       $v0, $s3, $s6
    /* 16EE1C 0026EE1C 0D014010 */  beqz       $v0, .L0026F254
    /* 16EE20 0026EE20 5500023C */   lui       $v0, %hi(D_00553260)
    /* 16EE24 0026EE24 2138B302 */  addu       $a3, $s5, $s3
    /* 16EE28 0026EE28 60324924 */  addiu      $t1, $v0, %lo(D_00553260)
    /* 16EE2C 0026EE2C 0800288D */  lw         $t0, 0x8($t1)
    /* 16EE30 0026EE30 0900E810 */  beq        $a3, $t0, .L0026EE58
    /* 16EE34 0026EE34 0400E48C */   lw        $a0, 0x4($a3)
    /* 16EE38 0026EE38 FFFF023C */  lui        $v0, (0xFFFFFFFE >> 16)
    /* 16EE3C 0026EE3C FEFF4234 */  ori        $v0, $v0, (0xFFFFFFFE & 0xFFFF)
    /* 16EE40 0026EE40 24108200 */  and        $v0, $a0, $v0
    /* 16EE44 0026EE44 2110E200 */  addu       $v0, $a3, $v0
    /* 16EE48 0026EE48 0400438C */  lw         $v1, 0x4($v0)
    /* 16EE4C 0026EE4C 01006330 */  andi       $v1, $v1, 0x1
    /* 16EE50 0026EE50 22006054 */  bnel       $v1, $zero, .L0026EEDC
    /* 16EE54 0026EE54 2D380000 */   daddu     $a3, $zero, $zero
.align 2
  .L0026EE58:
    /* 16EE58 0026EE58 FFFF023C */  lui        $v0, (0xFFFFFFFC >> 16)
    /* 16EE5C 0026EE5C FCFF4234 */  ori        $v0, $v0, (0xFFFFFFFC & 0xFFFF)
    /* 16EE60 0026EE60 1300E814 */  bne        $a3, $t0, .L0026EEB0
    /* 16EE64 0026EE64 24308200 */   and       $a2, $a0, $v0
    /* 16EE68 0026EE68 2118D300 */  addu       $v1, $a2, $s3
    /* 16EE6C 0026EE6C 1000C226 */  addiu      $v0, $s6, 0x10
    /* 16EE70 0026EE70 2B106200 */  sltu       $v0, $v1, $v0
    /* 16EE74 0026EE74 1B004054 */  bnel       $v0, $zero, .L0026EEE4
    /* 16EE78 0026EE78 0400A28E */   lw        $v0, 0x4($s5)
    /* 16EE7C 0026EE7C 23107600 */  subu       $v0, $v1, $s6
    /* 16EE80 0026EE80 2D20C003 */  daddu      $a0, $fp, $zero
    /* 16EE84 0026EE84 2118B602 */  addu       $v1, $s5, $s6
    /* 16EE88 0026EE88 01004234 */  ori        $v0, $v0, 0x1
    /* 16EE8C 0026EE8C 040062AC */  sw         $v0, 0x4($v1)
    /* 16EE90 0026EE90 080023AD */  sw         $v1, 0x8($t1)
    /* 16EE94 0026EE94 0400A28E */  lw         $v0, 0x4($s5)
    /* 16EE98 0026EE98 01004230 */  andi       $v0, $v0, 0x1
    /* 16EE9C 0026EE9C 25105600 */  or         $v0, $v0, $s6
    /* 16EEA0 0026EEA0 BAAF090C */  jal        func_0026BEE8
    /* 16EEA4 0026EEA4 0400A2AE */   sw        $v0, 0x4($s5)
    /* 16EEA8 0026EEA8 07010010 */  b          .L0026F2C8
    /* 16EEAC 0026EEAC 0800A226 */   addiu     $v0, $s5, 0x8
.align 2
  .L0026EEB0:
    /* 16EEB0 0026EEB0 2118D300 */  addu       $v1, $a2, $s3
    /* 16EEB4 0026EEB4 2B107600 */  sltu       $v0, $v1, $s6
    /* 16EEB8 0026EEB8 0A004054 */  bnel       $v0, $zero, .L0026EEE4
    /* 16EEBC 0026EEBC 0400A28E */   lw        $v0, 0x4($s5)
    /* 16EEC0 0026EEC0 0800E68C */  lw         $a2, 0x8($a3)
    /* 16EEC4 0026EEC4 2DB86000 */  daddu      $s7, $v1, $zero
    /* 16EEC8 0026EEC8 0C00E28C */  lw         $v0, 0xC($a3)
    /* 16EECC 0026EECC 0800B226 */  addiu      $s2, $s5, 0x8
    /* 16EED0 0026EED0 0C00C2AC */  sw         $v0, 0xC($a2)
    /* 16EED4 0026EED4 E0000010 */  b          .L0026F258
    /* 16EED8 0026EED8 080046AC */   sw        $a2, 0x8($v0)
.align 2
  .L0026EEDC:
    /* 16EEDC 0026EEDC 2D300000 */  daddu      $a2, $zero, $zero
    /* 16EEE0 0026EEE0 0400A28E */  lw         $v0, 0x4($s5)
.align 2
  .L0026EEE4:
    /* 16EEE4 0026EEE4 01004230 */  andi       $v0, $v0, 0x1
    /* 16EEE8 0026EEE8 95004014 */  bnez       $v0, .L0026F140
    /* 16EEEC 0026EEEC 2D284002 */   daddu     $a1, $s2, $zero
    /* 16EEF0 0026EEF0 0000A28E */  lw         $v0, 0x0($s5)
    /* 16EEF4 0026EEF4 FFFF033C */  lui        $v1, (0xFFFFFFFC >> 16)
    /* 16EEF8 0026EEF8 FCFF6334 */  ori        $v1, $v1, (0xFFFFFFFC & 0xFFFF)
    /* 16EEFC 0026EEFC 23A0A202 */  subu       $s4, $s5, $v0
    /* 16EF00 0026EF00 0400848E */  lw         $a0, 0x4($s4)
    /* 16EF04 0026EF04 5400E010 */  beqz       $a3, .L0026F058
    /* 16EF08 0026EF08 24208300 */   and       $a0, $a0, $v1
    /* 16EF0C 0026EF0C 5500033C */  lui        $v1, %hi(D_00553260)
    /* 16EF10 0026EF10 60326224 */  addiu      $v0, $v1, %lo(D_00553260)
    /* 16EF14 0026EF14 0800438C */  lw         $v1, 0x8($v0)
    /* 16EF18 0026EF18 4200E314 */  bne        $a3, $v1, .L0026F024
    /* 16EF1C 0026EF1C 2110C400 */   addu      $v0, $a2, $a0
    /* 16EF20 0026EF20 2118C400 */  addu       $v1, $a2, $a0
    /* 16EF24 0026EF24 1000C226 */  addiu      $v0, $s6, 0x10
    /* 16EF28 0026EF28 21B87300 */  addu       $s7, $v1, $s3
    /* 16EF2C 0026EF2C 2B10E202 */  sltu       $v0, $s7, $v0
    /* 16EF30 0026EF30 49004014 */  bnez       $v0, .L0026F058
    /* 16EF34 0026EF34 2D888002 */   daddu     $s1, $s4, $zero
    /* 16EF38 0026EF38 0C00828E */  lw         $v0, 0xC($s4)
    /* 16EF3C 0026EF3C 0800868E */  lw         $a2, 0x8($s4)
    /* 16EF40 0026EF40 0C00C2AC */  sw         $v0, 0xC($a2)
    /* 16EF44 0026EF44 080046AC */  sw         $a2, 0x8($v0)
    /* 16EF48 0026EF48 FCFF6626 */  addiu      $a2, $s3, -0x4
    /* 16EF4C 0026EF4C 2500C22C */  sltiu      $v0, $a2, 0x25
    /* 16EF50 0026EF50 24004010 */  beqz       $v0, .L0026EFE4
    /* 16EF54 0026EF54 08003226 */   addiu     $s2, $s1, 0x8
    /* 16EF58 0026EF58 2D380002 */  daddu      $a3, $s0, $zero
    /* 16EF5C 0026EF5C 1400C22C */  sltiu      $v0, $a2, 0x14
    /* 16EF60 0026EF60 17004014 */  bnez       $v0, .L0026EFC0
    /* 16EF64 0026EF64 2D284002 */   daddu     $a1, $s2, $zero
    /* 16EF68 0026EF68 0000028E */  lw         $v0, 0x0($s0)
    /* 16EF6C 0026EF6C 08000726 */  addiu      $a3, $s0, 0x8
    /* 16EF70 0026EF70 10002526 */  addiu      $a1, $s1, 0x10
    /* 16EF74 0026EF74 1C00C42C */  sltiu      $a0, $a2, 0x1C
    /* 16EF78 0026EF78 080022AE */  sw         $v0, 0x8($s1)
    /* 16EF7C 0026EF7C 0400038E */  lw         $v1, 0x4($s0)
    /* 16EF80 0026EF80 0F008014 */  bnez       $a0, .L0026EFC0
    /* 16EF84 0026EF84 0C0023AE */   sw        $v1, 0xC($s1)
    /* 16EF88 0026EF88 0800028E */  lw         $v0, 0x8($s0)
    /* 16EF8C 0026EF8C 2400C42C */  sltiu      $a0, $a2, 0x24
    /* 16EF90 0026EF90 10000726 */  addiu      $a3, $s0, 0x10
    /* 16EF94 0026EF94 18002526 */  addiu      $a1, $s1, 0x18
    /* 16EF98 0026EF98 100022AE */  sw         $v0, 0x10($s1)
    /* 16EF9C 0026EF9C 0C00038E */  lw         $v1, 0xC($s0)
    /* 16EFA0 0026EFA0 07008014 */  bnez       $a0, .L0026EFC0
    /* 16EFA4 0026EFA4 140023AE */   sw        $v1, 0x14($s1)
    /* 16EFA8 0026EFA8 1000038E */  lw         $v1, 0x10($s0)
    /* 16EFAC 0026EFAC 18000726 */  addiu      $a3, $s0, 0x18
    /* 16EFB0 0026EFB0 20002526 */  addiu      $a1, $s1, 0x20
    /* 16EFB4 0026EFB4 180023AE */  sw         $v1, 0x18($s1)
    /* 16EFB8 0026EFB8 1400028E */  lw         $v0, 0x14($s0)
    /* 16EFBC 0026EFBC 1C0022AE */  sw         $v0, 0x1C($s1)
.align 2
  .L0026EFC0:
    /* 16EFC0 0026EFC0 0000E28C */  lw         $v0, 0x0($a3)
    /* 16EFC4 0026EFC4 0400E724 */  addiu      $a3, $a3, 0x4
    /* 16EFC8 0026EFC8 0000A2AC */  sw         $v0, 0x0($a1)
    /* 16EFCC 0026EFCC 0400A524 */  addiu      $a1, $a1, 0x4
    /* 16EFD0 0026EFD0 0000E28C */  lw         $v0, 0x0($a3)
    /* 16EFD4 0026EFD4 0000A2AC */  sw         $v0, 0x0($a1)
    /* 16EFD8 0026EFD8 0400E38C */  lw         $v1, 0x4($a3)
    /* 16EFDC 0026EFDC 04000010 */  b          .L0026EFF0
    /* 16EFE0 0026EFE0 0400A3AC */   sw        $v1, 0x4($a1)
.align 2
  .L0026EFE4:
    /* 16EFE4 0026EFE4 2D280002 */  daddu      $a1, $s0, $zero
    /* 16EFE8 0026EFE8 4A90090C */  jal        func_00264128
    /* 16EFEC 0026EFEC 2D204002 */   daddu     $a0, $s2, $zero
.align 2
  .L0026EFF0:
    /* 16EFF0 0026EFF0 2310F602 */  subu       $v0, $s7, $s6
    /* 16EFF4 0026EFF4 21289602 */  addu       $a1, $s4, $s6
    /* 16EFF8 0026EFF8 01004234 */  ori        $v0, $v0, 0x1
    /* 16EFFC 0026EFFC 5500043C */  lui        $a0, %hi(D_00553260)
    /* 16F000 0026F000 0400A2AC */  sw         $v0, 0x4($a1)
    /* 16F004 0026F004 60328324 */  addiu      $v1, $a0, %lo(D_00553260)
    /* 16F008 0026F008 2D20C003 */  daddu      $a0, $fp, $zero
    /* 16F00C 0026F00C 080065AC */  sw         $a1, 0x8($v1)
    /* 16F010 0026F010 0400828E */  lw         $v0, 0x4($s4)
    /* 16F014 0026F014 01004230 */  andi       $v0, $v0, 0x1
    /* 16F018 0026F018 25105600 */  or         $v0, $v0, $s6
    /* 16F01C 0026F01C A7000010 */  b          .L0026F2BC
    /* 16F020 0026F020 040082AE */   sw        $v0, 0x4($s4)
.align 2
  .L0026F024:
    /* 16F024 0026F024 21285300 */  addu       $a1, $v0, $s3
    /* 16F028 0026F028 2B18B600 */  sltu       $v1, $a1, $s6
    /* 16F02C 0026F02C 0A006014 */  bnez       $v1, .L0026F058
    /* 16F030 0026F030 2D888002 */   daddu     $s1, $s4, $zero
    /* 16F034 0026F034 0800E68C */  lw         $a2, 0x8($a3)
    /* 16F038 0026F038 0C00E28C */  lw         $v0, 0xC($a3)
    /* 16F03C 0026F03C 2DB8A000 */  daddu      $s7, $a1, $zero
    /* 16F040 0026F040 08003226 */  addiu      $s2, $s1, 0x8
    /* 16F044 0026F044 0C00C2AC */  sw         $v0, 0xC($a2)
    /* 16F048 0026F048 080046AC */  sw         $a2, 0x8($v0)
    /* 16F04C 0026F04C 0C00828E */  lw         $v0, 0xC($s4)
    /* 16F050 0026F050 0B000010 */  b          .L0026F080
    /* 16F054 0026F054 0800868E */   lw        $a2, 0x8($s4)
.align 2
  .L0026F058:
    /* 16F058 0026F058 38008012 */  beqz       $s4, .L0026F13C
    /* 16F05C 0026F05C 21189300 */   addu      $v1, $a0, $s3
    /* 16F060 0026F060 2B107600 */  sltu       $v0, $v1, $s6
    /* 16F064 0026F064 36004014 */  bnez       $v0, .L0026F140
    /* 16F068 0026F068 2D284002 */   daddu     $a1, $s2, $zero
    /* 16F06C 0026F06C 0C00828E */  lw         $v0, 0xC($s4)
    /* 16F070 0026F070 2D888002 */  daddu      $s1, $s4, $zero
    /* 16F074 0026F074 0800868E */  lw         $a2, 0x8($s4)
    /* 16F078 0026F078 2DB86000 */  daddu      $s7, $v1, $zero
    /* 16F07C 0026F07C 08003226 */  addiu      $s2, $s1, 0x8
.align 2
  .L0026F080:
    /* 16F080 0026F080 0C00C2AC */  sw         $v0, 0xC($a2)
    /* 16F084 0026F084 080046AC */  sw         $a2, 0x8($v0)
    /* 16F088 0026F088 FCFF6626 */  addiu      $a2, $s3, -0x4
    /* 16F08C 0026F08C 2500C22C */  sltiu      $v0, $a2, 0x25
    /* 16F090 0026F090 25004010 */  beqz       $v0, .L0026F128
    /* 16F094 0026F094 2D380002 */   daddu     $a3, $s0, $zero
    /* 16F098 0026F098 1400C22C */  sltiu      $v0, $a2, 0x14
    /* 16F09C 0026F09C 18004014 */  bnez       $v0, .L0026F100
    /* 16F0A0 0026F0A0 2D284002 */   daddu     $a1, $s2, $zero
    /* 16F0A4 0026F0A4 0000028E */  lw         $v0, 0x0($s0)
    /* 16F0A8 0026F0A8 08000726 */  addiu      $a3, $s0, 0x8
    /* 16F0AC 0026F0AC 10002526 */  addiu      $a1, $s1, 0x10
    /* 16F0B0 0026F0B0 1C00C42C */  sltiu      $a0, $a2, 0x1C
    /* 16F0B4 0026F0B4 080022AE */  sw         $v0, 0x8($s1)
    /* 16F0B8 0026F0B8 0400038E */  lw         $v1, 0x4($s0)
    /* 16F0BC 0026F0BC 10008014 */  bnez       $a0, .L0026F100
    /* 16F0C0 0026F0C0 0C0023AE */   sw        $v1, 0xC($s1)
    /* 16F0C4 0026F0C4 0800028E */  lw         $v0, 0x8($s0)
    /* 16F0C8 0026F0C8 2400C42C */  sltiu      $a0, $a2, 0x24
    /* 16F0CC 0026F0CC 10000726 */  addiu      $a3, $s0, 0x10
    /* 16F0D0 0026F0D0 18002526 */  addiu      $a1, $s1, 0x18
    /* 16F0D4 0026F0D4 100022AE */  sw         $v0, 0x10($s1)
    /* 16F0D8 0026F0D8 0C00038E */  lw         $v1, 0xC($s0)
    /* 16F0DC 0026F0DC 08008014 */  bnez       $a0, .L0026F100
    /* 16F0E0 0026F0E0 140023AE */   sw        $v1, 0x14($s1)
    /* 16F0E4 0026F0E4 1000038E */  lw         $v1, 0x10($s0)
    /* 16F0E8 0026F0E8 18000726 */  addiu      $a3, $s0, 0x18
    /* 16F0EC 0026F0EC 20002526 */  addiu      $a1, $s1, 0x20
    /* 16F0F0 0026F0F0 180023AE */  sw         $v1, 0x18($s1)
    /* 16F0F4 0026F0F4 1400028E */  lw         $v0, 0x14($s0)
    /* 16F0F8 0026F0F8 1C0022AE */  sw         $v0, 0x1C($s1)
    /* 16F0FC 0026F0FC 00000000 */  nop
.align 2
  .L0026F100:
    /* 16F100 0026F100 0000E28C */  lw         $v0, 0x0($a3)
    /* 16F104 0026F104 0400E724 */  addiu      $a3, $a3, 0x4
    /* 16F108 0026F108 0000A2AC */  sw         $v0, 0x0($a1)
    /* 16F10C 0026F10C 0400A524 */  addiu      $a1, $a1, 0x4
    /* 16F110 0026F110 0000E28C */  lw         $v0, 0x0($a3)
    /* 16F114 0026F114 0000A2AC */  sw         $v0, 0x0($a1)
    /* 16F118 0026F118 0400E38C */  lw         $v1, 0x4($a3)
    /* 16F11C 0026F11C 0400A3AC */  sw         $v1, 0x4($a1)
    /* 16F120 0026F120 4D000010 */  b          .L0026F258
    /* 16F124 0026F124 0400858E */   lw        $a1, 0x4($s4)
.align 2
  .L0026F128:
    /* 16F128 0026F128 2D280002 */  daddu      $a1, $s0, $zero
    /* 16F12C 0026F12C 4A90090C */  jal        func_00264128
    /* 16F130 0026F130 2D204002 */   daddu     $a0, $s2, $zero
    /* 16F134 0026F134 48000010 */  b          .L0026F258
    /* 16F138 0026F138 0400258E */   lw        $a1, 0x4($s1)
.align 2
  .L0026F13C:
    /* 16F13C 0026F13C 2D284002 */  daddu      $a1, $s2, $zero
.align 2
  .L0026F140:
    /* 16F140 0026F140 52AD090C */  jal        func_0026B548
    /* 16F144 0026F144 2D20C003 */   daddu     $a0, $fp, $zero
    /* 16F148 0026F148 2D904000 */  daddu      $s2, $v0, $zero
    /* 16F14C 0026F14C 05004056 */  bnel       $s2, $zero, .L0026F164
    /* 16F150 0026F150 0400A58E */   lw        $a1, 0x4($s5)
    /* 16F154 0026F154 BAAF090C */  jal        func_0026BEE8
    /* 16F158 0026F158 2D20C003 */   daddu     $a0, $fp, $zero
    /* 16F15C 0026F15C 5A000010 */  b          .L0026F2C8
    /* 16F160 0026F160 2D100000 */   daddu     $v0, $zero, $zero
.align 2
  .L0026F164:
    /* 16F164 0026F164 FFFF023C */  lui        $v0, (0xFFFFFFFE >> 16)
    /* 16F168 0026F168 FEFF4234 */  ori        $v0, $v0, (0xFFFFFFFE & 0xFFFF)
    /* 16F16C 0026F16C F8FF5126 */  addiu      $s1, $s2, -0x8
    /* 16F170 0026F170 2410A200 */  and        $v0, $a1, $v0
    /* 16F174 0026F174 2110A202 */  addu       $v0, $s5, $v0
    /* 16F178 0026F178 09002216 */  bne        $s1, $v0, .L0026F1A0
    /* 16F17C 0026F17C FCFF6626 */   addiu     $a2, $s3, -0x4
    /* 16F180 0026F180 0400238E */  lw         $v1, 0x4($s1)
    /* 16F184 0026F184 FFFF023C */  lui        $v0, (0xFFFFFFFC >> 16)
    /* 16F188 0026F188 FCFF4234 */  ori        $v0, $v0, (0xFFFFFFFC & 0xFFFF)
    /* 16F18C 0026F18C 2D88A002 */  daddu      $s1, $s5, $zero
    /* 16F190 0026F190 24186200 */  and        $v1, $v1, $v0
    /* 16F194 0026F194 08003226 */  addiu      $s2, $s1, 0x8
    /* 16F198 0026F198 2F000010 */  b          .L0026F258
    /* 16F19C 0026F19C 21B86302 */   addu      $s7, $s3, $v1
.align 2
  .L0026F1A0:
    /* 16F1A0 0026F1A0 2500C22C */  sltiu      $v0, $a2, 0x25
    /* 16F1A4 0026F1A4 23004010 */  beqz       $v0, .L0026F234
    /* 16F1A8 0026F1A8 2D380002 */   daddu     $a3, $s0, $zero
    /* 16F1AC 0026F1AC 1400C22C */  sltiu      $v0, $a2, 0x14
    /* 16F1B0 0026F1B0 17004014 */  bnez       $v0, .L0026F210
    /* 16F1B4 0026F1B4 2D284002 */   daddu     $a1, $s2, $zero
    /* 16F1B8 0026F1B8 0000028E */  lw         $v0, 0x0($s0)
    /* 16F1BC 0026F1BC 08000726 */  addiu      $a3, $s0, 0x8
    /* 16F1C0 0026F1C0 08004526 */  addiu      $a1, $s2, 0x8
    /* 16F1C4 0026F1C4 1C00C42C */  sltiu      $a0, $a2, 0x1C
    /* 16F1C8 0026F1C8 000042AE */  sw         $v0, 0x0($s2)
    /* 16F1CC 0026F1CC 0400038E */  lw         $v1, 0x4($s0)
    /* 16F1D0 0026F1D0 0F008014 */  bnez       $a0, .L0026F210
    /* 16F1D4 0026F1D4 040043AE */   sw        $v1, 0x4($s2)
    /* 16F1D8 0026F1D8 0800028E */  lw         $v0, 0x8($s0)
    /* 16F1DC 0026F1DC 2400C42C */  sltiu      $a0, $a2, 0x24
    /* 16F1E0 0026F1E0 10000726 */  addiu      $a3, $s0, 0x10
    /* 16F1E4 0026F1E4 10004526 */  addiu      $a1, $s2, 0x10
    /* 16F1E8 0026F1E8 080042AE */  sw         $v0, 0x8($s2)
    /* 16F1EC 0026F1EC 0C00038E */  lw         $v1, 0xC($s0)
    /* 16F1F0 0026F1F0 07008014 */  bnez       $a0, .L0026F210
    /* 16F1F4 0026F1F4 0C0043AE */   sw        $v1, 0xC($s2)
    /* 16F1F8 0026F1F8 1000038E */  lw         $v1, 0x10($s0)
    /* 16F1FC 0026F1FC 18000726 */  addiu      $a3, $s0, 0x18
    /* 16F200 0026F200 18004526 */  addiu      $a1, $s2, 0x18
    /* 16F204 0026F204 100043AE */  sw         $v1, 0x10($s2)
    /* 16F208 0026F208 1400028E */  lw         $v0, 0x14($s0)
    /* 16F20C 0026F20C 140042AE */  sw         $v0, 0x14($s2)
.align 2
  .L0026F210:
    /* 16F210 0026F210 0000E28C */  lw         $v0, 0x0($a3)
    /* 16F214 0026F214 0400E724 */  addiu      $a3, $a3, 0x4
    /* 16F218 0026F218 0000A2AC */  sw         $v0, 0x0($a1)
    /* 16F21C 0026F21C 0400A524 */  addiu      $a1, $a1, 0x4
    /* 16F220 0026F220 0000E28C */  lw         $v0, 0x0($a3)
    /* 16F224 0026F224 0000A2AC */  sw         $v0, 0x0($a1)
    /* 16F228 0026F228 0400E38C */  lw         $v1, 0x4($a3)
    /* 16F22C 0026F22C 04000010 */  b          .L0026F240
    /* 16F230 0026F230 0400A3AC */   sw        $v1, 0x4($a1)
.align 2
  .L0026F234:
    /* 16F234 0026F234 2D204002 */  daddu      $a0, $s2, $zero
    /* 16F238 0026F238 4A90090C */  jal        func_00264128
    /* 16F23C 0026F23C 2D280002 */   daddu     $a1, $s0, $zero
.align 2
  .L0026F240:
    /* 16F240 0026F240 2D280002 */  daddu      $a1, $s0, $zero
    /* 16F244 0026F244 ECA9090C */  jal        func_0026A7B0
    /* 16F248 0026F248 2D20C003 */   daddu     $a0, $fp, $zero
    /* 16F24C 0026F24C 1B000010 */  b          .L0026F2BC
    /* 16F250 0026F250 2D20C003 */   daddu     $a0, $fp, $zero
.align 2
  .L0026F254:
    /* 16F254 0026F254 0800B226 */  addiu      $s2, $s5, 0x8
.align 2
  .L0026F258:
    /* 16F258 0026F258 2320F602 */  subu       $a0, $s7, $s6
    /* 16F25C 0026F25C 1000822C */  sltiu      $v0, $a0, 0x10
    /* 16F260 0026F260 0F004014 */  bnez       $v0, .L0026F2A0
    /* 16F264 0026F264 0100A230 */   andi      $v0, $a1, 0x1
    /* 16F268 0026F268 01008334 */  ori        $v1, $a0, 0x1
    /* 16F26C 0026F26C 25105600 */  or         $v0, $v0, $s6
    /* 16F270 0026F270 21283602 */  addu       $a1, $s1, $s6
    /* 16F274 0026F274 040022AE */  sw         $v0, 0x4($s1)
    /* 16F278 0026F278 2130A400 */  addu       $a2, $a1, $a0
    /* 16F27C 0026F27C 0400A3AC */  sw         $v1, 0x4($a1)
    /* 16F280 0026F280 2D20C003 */  daddu      $a0, $fp, $zero
    /* 16F284 0026F284 0800A524 */  addiu      $a1, $a1, 0x8
    /* 16F288 0026F288 0400C28C */  lw         $v0, 0x4($a2)
    /* 16F28C 0026F28C 01004234 */  ori        $v0, $v0, 0x1
    /* 16F290 0026F290 ECA9090C */  jal        func_0026A7B0
    /* 16F294 0026F294 0400C2AC */   sw        $v0, 0x4($a2)
    /* 16F298 0026F298 08000010 */  b          .L0026F2BC
    /* 16F29C 0026F29C 2D20C003 */   daddu     $a0, $fp, $zero
.align 2
  .L0026F2A0:
    /* 16F2A0 0026F2A0 21203702 */  addu       $a0, $s1, $s7
    /* 16F2A4 0026F2A4 25105700 */  or         $v0, $v0, $s7
    /* 16F2A8 0026F2A8 040022AE */  sw         $v0, 0x4($s1)
    /* 16F2AC 0026F2AC 0400838C */  lw         $v1, 0x4($a0)
    /* 16F2B0 0026F2B0 01006334 */  ori        $v1, $v1, 0x1
    /* 16F2B4 0026F2B4 040083AC */  sw         $v1, 0x4($a0)
    /* 16F2B8 0026F2B8 2D20C003 */  daddu      $a0, $fp, $zero
.align 2
  .L0026F2BC:
    /* 16F2BC 0026F2BC BAAF090C */  jal        func_0026BEE8
    /* 16F2C0 0026F2C0 00000000 */   nop
    /* 16F2C4 0026F2C4 2D104002 */  daddu      $v0, $s2, $zero
.align 2
  .L0026F2C8:
    /* 16F2C8 0026F2C8 9000BFDF */  ld         $ra, 0x90($sp)
.align 2
  .L0026F2CC:
    /* 16F2CC 0026F2CC 8000BEDF */  ld         $fp, 0x80($sp)
    /* 16F2D0 0026F2D0 7000B7DF */  ld         $s7, 0x70($sp)
    /* 16F2D4 0026F2D4 6000B6DF */  ld         $s6, 0x60($sp)
    /* 16F2D8 0026F2D8 5000B5DF */  ld         $s5, 0x50($sp)
    /* 16F2DC 0026F2DC 4000B4DF */  ld         $s4, 0x40($sp)
    /* 16F2E0 0026F2E0 3000B3DF */  ld         $s3, 0x30($sp)
    /* 16F2E4 0026F2E4 2000B2DF */  ld         $s2, 0x20($sp)
    /* 16F2E8 0026F2E8 1000B1DF */  ld         $s1, 0x10($sp)
    /* 16F2EC 0026F2EC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 16F2F0 0026F2F0 0800E003 */  jr         $ra
    /* 16F2F4 0026F2F4 A000BD27 */   addiu     $sp, $sp, 0xA0
endlabel func_0026ED88

.align 3
/* Handwritten function */
nonmatching func_0026F2F8, 0xA4

glabel func_0026F2F8
    /* 16F2F8 0026F2F8 FFFF073C */  lui        $a3, (0xFFFFF000 >> 16)
    /* 16F2FC 0026F2FC 2D300000 */  daddu      $a2, $zero, $zero
    /* 16F300 0026F300 00F0E734 */  ori        $a3, $a3, (0xFFFFF000 & 0xFFFF)
    /* 16F304 0026F304 00000000 */  nop
.align 2
  .L0026F308:
    /* 16F308 0026F308 0F000000 */  sync
    /* 16F30C 0026F30C 0000D0BC */  cache      0x10, 0x0($a2) /* handwritten instruction */
    /* 16F310 0026F310 0F000000 */  sync
    /* 16F314 0026F314 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 16F318 0026F318 24104700 */  and        $v0, $v0, $a3
    /* 16F31C 0026F31C 21104600 */  addu       $v0, $v0, $a2
    /* 16F320 0026F320 2B18A200 */  sltu       $v1, $a1, $v0
    /* 16F324 0026F324 2B104400 */  sltu       $v0, $v0, $a0
    /* 16F328 0026F328 06004014 */  bnez       $v0, .L0026F344
    /* 16F32C 0026F32C 00000000 */   nop
    /* 16F330 0026F330 04006014 */  bnez       $v1, .L0026F344
    /* 16F334 0026F334 00000000 */   nop
    /* 16F338 0026F338 0F000000 */  sync
    /* 16F33C 0026F33C 0000D4BC */  cache      0x14, 0x0($a2) /* handwritten instruction */
    /* 16F340 0026F340 0F000000 */  sync
.align 2
  .L0026F344:
    /* 16F344 0026F344 0F000000 */  sync
    /* 16F348 0026F348 0100D0BC */  cache      0x10, 0x1($a2) /* handwritten instruction */
    /* 16F34C 0026F34C 0F000000 */  sync
    /* 16F350 0026F350 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 16F354 0026F354 24104700 */  and        $v0, $v0, $a3
    /* 16F358 0026F358 21104600 */  addu       $v0, $v0, $a2
    /* 16F35C 0026F35C 2B18A200 */  sltu       $v1, $a1, $v0
    /* 16F360 0026F360 2B104400 */  sltu       $v0, $v0, $a0
    /* 16F364 0026F364 06004014 */  bnez       $v0, .L0026F380
    /* 16F368 0026F368 00000000 */   nop
    /* 16F36C 0026F36C 04006014 */  bnez       $v1, .L0026F380
    /* 16F370 0026F370 00000000 */   nop
    /* 16F374 0026F374 0F000000 */  sync
    /* 16F378 0026F378 0100D4BC */  cache      0x14, 0x1($a2) /* handwritten instruction */
    /* 16F37C 0026F37C 0F000000 */  sync
.align 2
  .L0026F380:
    /* 16F380 0026F380 0F000000 */  sync
    /* 16F384 0026F384 4000C624 */  addiu      $a2, $a2, 0x40
    /* 16F388 0026F388 0010C228 */  slti       $v0, $a2, 0x1000
    /* 16F38C 0026F38C DEFF4014 */  bnez       $v0, .L0026F308
    /* 16F390 0026F390 00000000 */   nop
    /* 16F394 0026F394 0800E003 */  jr         $ra
    /* 16F398 0026F398 00000000 */   nop
endlabel func_0026F2F8
    /* 16F39C 0026F39C 00000000 */  nop

.align 3
/* Handwritten function */
nonmatching func_0026F3A0, 0x7C

glabel func_0026F3A0
    /* 16F3A0 0026F3A0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 16F3A4 0026F3A4 2000B2FF */  sd         $s2, 0x20($sp)
    /* 16F3A8 0026F3A8 1000B1FF */  sd         $s1, 0x10($sp)
    /* 16F3AC 0026F3AC 2D908000 */  daddu      $s2, $a0, $zero
    /* 16F3B0 0026F3B0 3000BFFF */  sd         $ra, 0x30($sp)
    /* 16F3B4 0026F3B4 2D88A000 */  daddu      $s1, $a1, $zero
    /* 16F3B8 0026F3B8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 16F3BC 0026F3BC 00601040 */  mfc0       $s0, $12 /* handwritten instruction */
    /* 16F3C0 0026F3C0 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 16F3C4 0026F3C4 24800202 */  and        $s0, $s0, $v0
    /* 16F3C8 0026F3C8 03000012 */  beqz       $s0, .L0026F3D8
    /* 16F3CC 0026F3CC 00000000 */   nop
    /* 16F3D0 0026F3D0 9006040C */  jal        func_00101A40
    /* 16F3D4 0026F3D4 00000000 */   nop
.align 2
  .L0026F3D8:
    /* 16F3D8 0026F3D8 FFFF043C */  lui        $a0, (0xFFFFFFC0 >> 16)
    /* 16F3DC 0026F3DC C0FF8434 */  ori        $a0, $a0, (0xFFFFFFC0 & 0xFFFF)
    /* 16F3E0 0026F3E0 24282402 */  and        $a1, $s1, $a0
    /* 16F3E4 0026F3E4 BEBC090C */  jal        func_0026F2F8
    /* 16F3E8 0026F3E8 24204402 */   and       $a0, $s2, $a0
    /* 16F3EC 0026F3EC 06000012 */  beqz       $s0, .L0026F408
    /* 16F3F0 0026F3F0 3000BFDF */   ld        $ra, 0x30($sp)
    /* 16F3F4 0026F3F4 2000B2DF */  ld         $s2, 0x20($sp)
    /* 16F3F8 0026F3F8 1000B1DF */  ld         $s1, 0x10($sp)
    /* 16F3FC 0026F3FC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 16F400 0026F400 A2060408 */  j          func_00101A88
    /* 16F404 0026F404 4000BD27 */   addiu     $sp, $sp, 0x40
.align 2
  .L0026F408:
    /* 16F408 0026F408 2000B2DF */  ld         $s2, 0x20($sp)
    /* 16F40C 0026F40C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 16F410 0026F410 0000B0DF */  ld         $s0, 0x0($sp)
    /* 16F414 0026F414 0800E003 */  jr         $ra
    /* 16F418 0026F418 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_0026F3A0
    /* 16F41C 0026F41C 00000000 */  nop
