.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.3 */

nonmatching func_0026F434, 0x4

glabel func_0026F434
    /* 16F434 0026F434 00000000 */  nop
endlabel func_0026F434

/* Handwritten function */
nonmatching func_0026F438, 0xA4

glabel func_0026F438
    /* 16F438 0026F438 FFFF073C */  lui        $a3, (0xFFFFF000 >> 16)
    /* 16F43C 0026F43C 2D300000 */  daddu      $a2, $zero, $zero
    /* 16F440 0026F440 00F0E734 */  ori        $a3, $a3, (0xFFFFF000 & 0xFFFF)
    /* 16F444 0026F444 00000000 */  nop
.align 2
  .L0026F448:
    /* 16F448 0026F448 0F000000 */  sync
    /* 16F44C 0026F44C 0000D0BC */  cache      0x10, 0x0($a2) /* handwritten instruction */
    /* 16F450 0026F450 0F000000 */  sync
    /* 16F454 0026F454 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 16F458 0026F458 24104700 */  and        $v0, $v0, $a3
    /* 16F45C 0026F45C 21104600 */  addu       $v0, $v0, $a2
    /* 16F460 0026F460 2B18A200 */  sltu       $v1, $a1, $v0
    /* 16F464 0026F464 2B104400 */  sltu       $v0, $v0, $a0
    /* 16F468 0026F468 06004014 */  bnez       $v0, .L0026F484
    /* 16F46C 0026F46C 00000000 */   nop
    /* 16F470 0026F470 04006014 */  bnez       $v1, .L0026F484
    /* 16F474 0026F474 00000000 */   nop
    /* 16F478 0026F478 0F000000 */  sync
    /* 16F47C 0026F47C 0000D6BC */  cache      0x16, 0x0($a2) /* handwritten instruction */
    /* 16F480 0026F480 0F000000 */  sync
.align 2
  .L0026F484:
    /* 16F484 0026F484 0F000000 */  sync
    /* 16F488 0026F488 0100D0BC */  cache      0x10, 0x1($a2) /* handwritten instruction */
    /* 16F48C 0026F48C 0F000000 */  sync
    /* 16F490 0026F490 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 16F494 0026F494 24104700 */  and        $v0, $v0, $a3
    /* 16F498 0026F498 21104600 */  addu       $v0, $v0, $a2
    /* 16F49C 0026F49C 2B18A200 */  sltu       $v1, $a1, $v0
    /* 16F4A0 0026F4A0 2B104400 */  sltu       $v0, $v0, $a0
    /* 16F4A4 0026F4A4 06004014 */  bnez       $v0, .L0026F4C0
    /* 16F4A8 0026F4A8 00000000 */   nop
    /* 16F4AC 0026F4AC 04006014 */  bnez       $v1, .L0026F4C0
    /* 16F4B0 0026F4B0 00000000 */   nop
    /* 16F4B4 0026F4B4 0F000000 */  sync
    /* 16F4B8 0026F4B8 0100D6BC */  cache      0x16, 0x1($a2) /* handwritten instruction */
    /* 16F4BC 0026F4BC 0F000000 */  sync
.align 2
  .L0026F4C0:
    /* 16F4C0 0026F4C0 0F000000 */  sync
    /* 16F4C4 0026F4C4 4000C624 */  addiu      $a2, $a2, 0x40
    /* 16F4C8 0026F4C8 0010C228 */  slti       $v0, $a2, 0x1000
    /* 16F4CC 0026F4CC DEFF4014 */  bnez       $v0, .L0026F448
    /* 16F4D0 0026F4D0 00000000 */   nop
    /* 16F4D4 0026F4D4 0800E003 */  jr         $ra
    /* 16F4D8 0026F4D8 00000000 */   nop
endlabel func_0026F438
    /* 16F4DC 0026F4DC 00000000 */  nop

/* Handwritten function */
nonmatching func_0026F4E0, 0x7C

glabel func_0026F4E0
    /* 16F4E0 0026F4E0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 16F4E4 0026F4E4 2000B2FF */  sd         $s2, 0x20($sp)
    /* 16F4E8 0026F4E8 1000B1FF */  sd         $s1, 0x10($sp)
    /* 16F4EC 0026F4EC 2D908000 */  daddu      $s2, $a0, $zero
    /* 16F4F0 0026F4F0 3000BFFF */  sd         $ra, 0x30($sp)
    /* 16F4F4 0026F4F4 2D88A000 */  daddu      $s1, $a1, $zero
    /* 16F4F8 0026F4F8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 16F4FC 0026F4FC 00601040 */  mfc0       $s0, $12 /* handwritten instruction */
    /* 16F500 0026F500 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 16F504 0026F504 24800202 */  and        $s0, $s0, $v0
    /* 16F508 0026F508 03000012 */  beqz       $s0, .L0026F518
    /* 16F50C 0026F50C 00000000 */   nop
    /* 16F510 0026F510 9006040C */  jal        func_00101A40
    /* 16F514 0026F514 00000000 */   nop
.align 2
  .L0026F518:
    /* 16F518 0026F518 FFFF043C */  lui        $a0, (0xFFFFFFC0 >> 16)
    /* 16F51C 0026F51C C0FF8434 */  ori        $a0, $a0, (0xFFFFFFC0 & 0xFFFF)
    /* 16F520 0026F520 24282402 */  and        $a1, $s1, $a0
    /* 16F524 0026F524 0EBD090C */  jal        func_0026F438
    /* 16F528 0026F528 24204402 */   and       $a0, $s2, $a0
    /* 16F52C 0026F52C 06000012 */  beqz       $s0, .L0026F548
    /* 16F530 0026F530 3000BFDF */   ld        $ra, 0x30($sp)
    /* 16F534 0026F534 2000B2DF */  ld         $s2, 0x20($sp)
    /* 16F538 0026F538 1000B1DF */  ld         $s1, 0x10($sp)
    /* 16F53C 0026F53C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 16F540 0026F540 A2060408 */  j          func_00101A88
    /* 16F544 0026F544 4000BD27 */   addiu     $sp, $sp, 0x40
.align 2
  .L0026F548:
    /* 16F548 0026F548 2000B2DF */  ld         $s2, 0x20($sp)
    /* 16F54C 0026F54C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 16F550 0026F550 0000B0DF */  ld         $s0, 0x0($sp)
    /* 16F554 0026F554 0800E003 */  jr         $ra
    /* 16F558 0026F558 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_0026F4E0
    /* 16F55C 0026F55C 00000000 */  nop
