/* crt0: the SDK start-up module.  MAIN.MAP puts crt0.o(.text) at the head
 * of .text and SRCFILE.TXT attributes these instructions to
 * /usr/local/sce/ee/lib/crt0.s.  One object, so the partition is trivial;
 * the January link built a 0xC8-byte crt0 against this run of 0x110, so no
 * size tiling is claimed. */
#include "common.h"

/* The eight zero bytes the listing labels <_start-0x8>: crt0.s's pre-entry pad,
 * not a function.  Emitted here as data so the ROM run starts at the same
 * address and the dashboard stops counting a function that never existed. */
__asm__(".section .text\n"
        "    .set at\n"
        "    .set noreorder\n"
        "    .align 3\n"
        ".global D_00100000\n"
        "D_00100000:\n"
        "    .word 0, 0\n"
        "    .set reorder\n"
        "    .set at\n");

/* crt0.s's entry point, transcribed from the shipped instruction stream:
 * SRCFILE.TXT attributes every instruction of this member to
 * /usr/local/sce/ee/lib/crt0.s, so there is no C for it to be compiled
 * from.  `sq`, `syscall` and `ei` have no C spelling either. */

__asm__(".section .text\n"
        "    .set noat\n"
        "    .set noreorder\n"
        "    .align 3\n"
        "    .globl _start\n"
        "    .type _start, @function\n"
        "_start:\n"
        "    lui $2, %hi(D_0063C100)\n"
        "    lui $3, %hi(D_736198)\n"
        "    addiu $2, $2, %lo(D_0063C100)\n"
        "    addiu $3, $3, %lo(D_736198)\n"
        "    .align 2\n"
        "    .L00100018:\n"
        "    sq $0, 0x0($2)\n"
        "    sltu $1, $2, $3\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    bnez $1, .L00100018\n"
        "    addiu $2, $2, 0x10\n"
        "    lui $4, %hi(D_00640AF0)\n"
        "    lui $5, %hi(D_1FF0000)\n"
        "    lui $6, %hi(D_10000)\n"
        "    lui $7, %hi(D_0063C600)\n"
        "    lui $8, %hi(_root)\n"
        "    addiu $4, $4, %lo(D_00640AF0)\n"
        "    addiu $5, $5, %lo(D_1FF0000)\n"
        "    addiu $6, $6, %lo(D_10000)\n"
        "    addiu $7, $7, %lo(D_0063C600)\n"
        "    addiu $8, $8, %lo(_root)\n"
        "    daddu $28, $4, $0\n"
        "    addiu $3, $0, 0x3C\n"
        "    syscall 0\n"
        "    daddu $29, $2, $0\n"
        "    lui $4, %hi(D_736198)\n"
        "    lui $5, %hi(D_10000)\n"
        "    addiu $4, $4, %lo(D_736198)\n"
        "    addiu $5, $5, %lo(D_10000)\n"
        "    addiu $3, $0, 0x3D\n"
        "    syscall 0\n"
        "    jal _InitSys\n"
        "    nop\n"
        "    jal FlushCache\n"
        "    daddu $4, $0, $0\n"
        "    ei\n"
        "    lui $2, %hi(D_0063C600)\n"
        "    addiu $2, $2, %lo(D_0063C600)\n"
        "    lw $4, 0x0($2)\n"
        "    jal main\n"
        "    addiu $5, $2, 0x4\n"
        "    j Exit\n"
        "    daddu $4, $2, $0\n"
        "    .size _start, . - _start\n"
        "    .set reorder\n"
        "    .set at\n");

__asm__(".section .text\n"
        "    .set at\n"
        "    .set noreorder\n"
        "    .align 3\n"
        "    .globl _exit\n"
        "    .type _exit, @function\n"
        "_exit:\n"
        "    j Exit\n"
        "    daddu $4, $0, $0\n"
        "    .size _exit, . - _exit\n"
        "    .set reorder\n"
        "    .set at\n");

__asm__(".section .text\n"
        "    .set at\n"
        "    .set noreorder\n"
        "    .align 3\n"
        "    .globl _root\n"
        "    .type _root, @function\n"
        "_root:\n"
        "    addiu $3, $0, 0x23\n"
        "    syscall 0\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    nop\n"
        "    addiu $3, $0, 0x0\n"
        "    syscall 0\n"
        "    jr $31\n"
        "    nop\n"
        "    .size _root, . - _root\n"
        "    .set reorder\n"
        "    .set at\n");
