/* libgraph.a member graph002.o.  MAIN.MAP member spans tile this run exactly and
 * this member starts at an 8-aligned function start of the shipped ELF. */
#include "common.h"
#include "r5900.h"
#include "vu0.h"
#include "math_private.h"
#include "math_private.h"

__asm__(".section .text\n"
        "    .set noat\n"
        "    .set noreorder\n"
        "    .global sceGsResetPath\n"
        "    .type sceGsResetPath, @function\n"
        "    .align 3\n"
        "sceGsResetPath:\n"
        "    lui   $2, 0x1000\n"
        "    addiu $7, $0, 0x1\n"
        "    ori   $2, $2, 0x3C10\n"
        "    lui   $3, 0x1000\n"
        "    sw    $7, 0x0($2)\n"
        "    ori   $3, $3, 0x3C20\n"
        "    addiu $2, $0, 0x2\n"
        "    daddu $4, $0, $0\n"
        "    sw    $2, 0x0($3)\n"
        "    sync\n"
        "    cfc2.ni $4, $vi28\n"
        "    ori   $4, $4, 0x200\n"
        "    ctc2.ni $4, $vi28\n"
        "    sync.p\n"
        "    lui   $5, %hi(D_0054A2C0)\n"
        "    lui   $6, 0x1000\n"
        "    addiu $5, $5, %lo(D_0054A2C0)\n"
        "    ori   $6, $6, 0x5000\n"
        "    lq    $4, 0x0($5)\n"
        "    lui   $3, 0x1000\n"
        "    ori   $3, $3, 0x3000\n"
        "    sq    $4, 0x0($6)\n"
        "    lq    $2, 0x10($5)\n"
        "    sq    $2, 0x0($6)\n"
        "    jr    $31\n"
        "    sw    $7, 0x0($3)\n"
        "    .size sceGsResetPath, . - sceGsResetPath\n"
        "    .set reorder\n"
        "    .set at\n");
