#!/usr/bin/env python3
"""tools/easy_pickups.py — build decomp/easy_pickups.md, the small-function
convergence queue for this target.

Two sections, kept separate on purpose (user directive 2026-09-04):

  1. NEAR-MISS PORTS — functions whose body from another version (ntsc, aug6)
     compiled to ALMOST the right bytes here and was reverted `codegen` by the
     port driver.  Ranked by differing-instruction count, then size.  Source:
     .port_cache/candidates*.json + decomp/port_ledger*.md (one pair per
     source version; pass extra `--scan NAME=candidates.json:ledger.md`).
  2. SMALL UNMATCHED — every still-INCLUDE_ASM function of at most
     `--max-insns` instructions (default 15), smallest first.  NOT the full
     unmatched list.

Usage:  .venv/bin/python tools/easy_pickups.py [--max-insns 15]
        [--scan ntsc=.port_cache/candidates.json:decomp/port_ledger_pal.md]
"""
from __future__ import annotations
import argparse, glob, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from ico_version import detect_version, asm_root  # noqa: E402

VER = detect_version(ROOT)
ASM = ROOT / asm_root(ROOT, VER)
OUT = ROOT / "decomp" / "easy_pickups.md"
SRC_GLOBS = ("src/*.c", "src/cod/*.c", "ios/*.c", "isys/*.c", "sound/*.c", "ito/*/*.c")
INSN_RE = re.compile(r"^\s*/\*\s*[0-9A-F]+\s+[0-9A-F]{8}\s+[0-9A-F]{8}\s*\*/", re.M)


def ledger_status(path: Path) -> dict[str, tuple[str, str, str]]:
    out = {}
    if not path.exists():
        return out
    for m in re.finditer(r"^- (PORTED|REVERTED) `(\w+)`[^\n]*?(?:—\s*\[([\w-]+)\](.*))?$",
                         path.read_text(errors="replace"), re.M):
        out[m.group(2)] = (m.group(1), m.group(3) or "", (m.group(4) or "").strip())
    return out


def near_misses(scans: list[tuple[str, Path, Path]]):
    rows = []
    for ver, cand, ledger in scans:
        if not cand.exists():
            print(f"easy_pickups: no {cand}; skipping {ver}", file=sys.stderr)
            continue
        st = ledger_status(ledger)
        recs = json.loads(cand.read_text())
        recs = recs["records"] if isinstance(recs, dict) else recs
        for r in recs:
            s = st.get(r["name"])
            if not s or s[0] != "REVERTED" or s[1] != "codegen":
                continue
            rows.append({
                "name": r["name"], "vma": r["pal_vma"], "tu": r["pal_tu"],
                "src": ver, "src_name": r.get("us_name") or r.get("aug6_name") or "",
                "src_insns": r["src_insns"], "pal_insns": r["pal_insns"],
                "diff": r["diff_count"], "verdict": r["verdict"],
                "classes": ",".join(r.get("classes") or []), "first": s[2],
            })
    # a function reached from two versions keeps its smallest diff
    best: dict[str, dict] = {}
    for r in rows:
        if r["name"] not in best or r["diff"] < best[r["name"]]["diff"]:
            best[r["name"]] = r
    return sorted(best.values(), key=lambda r: (r["diff"], r["pal_insns"], r["name"]))


def stubs() -> dict[str, str]:
    """INCLUDE_ASM'd function -> asm dir."""
    out = {}
    for g in SRC_GLOBS:
        for f in glob.glob(str(ROOT / g)):
            for d, n in re.findall(r'INCLUDE_ASM\("([^"]+)",\s*(\w+)\)', Path(f).read_text(errors="replace")):
                out[n] = d
    return out


def insn_count(asm_dir: str, name: str) -> int | None:
    p = ROOT / asm_dir / f"{name}.s"
    if not p.exists():
        return None
    return len(INSN_RE.findall(p.read_text(errors="replace")))


def small_unmatched(max_insns: int):
    rows = []
    for name, d in stubs().items():
        n = insn_count(d, name)
        if n is not None and n <= max_insns:
            rows.append({"name": name, "tu": d.split("/", 2)[-1], "insns": n})
    return sorted(rows, key=lambda r: (r["insns"], r["tu"], r["name"]))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--max-insns", type=int, default=15)
    ap.add_argument("--scan", action="append", default=[],
                    help="VER=candidates.json:ledger.md (repeatable)")
    a = ap.parse_args()
    scans = [("ntsc", ROOT / ".port_cache/candidates.json", ROOT / "decomp/port_ledger_pal.md")]
    for s in a.scan:
        ver, rest = s.split("=", 1); c, l = rest.split(":", 1)
        scans.append((ver, ROOT / c, ROOT / l))
    nm = near_misses(scans)
    sm = small_unmatched(a.max_insns)
    L = [f"# Easy pickups — `{VER}` convergence queue", "",
         "Generated by `tools/easy_pickups.py`; regenerate, don't hand-edit. Work top-down;",
         "the standard match loop applies (`decomp-match` / `decomp-sweep`), escalating to",
         "`decomp-convergence` only on a genuine stall. Crutch ban as in CLAUDE.md.", "",
         f"## 1. Near-miss ports ({len(nm)}) — another version's matched body, reverted `codegen` here",
         "", "Ranked by differing instructions. `first` is the port driver's first divergence.", "",
         "| # | PAL function | VMA | TU | from | source name | src/pal insns | diff | classes | first divergence |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(nm, 1):
        L.append(f"| {i} | `{r['name']}` | 0x{r['vma']:08X} | {r['tu']} | {r['src']} | `{r['src_name']}` | "
                 f"{r['src_insns']}/{r['pal_insns']} | {r['diff']} | {r['classes']} | {r['first'].replace('|','/')} |")
    L += ["", f"## 2. Small unmatched (≤ {a.max_insns} insns) — {len(sm)} functions, no port candidate needed", "",
          "| # | function | TU | insns |", "|---|---|---|---|"]
    for i, r in enumerate(sm, 1):
        L.append(f"| {i} | `{r['name']}` | {r['tu']} | {r['insns']} |")
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(nm)} near-miss ports, {len(sm)} small unmatched")


if __name__ == "__main__":
    main()
