#!/usr/bin/env python3
"""stub_rodata_inline.py — move an unmigrated rodata chunk from the
auto-generated `_data.c` sidecar to an `INCLUDE_RODATA(...)` reference
inside the tracked `src/<TU>.c`, with the raw `.byte` directives in
`asm/rodata/<TU>/<sym>.s`.

Use this for chunks the developer has consciously deferred — bytes
they don't intend to type in the current PR (compressed textures,
opaque struct arrays, etc.). Typed defs in tracked src count toward
progress; INCLUDE_RODATA chunks don't, but the symbol becomes
pinned to the owning TU and visible inline in the tracked source.

Usage: tools/stub_rodata_inline.py D_<VMA> [D_<VMA> ...]

For each symbol:
  1. Look up the owning TU via decomp/data_tu_map.json.
  2. Read the symbol's bytes from baserom/baseelf.elf at its VMA.
     Size comes from the migrator's emit shape in `_data.c`.
  3. Write `asm/rodata/<TU>/<sym>.s` containing the raw `.byte`
     directives (no `.section` — the macro handles that).
  4. Append `INCLUDE_RODATA("asm/rodata/<TU>", <sym>);` to the
     tracked `src/<TU>.c`.

The migrator's `_scan_existing_definitions()` doesn't currently see
INCLUDE_RODATA refs (it only matches `__attribute__((section)) D_X`
defs), so the chunk WILL get re-emitted in `_data.c` on the next
`make setup` — for now the developer must also strip it from
`_data.c` by hand or wait for migrate_data_per_tu.py to learn the
INCLUDE_RODATA shape. Track this in decomp/MATCH_DATA.md.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
ASM_RODATA = REPO / "asm" / "rodata"

# Reuse the data_tu_map for TU lookup.
import json
DATA_TU_MAP = REPO / "decomp" / "data_tu_map.json"

try:
    from elftools.elf.elffile import ELFFile
except ImportError as exc:
    sys.exit(f"stub_rodata_inline: missing dependency ({exc.name}).")

# Match every shape the migrator may emit. We need the byte size
# (and bytes themselves, if pre-typing) regardless of form.
DEF_SHAPES = [
    # `unsigned char D_X[N] = { ... };`
    (re.compile(
        r'__attribute__\(\(section\("\.(\w+)\.0x([0-9A-Fa-f]+)"\)\)\)\s+'
        r'(?:const\s+)?unsigned char (D_[0-9A-Fa-f]{8})\[(\d+)\]\s*=\s*\{'
    ), "byte_arr"),
    # `void *D_X[N] = { ... };` or `unsigned int D_X[N] = { ... };`
    (re.compile(
        r'__attribute__\(\(section\("\.(\w+)\.0x([0-9A-Fa-f]+)"\)\)\)\s+'
        r'(?:void \*|unsigned int) (D_[0-9A-Fa-f]{8})\[(\d+)\]\s*=\s*\{'
    ), "word_arr"),
    # `unsigned char D_X = 0xNN;` (singleton)
    (re.compile(
        r'__attribute__\(\(section\("\.(\w+)\.0x([0-9A-Fa-f]+)"\)\)\)\s+'
        r'unsigned char (D_[0-9A-Fa-f]{8})\s*=\s*0x[0-9A-Fa-f]+\s*;'
    ), "byte_one"),
]


def _find_def(sym: str) -> tuple[Path, str, int, int] | None:
    """Locate (data_c_path, sect, vma, size) for `sym` in any
    `_data.c`. Returns None if the sym isn't migrator-emitted."""
    for c_path in SRC.rglob("*_data.c"):
        text = c_path.read_text()
        if sym not in text:
            continue
        for regex, _kind in DEF_SHAPES:
            for m in regex.finditer(text):
                if m.group(3) != sym:
                    continue
                sect = m.group(1)
                vma = int(m.group(2), 16)
                size = int(m.group(4)) if m.lastindex >= 4 else 1
                return c_path, sect, vma, size
    return None


def _tu_for_sym(sym: str) -> str | None:
    if not DATA_TU_MAP.exists():
        return None
    d = json.loads(DATA_TU_MAP.read_text())
    rec = d.get(sym)
    if not rec:
        return None
    tu = rec.get("tu")
    if not tu:
        return None
    return tu[:-2] if tu.endswith(".c") else tu


def _read_bytes(vma: int, size: int) -> bytes:
    with (REPO / "baserom" / "baseelf.elf").open("rb") as fh:
        elf = ELFFile(fh)
        for seg in elf.iter_segments():
            if seg["p_type"] != "PT_LOAD":
                continue
            v_start = seg["p_vaddr"]
            v_end = v_start + seg["p_filesz"]
            if v_start <= vma < v_end:
                offset = seg["p_offset"] + (vma - v_start)
                fh.seek(offset)
                return fh.read(size)
    raise ValueError(f"VMA 0x{vma:08X} not in any PT_LOAD")


def _write_asm_blob(tu: str, sym: str, sect: str, vma: int,
                    data: bytes) -> Path:
    """Emit asm/rodata/<TU>/<sym>.s with raw bytes. The section attr
    is provided by the INCLUDE_RODATA macro's inline-asm wrapper."""
    folder = ASM_RODATA / Path(tu).name
    folder.mkdir(parents=True, exist_ok=True)
    out = folder / f"{sym}.s"
    lines = [
        f"/* Auto-generated by tools/stub_rodata_inline.py for {sym}.",
        f" * Section: .{sect}, VMA 0x{vma:08X}, {len(data)} bytes.",
        f" * Replace this with a typed definition in src/{tu}.c when",
        f" * the bytes get decoded. */",
        f".section .{sect}.0x{vma:08X}, \"a\"",
        f".global {sym}",
        f"{sym}:",
    ]
    # 16 bytes per .byte directive for readability.
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(".byte " + ", ".join(f"0x{b:02X}" for b in chunk))
    lines.append(".previous")
    out.write_text("\n".join(lines) + "\n")
    return out


def _append_include_rodata(tu: str, sym: str) -> None:
    """Append `INCLUDE_RODATA("asm/rodata/<TU>", <sym>);` to the
    tracked src/<TU>.c. Includes common.h if it isn't already."""
    tu_c = SRC / f"{tu}.c" if "/" not in tu else SRC / tu
    tu_c = tu_c.with_suffix(".c") if tu_c.suffix != ".c" else tu_c
    if not tu_c.exists():
        # Create a minimal anchor file (parappa2-style header).
        tu_c.parent.mkdir(parents=True, exist_ok=True)
        tu_c.write_text(
            f'/* src/{tu}.c */\n\n'
            f'#include "common.h"\n\n'
        )
    text = tu_c.read_text()
    if '#include "common.h"' not in text and '#include <common.h>' not in text:
        # Insert include after the first comment block / before defs.
        text = '#include "common.h"\n\n' + text
    # The macro wants the folder name relative to the asm-include's
    # include path. Use a literal folder string.
    folder_lit = f'"asm/rodata/{Path(tu).name}"'
    line = f'INCLUDE_RODATA({folder_lit}, {sym});\n'
    if line in text:
        return
    if not text.endswith("\n"):
        text += "\n"
    text += line
    tu_c.write_text(text)


def _strip_from_sidecar(c_path: Path, sym: str) -> None:
    """Remove the `__attribute__((section)) ... <sym> ... ;` line from
    its _data.c, so the next compile doesn't double-define. This is a
    best-effort one-pass match — works for both byte-array and pointer-
    array shapes the migrator emits."""
    text = c_path.read_text()
    # Match a full def ending in `};` or `;` (singleton).
    pat = re.compile(
        r'__attribute__\(\(section\("\.\w+\.0x[0-9A-Fa-f]+"\)\)\)'
        r'[^;]*?\b' + re.escape(sym) + r'\b[^;]*;[ \t]*\n?',
        re.DOTALL,
    )
    new_text, n = pat.subn("", text, count=1)
    if n == 1:
        c_path.write_text(new_text)


def main() -> int:
    if len(sys.argv) < 2:
        sys.exit("usage: stub_rodata_inline.py D_<VMA> [D_<VMA> ...]")
    for arg in sys.argv[1:]:
        sym = arg.strip()
        if not re.fullmatch(r'D_[0-9A-Fa-f]{8}', sym):
            print(f"skipping {arg}: not a D_<8hex>", file=sys.stderr)
            continue
        sym = "D_" + sym[2:].upper()
        found = _find_def(sym)
        if found is None:
            print(f"{sym}: not in any _data.c — already typed, or "
                  f"run tools/build.sh setup first.", file=sys.stderr)
            continue
        c_path, sect, vma, size = found
        tu = _tu_for_sym(sym)
        if tu is None:
            print(f"{sym}: no TU in data_tu_map.json", file=sys.stderr)
            continue
        data = _read_bytes(vma, size)
        asm_out = _write_asm_blob(tu, sym, sect, vma, data)
        _append_include_rodata(tu, sym)
        _strip_from_sidecar(c_path, sym)
        print(f"{sym}: stubbed to {asm_out.relative_to(REPO)}; "
              f"INCLUDE_RODATA added to src/{tu}.c")
    return 0


if __name__ == "__main__":
    sys.exit(main())
