#include "common.h"

INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEnd);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEne1Chk);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEne2Chk);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aDoorUp);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aHasiUpSub);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aHasiUp);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aTorchOnChk);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aTorchOffChk);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aDoor);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEne1);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEne2);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEnemy1);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEnemy2);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEnemy3);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aEnemy4);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aIntro);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aHint1);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aGirlPos);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aHasi);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aTorch);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aInit);
INCLUDE_ASM("asm/nonmatchings/src/st08a", func_00240EE8);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aDoorUpSub);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aIntroChk);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aGirlPosChk);
INCLUDE_ASM("asm/nonmatchings/src/st08a", actSt08aHint1Chk);
INCLUDE_ASM("asm/nonmatchings/src/st08a", func_00241190);
